- dev/create_google_dev_vm.py
> Removed obsolete instructions output.

- dev/build_release.py
Also updated usage instructions.
> Generate bintray packages if needed.

- InstallSpinnaker.sh
> Add install option for dependencies only -- no spinnaker services

- README.adoc
> Remove note about packer.

- pylib/spinnaker/transform_old_config.py
@duftler Fixes a non-fatal bug for whatever the next build.
> Removed redudnant attribute

- dev/bootstrap_dev.sh
- dev/install_development.sh
@duftler Rewrote the install_development.sh and updated the dev/bootstrap_dev.sh script.
> Refactored install_development.sh to use production install

- pylib/spinnaker/spinnaker_runner.py
> Fix run_dev

- pylib/spinnaker/configurator.py
- pylib/spinnaker/reconfigure_spinnaker.py
> Fixes reconfigure_spinnaker.sh to behave properly when not run as root.

- README.adoc
Also, removed the deprecated --package_manager option in install_development.sh
> Updated run_dev instructions.

- pylib/spinnaker/transform_old_config.py
- pylib/spinnaker/yaml_util.py
- unittest/yaml_util_test.py
> Moved yaml transform method.

- README.adoc
- dev/dev_runner.py
- pylib/spinnaker/spinnaker_runner.py
> Auto-generate spinnaker-local.yml on run_dev first's run.

- config/settings.js
> Sync feature block in settings.js.

- dev/build_release.py
> Removed obsolete tar packaging.

- dev/bootstrap_dev.sh
- dev/create_google_dev_vm.py
Added checks for gcloud and copy over configuration to avoid the oauth flow
on the other end.
Default to "upstream" rather than the gituser so by default you dont need forked repos.
Refactored copying files to copy lists of files.
Copy .gradle/gradle.properties
> Updated script to create google development environment

- dev/create_google_dev_vm.py
> Check for not ready error.

- dev/create_google_dev_vm.py
@duftler Detect invalid json credential path when copying credentials over.
> Fixed typo reporting errors

- pylib/spinnaker/spinnaker_runner.py
> Always start rush

- InstallSpinnaker.sh
- pylib/spinnaker/fetch.py
> Dont hang checking for aws

- dev/create_google_dev_vm.py
@ewiseblatt or @skim1420 please review.
> Add tunneling of port 8087 to gcloud command in instructions.

- experimental/docker-compose/README.md
changed the name of the docker machine to be spinnakergcp
use docker-machine scp and docker-machine ssh where appropriate. ( this will simplify instructions for azure and aws ) 
@duftler ptal
> Docker machine commands

- install/first_google_boot.sh
> Adds apt-mark hold/unhold around doing apt-get updates

- install/first_google_boot.sh
> Dont fail if no config is provided.

- experimental/docker-compose/docker-compose.yml
- experimental/kubernetes/2-repContollers.yml
Deck just seems unable to consistently build on docker hub automated builds.
> use images in quay.io

- experimental/kubernetes/README.md
> Replace `app` with `component` in pod query.

- experimental/kubernetes/0-dependencies.yml
> Fix typo in redis parameter.

- experimental/kubernetes/README.md
> Fix 2 typos.

- experimental/kubernetes/README.md
> Drop quotes.

- experimental/kubernetes/README.md
> Fix aws creds copy command.

- InstallSpinnaker.sh
- build.gradle
- pkg_scripts/preInstall.sh
Uses package manager where it can and uses direct download where it cannot of DOWNLOAD is true
Fixed a couple other bugs when performing a non-standard installation
@skorten
> Fix startup local install

- experimental/kubernetes/README.md
Need enough cpu capacity when running everything on one node.
@ttomsu please review.
> Specify explicit machine type for container nodes.

- unittest/configurator_test.py
> Allow Configurator unittest to be run from any directory.

- dev/build_release.py
When publishing InstallSpinnaker.sh to bintray from dev/build_spinnaker.sh, it
is not uncommon to get a 409 error. I think this is because the content changes but
version numbers do not (until the project is explicitly released). To work around
this, when encountering a 409 publising an update, try to delete the exiting content
and retry.
> Handle bintray 409

- config/clouddriver.yml
- config/default-spinnaker-local.yml
- config/settings.js
- config/spinnaker.yml
This patch will add Cloud Foundry property settings to the default configuration.
It also updates echo with slack settings.
> Add CF support to prop files

- pylib/spinnaker/configurator.py
This change is related to this pull request in deck:
https://github.com/spinnaker/deck/pull/1851
More information in the deck pull request. This should not be merged unless the deck pull request is merged.
@cfieber here is the change you requested.
> Related to pull request in deck, move install dir from /var/www to /var/www/html

- google/dev/publish_gce_release.sh
> Add gcloud --service_account parameter

- pkg_scripts/postInstall.sh
> Dont touch existing spinnaker-local.yml file when upgrading

- config/settings.js
- etc/apache2/sites-available/spinnaker.conf
updated apache site config to reflect new DocumentRoot /var/www/html changed in https://github.com/spinnaker/deck/pull/1851
changed let to var for cf settings in the reconfigure block of config/settings.js
> updated settings.js and apache conf deck v2.488

- InstallSpinnaker.sh
@dpeterka 
We are seeing occasional failures where a repository is temporarily unavailable (usually its the packer download) so want the caller to know the install failed. I'm not signing my private repository so I'm allowing there not to be a key. If you think we should require it to be signed then I'll make the other changes I need to sign it and take that change out of this PR.
> Fail install on errors.

- install/first_google_boot.sh
@duftler 
DO NOT MERGE
I havent tested this yet. I'm just catching you in your travel window.
Looking for approval assuming this works (as is or with trivial variation).
I'll merge after verifying (if you lgtm)
> Try waiting for cassandra thrift before upgrading.

- pylib/spinnaker/configurator.py
- pylib/spinnaker/yaml_util.py
- unittest/yaml_util_test.py
@AMeng 
I havent fully confirmed this yet. It is going to take me a while. However I believe this works.
You can review it and try it out to verify it fixes your problem.
> Fixed yaml replace() to return typed values rather than forcing strings

- config/default-spinnaker-local.yml
- config/settings.js
- config/spinnaker.yml
The current settings.js file is outdated compared to the one in deck. This pulls in most of the latest changes. Some of the things in the deck version appear to be for internal use only? I wasn't sure if everything should be copied directly.
https://github.com/spinnaker/deck/blob/master/settings.js
> Sync settings.js with deck

- experimental/kubernetes/spinnaker-local.yml
Per https://github.com/spinnaker/spinnaker/issues/678
> Disables AWS in experimental/kubernetes by default

- experimental/kubernetes/README.md
https://github.com/spinnaker/spinnaker/issues/678
> Removes AWS references from kubernetes instructions

- experimental/kubernetes/spinnaker-local.yml
From https://github.com/spinnaker/spinnaker/issues/678
> Remove inconsistent header documentation

- README.adoc
It's not made clear in the README that Spinnaker lives in several repos, or how they interact. See [1](https://news.ycombinator.com/item?id=10579296), [2](https://www.reddit.com/r/devops/comments/3t4w5b/netflix_released_a_cicd_tool/cx4h5wg), [3](https://www.reddit.com/r/devops/comments/3t4w5b/netflix_released_a_cicd_tool/cx37be2). I figured it wouldn't hurt to put a link to the developer guide which clears this up.
@rbuskens
> Add a link to the developer guide.

- dev/bootstrap_dev.sh
- experimental/packer/configure.sh
Packer files are no longer on bin tray.
> Packer url moved

- config/clouddriver.yml
Feel free to accept it or reject it in case it doesn't look right
> Fixed path for cf account name + password

- config/default-spinnaker-local.yml
- config/spinnaker.yml
> Update AWS config comments in spinnaker*.yml

- README.adoc
Make setup more clear for #771.
> Update mac instructions for cassandra

- config/clouddriver.yml
- config/default-spinnaker-local.yml
- config/spinnaker.yml
> provider/kubernetes: Default credentials in default-spinnaker-local.yml

- config/default-spinnaker-local.yml
- config/igor.yml
- config/spinnaker.yml
- experimental/docker-compose/docker-compose.yml
@duftler 
Useful for https://github.com/spinnaker/igor/pull/64
> Add clouddriver baseUrl to igor to enable docker polling

- config/igor.yml
> Remove circular dependency on services

- dev/build_google_image.packer
- dev/build_google_image.sh
- dev/create_google_dev_vm.py
- google/google_cloud_logging/add_google_cloud_logging.sh
- google/google_cloud_logging/spinnaker.conf
Adds support for Google Cloud Logging when building GCE images.
Also adds script into google/google_cloud_logging for adhoc installation.
We'll need to make this available
> Add Google Cloud Logging to GCE image.

- dev/build_google_image.packer
> Install Google Cloud Monitoring into GCE image

- google/google_cloud_logging/spinnaker.conf
> Fixed Google Cloud Logging configuration

- config/echo.yml
This is a fix for issue: Spinnaker #799
> Add spring.mail.host property to echo.yml to adhere to use of spring boot mail starter

- config/default-spinnaker-local.yml
- config/spinnaker.yml
- install/first_google_boot.sh
> Configure Kubernetes on GCE and fixed its config files.

- install/first_google_boot.sh
> Ignore empty metadata values

- README.adoc
This PR updates some of the links, titles, and copy in the main README file to fix broken links.
> Updated links to the Spinnaker docks

- experimental/kubernetes/README.md
- experimental/kubernetes/config/clouddriver-local.yml
> Simplifies sample registries included in clouddriver-local.yml

- InstallSpinnaker.sh
> Replace distro -ne check with -lt.

- config/clouddriver.yml
- config/default-spinnaker-local.yml
> Updated comments for adding multiple accounts

- config/default-spinnaker-local.yml
- config/igor.yml
This adds travis configuration skeleton.
Relates to this pr in igor that has been merged. https://github.com/spinnaker/igor/pull/74
> igor/travis: Configuration templates

- InstallSpinnaker.sh
Changed flow around getting cassandra to avoid failing and exiting the script if `apt-get install` fails. It now uses `apt-cache search` to check if any cassandra packages are available in APT. Otherwise, it pulls the debs explicitly and installs. ~~Also added flags to populate `/etc/default/spinnaker` with defaults for Google project id and service account credential path.~~
> Changed flow around getting cassandra to avoid failing, added flags.

- InstallSpinnaker.sh
Cassandra install fix variable spelling error.
> Cassandra install fix variable spelling error.

- config/default-spinnaker-local.yml
- config/spinnaker.yml
Addresses comment by @ewiseblatt in https://github.com/spinnaker/spinnaker/pull/850
> Set default kubernetes namespace in config

- config/default-spinnaker-local.yml
- config/settings.js
- config/spinnaker.yml
Configures the notifications displayed in the UI based on Echo's configuration.
@ewiseblatt PTAL - I'm guessing this will work as expected, but am not sure how to verify it...
> Configure notifications in Deck

- pylib/spinnaker/configurator.py
> Write empty strings to settings.js

- pylib/spinnaker/configurator.py
- pylib/spinnaker/reconfigure_spinnaker.py
@anotherchrisberry 
This is to support testing your earlier PR.
Dont merge this yet until we resolve the issue or it is going to prevent people from being able to run Spinnaker at all. For that matter, you can argue this should be a soft error, but I think a hard error forcing a fix is appropriate.
> Check for unresolved spring variables in settings.js

- InstallSpinnaker.sh
Use consistent bash syntax.
Cleaned up some comments.
Declare and document some global variables (using boolean values).
Fixed azure config with --quiet.
Deprecated "both" --cloud_provider option.
@dpeterka @rguthriemsft
> Cleaned up install script to make more internally consistent.

- config/clouddriver.yml
- config/default-spinnaker-local.yml
- config/spinnaker.yml
@rguthriemsft FYI I linked to a non-existent section for Azure. When you update http://www.spinnaker.io/docs/target-deployment-setup, use the section tag I'm assuming based on the pattern of the others.
@lwander Please review. Particularly the mention of kubernetes dependencies.
> Cleaned up config file comments and ensure default values for env vars.

- pylib/spinnaker/validate_configuration.py
- pylib/spinnaker/yaml_util.py
- unittest/validate_configuration_test.py
- unittest/yaml_util_test.py
Fixes https://github.com/spinnaker/spinnaker/issues/874
@lwander
> Look for either .yml or .yaml in scripting support

- pylib/spinnaker/codelab_config.py
Fixed codelab config property names.
> Fixed codelab config property names.

- google/codelab/provision_spinnaker_codelab_image.sh
Added script to provision base spinnaker image for codelab. @ewiseblatt PTAL.
> Added script to provision base spinnaker image for codelab.

- google/codelab/provision_spinnaker_codelab_image.sh
Fix for correct Jenkins user home directory in codelab script. @ewiseblatt FYI.
> Fix for correct Jenkins user home directory in codelab script.

- google/codelab/provision_spinnaker_codelab_image.sh
Added codelab startup script to gcs bucket, copies to machine during startup. @ewiseblatt FYI.
> Added codelab startup script to gcs bucket, copies to machine.

- config/settings.js
Do not merge until https://github.com/spinnaker/gate/pull/230 is merged.
@spinnaker/google-reviewers FYI
> New authEndpoint

- install/first_google_boot.sh
> docker: Make GCR the default registry

- config/clouddriver.yml
- config/default-spinnaker-local.yml
- config/spinnaker.yml
surfaces defaultKeyPairTemplate in yml. @duftler PTAL
> surfaces defaultKeyPairTemplate in yml

- InstallSpinnaker.sh
> Set default google project

- config/settings.js
- added useAmiBlockDeviceMappings field to settings.js 
@duftler
> added useAmiBlockDeviceMappings field to settings.js

- pylib/spinnaker/configurator.py
- pylib/spinnaker/transform_old_config.py
- pylib/spinnaker/yaml_util.py
@jtk54 
Write back quotes into YAML files when they are required.
> Inject non-superfluous quotes when rewriting yaml

- InstallSpinnaker.sh
- pkg_scripts/postInstall.sh
Removed unnecessary apache conf removal, listener overwrites. @ewiseblatt PTAL.
> Removed unnecessary apache conf removal, listener overwrites.

- pylib/spinnaker/change_cassandra.py
- pylib/spinnaker/yaml_util.py
@jtk54 I inadvertantly changed ownership of the files in my previous PR
> fix ownership in change_cassandra

- pylib/spinnaker/validate_configuration.py
Fix for https://github.com/spinnaker/spinnaker/issues/949
@wgjohnson verify this satisfies your needs and expectations.
@duftler review
> Check ownership of sensitive files.

- pylib/spinnaker/transform_old_config.py
- pylib/spinnaker/yaml_util.py
- unittest/yaml_util_test.py
Fixed yaml_util writing captalized booleans to config. @lwander PTAL. @ewiseblatt FYI.
> Fixed yaml_util writing captalized booleans to config.

- google/dev/google_install_loader.py
Fixed remote file exploding from metadata and docstrings. @lwander PTAL. @ewiseblatt FYI.
> Fixed remote file exploding from metadata and docstrings.

- InstallSpinnaker.sh
- etc/init/spinnaker.conf
- pkg_scripts/postInstall.sh
- pylib/spinnaker/change_cassandra.py
Removed Cassandra waiting from upstart config. This hangs for people not using Cassandra on localhost. Replaced with reporting. @lwander PTAL. @ewiseblatt FYI.
> Removed Cassandra waiting from upstart config.

- config/clouddriver.yml
- experimental/kubernetes/README.md
- experimental/kubernetes/config/front50-local.yml
- experimental/kubernetes/config/spinnaker-local.yml
- experimental/kubernetes/rcs/spin-front50.yaml
- experimental/kubernetes/scripts/cleanup-config.sh
- experimental/kubernetes/scripts/startup-config.sh
> provider/kubernetes: Make s3 persistence easier to set up

- consul/README.md
@duftler 
Here I'll be updating the consul + spinnaker integration documentation w.r.t. consul setup. I'll add documentation as the scripts for setup are added. I think this leaves a nice audit trail.
> Consul readme

- consul/README.md
- consul/config/server/config.json
- consul/install/install.sh
- consul/upstart/consul.conf
This gives some details around a sane boostrapping process for the sake of Consul leader election.
@duftler
> provider/consul: Document server setup

- config/front50.yml
- config/spinnaker.yml
> Add bucket location to default GCS config

- config/default-spinnaker-local.yml
- config/fiat.yml
- config/spinnaker.yml
Fiat feature flagged as disabled globally.
@jtk54 @ewiseblatt PTAL.
@duftler @cfieber FYI
> Adds fiat config files. Disabled by default.

- consul/README.md
- consul/upstart/consul.client.conf
- consul/upstart/consul.server.conf
> provider/consul: Describe spinnaker setup

- consul/README.md
> Fix upstart directory

- experimental/kubernetes/README.md
@duftler - I forgot to remove this reference when I remove cassandra as a pipeline store option.
> Remove reference to Cassandra

- experimental/kubernetes/rcs/spin-deck.yaml
> provider/kubernetes: New kubectl env values require strings

- config/orca.yml
- config/spinnaker.yml
- experimental/kubernetes/config/orca-local.yml
- experimental/kubernetes/config/spinnaker-local.yml
This was dropped from orca here: https://github.com/spinnaker/orca/pull/922
> Drop propagateCloudProviderType flag.

- pylib/spinnaker/codelab_config.py
@danielpeach please review @ewiseblatt FYI.
> Disable destructive action challenge for codelab.

- config/clouddriver.yml
- config/default-spinnaker-local.yml
- config/spinnaker.yml
- install/first_google_boot.sh
@ewiseblatt PTAL, @duftler FYI
> (consul) default config

- install/first_google_boot.sh
> (kubernetes) failed to query by zone and move credentials to spinnaker directory

- install/first_google_boot.sh
> update gcloud in first_google_boot

- config/settings.js
@danielpeach - This hooks up the feature flag you added in https://github.com/spinnaker/deck/pull/2662
@danielpeach, @ewiseblatt - PTAL
> Adds fiatEnabled flag to autoconfigured settings.js

- README.adoc
We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](http://spinnaker.io/online_docs/community/contributing_guidelines.html) and [On Collaborative Development](http://spinnaker.io/documentation/collab_dev.html).
When filling out a pull request, please consider the following:
* Provide a descriptive title for your changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days. 
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to …
> Fixed a typo in README.adoc

- experimental/kubernetes/simple/README.md
Replaces: https://github.com/spinnaker/spinnaker/pull/1045
@duftler
> (kubernetes) clearup iam requirements

- install/first_google_boot.sh
@ewiseblatt PTAL
If the user now provides "gcr_enabled" as instance metadata, but does not
supply an email address, the default compute service account is used.
Also the user can optionally provide which GCR registry to use.
The next set of changes will allow a user to specify where their kube cluster is.
> (gcr) simplify lookup of service account email

- experimental/docker-compose/docker-compose.dev.yml
- experimental/docker-compose/docker-compose.override.yml
- experimental/docker-compose/docker-compose.remote.yml
- experimental/docker-compose/docker-compose.yml
@spinnaker/reviewers @ttomsu  PTAL
linked to https://github.com/spinnaker/fiat/pull/79
> Fiat docker-compose config

- install/first_google_boot.sh
> (gcr) more reliable way of retrieving service account key

- config/fiat.yml
> Rm a few obsolete fiat settings

- consul/README.md
- consul/codelab/README.md
- consul/install/install.sh
> (consul) this captures the GCE setup side for getting consul to work with Spinnaker

- experimental/kubernetes/simple/README.md
Btw, it also created the service account in the wrong project.
> Fix readme command

- consul/codelab/README.md
- consul/install/install.sh
- install/first_google_boot.sh
> (consul) fix install bugs, and add rosco config section

- config/clouddriver.yml
- config/default-spinnaker-local.yml
- config/gate.yml
- config/igor.yml
- config/spinnaker.yml
- etc/default/spinnaker
- google/stackdriver_monitoring/http_server.py
- google/stackdriver_monitoring/metric_collector.py
- google/stackdriver_monitoring/metric_collector_handlers.py
- google/stackdriver_monitoring/metric_collector_handlers_test.py
- google/stackdriver_monitoring/sample_filter.json
- google/stackdriver_monitoring/spectator_client.py
- google/stackdriver_monitoring/spectator_client_test.py
- google/stackdriver_monitoring/stackdriver_client.py
> Configuration to support stackdriver.

- InstallSpinnaker.sh
@duftler 
I updated my machine with these versions and ran a bake and deploy test so packer seems ok.
redis is where netflix is.
> Updated versions for redis/jemalloc and packer

- testing/citest/README.md
- testing/citest/requirements.txt
- testing/citest/spinnaker_testing/__init__.py
- testing/citest/spinnaker_testing/expression_dict.py
- testing/citest/spinnaker_testing/frigga.py
- testing/citest/spinnaker_testing/front50.py
- testing/citest/spinnaker_testing/gate.py
- testing/citest/spinnaker_testing/jenkins_agent.py
- testing/citest/spinnaker_testing/kato.py
- testing/citest/spinnaker_testing/scrape_spring_config.py
- testing/citest/spinnaker_testing/spinnaker.py
- testing/citest/spinnaker_testing/spinnaker_test_scenario.py
- testing/citest/spinnaker_testing/yaml_accumulator.py
- testing/citest/tests/aws_kato_test.py
- testing/citest/tests/aws_smoke_test.py
- testing/citest/tests/bake_and_deploy_test.py
- testing/citest/tests/google_front50_test.py
- testing/citest/tests/google_http_lb_upsert_scenario.py
- testing/citest/tests/google_http_lb_upsert_server_test.py
- testing/citest/tests/google_http_lb_upsert_test.py
- testing/citest/tests/google_kato_test.py
- testing/citest/tests/google_server_group_test.py
- testing/citest/tests/google_smoke_test.py
- testing/citest/tests/kube_smoke_test.py
- testing/citest/unittests/expression_dict_test.py
- testing/citest/unittests/yaml_accumulator_test.py
@duftler 
I had jake create a copy of the spinnaker repo and merged this into that copy to see how github would handle the pull request. It looks reasonable (https://github.com/jtk54/eric-test/commits/master?after=8hVGTky%2FTNlW44nHR8LwxYtFrHgrMzQ%3D). Note his copy was from may so you have to go back to see the interleaving of history.
@ajordens FYI
> Migrate citest

- experimental/kubernetes/simple/README.md
Avoid situations like these: https://github.com/spinnaker/spinnaker/issues/1140
> Warn against editing wrong config

- testing/citest/tests/google_front50_test.py
- testing/citest/tests/google_http_lb_upsert_scenario.py
> Fixed l7 test for refactoring and front50 for latency

- build.gradle
> publish InstallSpinnaker.sh during release process

- testing/citest/README.md
- testing/citest/tests/aws_kato_test.py
- testing/citest/tests/aws_smoke_test.py
- testing/citest/tests/google_front50_test.py
- testing/citest/tests/google_http_lb_upsert_scenario.py
- testing/citest/tests/google_kato_test.py
- testing/citest/tests/google_server_group_test.py
- testing/citest/tests/google_smoke_test.py
> Rewrote contracts to use DICT_MATCHES and LIST_MATCHES.

- testing/citest/tests/google_http_lb_upsert_scenario.py
> Fixed google httplb test

- experimental/kubernetes/ha/clouddriver/cache/rcs/spin-clouddriver-cache.yaml
- experimental/kubernetes/ha/clouddriver/mutate/rcs/spin-clouddriver-mutate.yaml
- experimental/kubernetes/ha/clouddriver/ro/rcs/spin-clouddriver-readonly.yaml
- experimental/kubernetes/ha/deck/rcs/spin-deck.yaml
- experimental/kubernetes/ha/echo/event/rcs/spin-echo-event.yaml
- experimental/kubernetes/ha/echo/sched/rcs/spin-echo-sched.yaml
- experimental/kubernetes/ha/front50/rcs/spin-front50.yaml
- experimental/kubernetes/ha/gate/rcs/spin-gate.yaml
- experimental/kubernetes/ha/igor/rcs/spin-igor.yaml
- experimental/kubernetes/ha/orca/rcs/spin-orca.yaml
- experimental/kubernetes/ha/rosco/rcs/spin-rosco.yaml
- experimental/kubernetes/simple/README.md
- experimental/kubernetes/simple/rcs/spin-clouddriver.yaml
- experimental/kubernetes/simple/rcs/spin-deck.yaml
- experimental/kubernetes/simple/rcs/spin-echo.yaml
- experimental/kubernetes/simple/rcs/spin-front50.yaml
- experimental/kubernetes/simple/rcs/spin-gate.yaml
- experimental/kubernetes/simple/rcs/spin-igor.yaml
- experimental/kubernetes/simple/rcs/spin-orca.yaml
> Change release tag from `:latest` to `:master`

- testing/citest/tests/bake_and_deploy_test.py
- testing/citest/tests/kube_smoke_test.py
> Fixed bake and deploy and kubernetes smoke tests.

- dev/build_release.py
> Disable deck tests when CHROME_BIN isnt set

- config/clouddriver.yml
- config/default-spinnaker-local.yml
- config/echo.yml
- config/fiat.yml
- config/front50.yml
- config/gate.yml
- config/igor.yml
- config/orca.yml
- config/rosco.yml
- config/spinnaker.yml
- google/stackdriver_monitoring/stackdriver_client.py
> Configure spectator/stackdriver per service rather than globally

- install/first_google_boot.sh
If the contents of your `~/.kube/config` file are passed as the instance
metadata parameter `kube_config`, and you do not specify the GKE cluster you
wish to manage with `kube_cluster`, that file's contents will be used as the
credentials to manage your kubernetes cluster with Spinnaker.
@ewiseblatt PTAL
> (kubernetes) provide first_google_boot with kube_config

- install/first_google_boot.sh
> (kubernetes) fix result of `attempt_write_kube_credentials`

- google/README.txt
> Remove obsolete directories in directory layout

- config/front50.yml
> Specific S3 as front50 backend stackdriver hints

- config/gate.yml
- config/igor.yml
> Add stackdriver hints.

- testing/citest/spinnaker_testing/spinnaker_test_scenario.py
- testing/citest/tests/google_front50_test.py
@jtk54 
front50 is being refactored. When adam submits then we'll need these changes to complement it.
> Modified tests for front50 migration to v2 API

- config/default-spinnaker-local.yml
- config/echo.yml
- config/spinnaker.yml
Disable Cassandra and enable in-memory by default for echo.
> Disable cassandra by default for echo.

- config/front50.yml
- dev/create_google_dev_vm.py
> Added stackdriver hint

- google/stackdriver_monitoring/http_server.py
- google/stackdriver_monitoring/metric_collector.py
- google/stackdriver_monitoring/metric_collector_handlers.py
- google/stackdriver_monitoring/metric_collector_handlers_test.py
- google/stackdriver_monitoring/spectator_client.py
- google/stackdriver_monitoring/spectator_client_test.py
- google/stackdriver_monitoring/stackdriver_client.py
- google/stackdriver_monitoring/stackdriver_handlers.py
@lwander 
Segregated stackdriver stuff into its own modules to make it easier to add another option.
Support text or html so command line tool has readable output.
Other cleanups while I'm here.
> refactored metric collector tool.

- testing/citest/README.md
> List dependency on libffi-dev

- google/stackdriver_monitoring/metric_collector.py
- google/stackdriver_monitoring/spectator_client.py
Added skeleton into metric_collector for externally monitoring metrics.
> Added control loop and helper functions for monitoring metrics.

- google/stackdriver_monitoring/command_processor.py
- google/stackdriver_monitoring/dummy_service.py
- google/stackdriver_monitoring/http_server.py
- google/stackdriver_monitoring/metric_collector.py
- google/stackdriver_monitoring/spectator_client.py
- google/stackdriver_monitoring/stackdriver_client.py
> Cleanup command processing.

- dev/build_release.py
@jtk54 
This is obsolete (and now broken with tests removed from citest repo)
> Dont package tests into release.

- google/stackdriver_monitoring/datadog_service.py
- google/stackdriver_monitoring/server_handlers.py
- google/stackdriver_monitoring/stackdriver_handlers.py
- google/stackdriver_monitoring/stackdriver_service.py
Other small tweaks.
@ttomsu 
I think this fixes all the issues we ran into yesterday afternoon.
> Dont assume metric monitor tool is running on GCE

- config/default-spinnaker-local.yml
- config/rosco.yml
> Adding Azure bake config to default spinnaker local

- consul/config/bootstrap-consul.sh
This works by either joining the current MIG, or joining a metadata-provided list of known consul members
@ewiseblatt or @duftler PTAL
Note the install scripts automatically package this onto the consul base images.
> (consul) bootstrap script for starting consul

- config/clouddriver.yml
- config/default-spinnaker-local.yml
@ewiseblatt @duftler @scotmoor PTAL
> Adding Azure keyvault config to spinnaker-local

- google/dev/build_google_tarball.py
> Fixes build_google_tarball to specify project when deleting snapshot

- pylib/spinnaker/yaml_util.py
- unittest/yaml_util_test.py
> Handle SPEL concatenation in python scripts

- config/clouddriver.yml
- config/front50.yml
- config/gate.yml
- config/igor.yml
- config/orca.yml
- config/rosco.yml
> removed deprecated stackdriver hints.

- testing/citest/tests/google_kato_test.py
@duftler
This depends on https://github.com/google/citest/pull/241
> Fix available google image test

- pylib/spinnaker/yaml_util.py
- unittest/validate_configuration_test.py
- unittest/yaml_util_test.py
> Fixed corner cases for python scripts interpreting spring yaml

- google/dev/delete_resources.py
> Added tool to facilitate deleting GCP resources.

- google/stackdriver_monitoring/datadog_service.py
- google/stackdriver_monitoring/spectator_client.py
Keep stats on number of data points collected.
@jtk54
> Optionally log metric deltas across polls in metric_tool.

- etc/apache2/sites-available/spinnaker.conf
@duftler (this should no longer be needed, right?)
> Remove Rosco port from Apache2 ProxyPass config

- experimental/kubernetes/simple/rs/data-redis-master.yaml
- experimental/kubernetes/simple/rs/data-redis-sentinel.yaml
- experimental/kubernetes/simple/rs/data-redis-server.yaml
- experimental/kubernetes/simple/rs/spin-clouddriver.yaml
- experimental/kubernetes/simple/rs/spin-deck.yaml
- experimental/kubernetes/simple/rs/spin-echo.yaml
- experimental/kubernetes/simple/rs/spin-front50.yaml
- experimental/kubernetes/simple/rs/spin-gate.yaml
- experimental/kubernetes/simple/rs/spin-igor.yaml
- experimental/kubernetes/simple/rs/spin-orca.yaml
- experimental/kubernetes/simple/scripts/startup-cluster-redis.sh
- experimental/kubernetes/simple/scripts/startup-redis.sh
- experimental/kubernetes/simple/scripts/startup-spinnaker.sh
- experimental/kubernetes/simple/scripts/update-component.sh
I also dropped the startup command in the deck image that's no longer necessary since deck now runs on apache.
> Switch from deploying replication controllers to replica sets

- config/settings.js
- experimental/kubernetes/ha/deck/config/settings.js
- experimental/kubernetes/simple/config/settings.js
> add default k8s proxy

- experimental/kubernetes/ha/redis/cleanup-components.sh
- experimental/kubernetes/ha/redis/rs/redis-clouddriver-master.yaml
- experimental/kubernetes/ha/redis/rs/redis-clouddriver-slave.yaml
- experimental/kubernetes/ha/redis/rs/redis-fiat-master.yaml
- experimental/kubernetes/ha/redis/rs/redis-gate-master.yaml
- experimental/kubernetes/ha/redis/rs/redis-igor-master.yaml
- experimental/kubernetes/ha/redis/rs/redis-orca-master.yaml
- experimental/kubernetes/ha/redis/rs/redis-rosco-master.yaml
- experimental/kubernetes/ha/redis/startup-components.sh
@lwander is this all that's needed to make Replication Controllers into ReplicaSets?
> Redis RCs -> RS

- google/stackdriver_monitoring/SampleDatadogTimeboard.json
- google/stackdriver_monitoring/SamplePrometheusGrafanaDashboard.json
- google/stackdriver_monitoring/prometheus_service.py
- google/stackdriver_monitoring/spectator_client.py
> Updated experimental monitoring support.

- google/stackdriver_monitoring/MinimalDatadogTimeboard.json
- google/stackdriver_monitoring/MinimalPrometheusGrafanaDashboard.json
- google/stackdriver_monitoring/README.md
- google/stackdriver_monitoring/SampleDatadogTimeboard.json
- google/stackdriver_monitoring/SamplePrometheusGrafanaDashboard.json
- google/stackdriver_monitoring/create_install_tar.sh
- google/stackdriver_monitoring/datadog_handlers.py
- google/stackdriver_monitoring/requirements.txt
- testing/citest/README.md
Added minimal dashboards.
@duftler
> Package monitoring tool as a zip file

- dev/build_google_image.packer
> Set packer ssh_username.

- experimental/kubernetes/simple/scripts/cleanup-spinnaker.sh
@lwander updating this script to cleanup the replica sets.
> fixing simple cleanup script for replica sets

- config/default-spinnaker-local.yml
- config/front50.yml
- config/spinnaker.yml
This config enables the work done in this pull request:
https://github.com/spinnaker/front50/pull/185
> Add config for front50 using Azure Storage

- config/front50.yml
- config/spinnaker.yml
> Allow front50 gcs to be configured from spinnaker-local.yml

- config/clouddriver.yml
- config/default-spinnaker-local.yml
- config/settings.js
- config/spinnaker.yml
@lwander or @duftler please review.
> (appengine) config

- testing/citest/tests/bake_and_deploy_test.py
> Dont require --jenkins_master or --jenkins_url for bake_and_deploy_test.

- config/rosco.yml
@robumberger, @scotmoor, @duftler PTAL.
> Update rosco.yml - fixing issue with yaml for objectID

- install/first_google_boot.sh
@lwander or @spinnaker/google-reviewers
> Dont update gcloud on boot

- experimental/kubernetes/simple/config/settings.js
@lwander please review.
@emptywee FYI
> adds auth endpoint to k8s/simple settings.js

- testing/citest/spinnaker_testing/spinnaker_test_scenario.py
- testing/citest/tests/appengine_smoke_test.py
> added app engine smoke test

- dev/annotate_source.py
- dev/generate_bom.py
Note that this script requires `hal` to be installed. This generates the BOM file and writes it to local. `hal` will be responsible for publishing the BOM to the correct bucket.
> feat(bom): BOM generation tool.

- experimental/kubernetes/simple/README.md
Updated `experimental/simple/README.md` to make the startup instructions clearer and mention that you must first create the S3 bucket, per @lwander.
> Corrected and enhanced `experimental/simple/README.md`.

- .github/PULL_REQUEST_TEMPLATE.md
@ewiseblatt FYI the links in the previous template were broken.
> fix(PR Template): Fixed broken links to docs.

- dev/refresh_source.py
> Add halyard to source refresh script as optional

- dev/build_release.py
- dev/refresh_source.py
Fixed --nobuild option
Fixed optional directories not available.
@jtk54
> fix(dev): Minor fixes to special cases in build_release

- dev/build_release.py
- dev/generate_bom.py
> chore(dev): Cleaned up build_release

- dev/annotate_source.py
- dev/generate_bom.py
This generates the changelog using `clog-cli` and writes it to a file. I'll add the changelog publication step soon.
> feat(bom): Generate and write changelog.

- dev/build_prevalidation.py
- dev/build_release.py
- dev/generate_bom.py
Depends on https://github.com/spinnaker/halyard/pull/232.
> feat(build): Add spinnaker-monitoring to bom and build.

- dev/annotate_source.py
- dev/build_prevalidation.py
- dev/generate_bom.py
- dev/promote_bom.py
Also:
* renames the BOM to '{branch}-{datestring}-{buildnumber}'
* Adds a mandatory version argument during BOM promotion.
> Add 'spinnaker' to the release BOM.

- pylib/spinnaker/change_cassandra.py
> fix(dev): Fixed change_cassandra for disabling cassandra.

- dev/build_prevalidation.py
- dev/build_release.py
> fix(build): Replaces removed workflow to build debs with main in

- dev/generate_bom.py
> fix(changelog): Fix broken URLs by invoking 'clog' properly.

- InstallSpinnaker.sh
- dev/build_google_image.sh
- dev/build_release.py
@skim1420 
Not sure what happened. I'm testing this now.
> Fixed corrupted submit

- dev/build_google_image.sh
- dev/create_google_dev_vm.py
- etc/default/spinnaker
> fix(dev): Fixed warnings in build_google_image

- testing/citest/README.md
- testing/citest/requirements.txt
- testing/citest/spinnaker_testing/spinnaker_test_scenario.py
- testing/citest/tests/openstack_smoke_test.py
We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](http://www.spinnaker.io/docs/contributing-to-spinnaker).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a …
> added OpenStack smoke test

- .gitignore
We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](http://www.spinnaker.io/docs/contributing-to-spinnaker).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a …
> Tell git to ignore .vscode directory that Visual Studio Code creates

- etc/default/spinnaker
> fix(google): Handle domain names in project names.

- dev/dev_runner.py
- dev/refresh_source.py
> fix(dev): start/stop deck

- testing/citest/spinnaker_testing/aws_scenario_support.py
- testing/citest/spinnaker_testing/scrape_spring_config.py
- testing/citest/spinnaker_testing/spinnaker.py
- testing/citest/tests/aws_smoke_test.py
> Aws smoke test

- dev/hal_install_spin.docker
- dev/hal_k8s_run.sh
> feat(halyard_k8s_pod): Use halyard to configure jenkins for bake and

- dev/bootstrap_dev.sh
- dev/dev_runner.py
- pylib/spinnaker/change_cassandra.py
* install kubectl
* change_cassandra disables $HOME/.spinnaker/spinnaker-local.yml if present
* populate default spinnaker-local.yml with:
- disable cassandra
- configure front50 storage bucket
@duftler
> fix(dev): Fixes to setting up google development environment

- dev/bootstrap_dev.sh
@duftler 
last pr was merged prematurely. Here's the remaining fix.
Note that I remove the old gcloud. That's something new.
I can take that out, but it gets rid of some warnings and possible error later.
> fix(dev): Install kubectl with bootstrap_dev.sh

- dev/refresh_source.py
@duftler or @ewiseblatt please review.
> fix(dev): fixes deck dev startup

- dev/build_google_image.sh
> fix(dev): build google tarball from existing image

- dev/build_google_image.sh
> fix(dev): Recreate disks through instances, not directly from images

- dev/publish_test_results.py
@ttomsu Can you check that the post format is correct (front matter, etc)? I'll expand this in the future to push and update the changelog from the previous release tag.
> feat(nightly): Publish nightly test results to spinnaker.github.io.

- dev/build_google_image.sh
Removed optimizations to simplify script.
Dont pre-warm cleaner job or support a disk-based API.
@lwander
> chore(dev): Simplify build_googe_image.sh

- testing/citest/spinnaker_testing/aws_scenario_support.py
- testing/citest/tests/aws_kato_test.py
- testing/citest/tests/aws_smoke_test.py
@jtk54 
This depends on both the citest PRs I sent you
> chore(testing): Migrated aws tests from AwsCliAgent to AwsPythonAgent

- dev/build_google_image.sh
- dev/clean_google_image.sh
- dev/extract_disk_to_gcs.sh
@skim1420 
The real fix here is in the dd call.
> fix(dev): Fixed image extraction to tar.gz

- config/spinnaker.yml
> fix(config): Add chaos.enabled to spinnaker.yml

- testing/citest/README.md
- testing/citest/spinnaker_testing/azure_scenario_support.py
- testing/citest/spinnaker_testing/spinnaker_test_scenario.py
- testing/citest/tests/azure_smoke_test.py
Initial commit of azure support and test cases for app and security group.  Pull request https://github.com/google/citest/pull/257 is required for this to work properly.
@EricJizbaMSFT PTAL @ewiseblatt PTAL
> initial commit - Azure test (app/security group)

- dev/build_google_image_functions.sh
> chore(google): allow reuse of a bash support module.

- dev/build_google_image_functions.sh
> fix(google): Fixed typo in previous commit

- InstallSpinnaker.sh
- dev/build_google_image.sh
- dev/build_google_image_functions.sh
- dev/clean_google_image.sh
- google/codelab/provision_spinnaker_codelab_image.sh
- pylib/spinnaker/codelab_config.py
This consolidates the scripts a little and turns cassandra off
in the codelab image.
It also changes the jenkins port in the codelab from 9090 to 5656
so that 9090 can be available for prometheus.
@jtk54
> chore(google): changed scripts building google image and codelab.

- google/codelab/provision_spinnaker_codelab_image.sh
- pylib/spinnaker/codelab_config.py
> chore(google): Update codelab config

- config/default-spinnaker-local.yml
> config(provider/openstack): Added extra settings and some documentation

- google/codelab/provision_spinnaker_codelab_image.sh
> fix(google): Install codelab boot scripts.

- dev/publish_halyard.py
@jtk54 or @lwander please review.
> feat(halyard_release): publish halyard docs when releasing halyard

- dev/publish_halyard.py
> feat(halyard_release): push directly to docs repo

- dev/publish_halyard.py
Reverts spinnaker/spinnaker#1629
> Revert "feat(halyard_release): push directly to docs repo"

- dev/publish_halyard.py
Reverts spinnaker/spinnaker#1633
> Revert "Revert "feat(halyard_release): push directly to docs repo""

- dev/all_tests.yaml
- dev/validate_bom.sh
- dev/validate_bom__config.py
- dev/validate_bom__deploy.py
- dev/validate_bom__main.py
- dev/validate_bom__test.py
- pylib/spinnaker/run.py
Initial version only supports localdebian install on Google.
However the framework and process are set up to accomodate other
deployment types and platforms.
@lwander
> feat(testing): Script for deploying and validating a bom.

- dev/publish_api_docs.py
@jtk54 or @lwander please review.
> feat(docs): publish api docs

- config/settings.js
- experimental/kubernetes/ha/deck/config/settings.js
- experimental/kubernetes/simple/config/settings.js
> feat(gce): adds `associate public ip` flag to settings.js

- dev/generate_bom.py
@jtk54 what's the best way for me to run/validate this?
> feat(profiles): Publish a tar.gz for profile directories

- dev/validate_bom__config.py
- dev/validate_bom__deploy.py
- dev/validate_bom__main.py
- dev/validate_bom__test.py
Also fixes to configure jenkins to run bake_and_deploy_test.
@lwander
> feat(testing): collect logs after validating boms.

- dev/validate_bom__deploy.py
- dev/validate_bom__main.py
Also adds service account support where gcloud usage remains
@jtk54
> Use raw scp/ssh instaed of gcloud

- dev/all_tests.yaml
- dev/validate_bom__config.py
> feat(azure): Run azure interoperability tests during validation

- dev/validate_bom__deploy.py
- dev/validate_bom__test.py
> chore(validate): Cleanup error handling and reporting.

- dev/validate_bom__test.py
> fix(validate): handle overriden test paths.

- dev/all_tests.yaml
- dev/validate_bom__config.py
- dev/validate_bom__deploy.py
- dev/validate_bom__main.py
@lwander 
This is two PRs in one refactoring to generalize, then adding azure.
> Refactor validate and add azure

- dev/validate_bom__test.py
> feat(validate): add --test_stack

- dev/all_tests.yaml
- dev/validate_bom__config.py
@danielpeach 
This isnt complete. It configures the account but does not pass the right arguments into the test.
I dont understand how to run it. Please advise.
> feat(validate): Run appengine integration tests.

- dev/all_tests.yaml
- dev/validate_bom__test.py
> fix(validate): Handle no-argument flags

- dev/validate_bom__config.py
- dev/validate_bom__deploy.py
Also refactored some cleanup:
* force chmod 400 of uploaded files since they are typically sensitive
* added hook for determining internal ip
@lwander
> fix(validate): pass through hal_user when ssh/scp

- dev/validate_bom__config.py
- dev/validate_bom__deploy.py
@lwander 
Currently validate_bom contains some workarounds for missing aws support in halyard so it isnt honest validating the configuration process. However it lets us validate the spinnaker runtime on aws while we are waiting on halyard support to be completed.
This does not work around not being able to configure aws accounts, so EC2 deployments cannot actually manage EC2. However, they can use S3 and manage other cloud providers from the EC2 hosted spinnaker.
Note that the workaround seems to require I put an .aws/credentials file in all three different locations for one reason or another.
> feat(validate): Deploy to EC2

- dev/validate_bom__config.py
@lwander 
I'm hacking in apt-get install python-dev as a dependency; I thought you added this earlier in the week but am not seeing it.
I'd like to have a way of setting --client_host (in the prometheus install) to expose the daemon to the network to be polled by a remote prometheus.
> feat(validation): Monitor validation

- dev/all_tests.yaml
- dev/validate_bom__main.py
- dev/validate_bom__test.py
> fix(validate): Fixed front50 test

- testing/citest/spinnaker_testing/spinnaker.py
- testing/citest/spinnaker_testing/spinnaker_test_scenario.py
> Config network protocol used

- install/first_google_boot.sh
> fix(install): Pin redis version on first boot

- dev/build_release.py
> fix(build): Include all subsystems in index.

- dev/validate_bom__config.py
- dev/validate_bom__deploy.py
- dev/validate_bom__test.py
> feat(validate): validate halyard aws.

- dev/validate_bom__config.py
- dev/validate_bom__deploy.py
> fix(validate): Fix validating aws deployments

- dev/validate_bom__deploy.py
> feat(validate): Added --halyard_version

- dev/all_tests.yaml
- dev/validate_bom__config.py
- dev/validate_bom__deploy.py
- dev/validate_bom__main.py
- dev/validate_bom__test.py
- testing/citest/tests/kube_smoke_test.py
This is a rollup of a bunch of individual changes to increase validation
flexibility and simplify some of the logging/reporting.
@jtk54
> chore(validate): various validation cleanup and refactoring

- dev/validate_bom__deploy.py
> fix(validate): Install halyard with --user

- dev/validate_bom__deploy.py
> fix(validate): Fixed hal user from previous commit.

- dev/validate_bom__deploy.py
> fix(validate): sudo hal deploy apply

- testing/citest/tests/appengine_smoke_test.py
> fix(validate): Fixed server group check in appengine_smoke_test.

- dev/validate_bom__config.py
- dev/validate_bom__deploy.py
- testing/citest/spinnaker_testing/aws_scenario_support.py
- testing/citest/tests/aws_smoke_test.py
- testing/citest/tests/google_kato_test.py
- testing/citest/tests/google_server_group_test.py
This still doesnt work in general for aws, though
it does work with my paritcular setup. My intent
here was to be able to easily change the region,
but I still cannot do that. I think this is still
an improvement overall, though doesnt go as far as
I wanted.
@jtk54
> fix(validate): fixed location assumptions in tests.

- dev/annotate_source.py
- dev/build_release.py
- dev/generate_bom.py
We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to …
> feat(build): Build and push rpms

- dev/validate_bom__deploy.py
> fix(validate): retry aws to accommodate eventual consistency

- dev/generate_bom.py
Fixed initializing the `self.__halyard_version` added for RPM support. Small refactor that lets us resume running our release process.
> fix(generate_bom): Fix up Halyard version entry initialization.

- InstallSpinnaker.sh
fix confused comment as ubuntu 14.xx.x is only supported at this moment
> make it clear only Ubuntu 14.xx.x is supported now

- dev/validate_bom__config.py
- dev/validate_bom__deploy.py
- dev/validate_bom__test.py
- testing/citest/spinnaker_testing/scrape_spring_config.py
- testing/citest/spinnaker_testing/spinnaker.py
- testing/citest/tests/google_kato_test.py
- testing/citest/tests/kube_smoke_test.py
* Add KeepAlive probe to appease kubectl port forwarding
* Determine Azure IP address
* Retry resolvedEnv scrape
* Comment out Front50 None attributes to make S3 test happy.
* Split kube namespaces and only use the first
@jtk54
> fix(validate): Various validation fixes and enhancements

- dev/validate_bom__deploy.py
@jtk54 
Sorry, I thought I sent this out Monday night.
> feat(validate): Added deploy_google_network and tags options.

- dev/build_google_image_functions.sh
- dev/build_halyard_image.sh
- dev/image_name_from_family_and_version.sh
The additional image_name_from_family_and_version file will be consumed in jenkins to name our images
> feat(c2d): Image family support

- google/dev/publish_gce_release.sh
> fix(c2d): local scoped to functions only

- install/first_halyard_boot.sh
> feat(launcher): enables necessary apis on halyard boot

- dev/all_tests.yaml
- dev/validate_bom__config.py
- dev/validate_bom__deploy.py
- dev/validate_bom__test.py
Added/fixed monitoring into validation
Removed some logging chatter
@jtk54
> chore(validate): more monitoring, less logging

- dev/all_tests.yaml
- dev/validate_bom__test.py
- testing/citest/tests/appengine_smoke_test.py
- testing/citest/tests/google_front50_test.py
- testing/citest/tests/google_http_lb_upsert_scenario.py
- testing/citest/tests/google_kato_test.py
- testing/citest/tests/google_server_group_test.py
- testing/citest/tests/google_smoke_test.py
@jtk54 
There's some extra reformatting in appengine test
but mostly this complements the PR to citest converting the google tests over to the new verifier API
> Google tests

- testing/citest/tests/bake_and_deploy_test.py
- testing/citest/tests/google_http_lb_upsert_server_test.py
- testing/citest/tests/google_server_group_test.py
- testing/citest/tests/google_smoke_test.py
> chore(validate): Poll less frequently on long operations

- testing/citest/tests/aws_kato_test.py
- testing/citest/tests/aws_smoke_test.py
> chore(validate): Migrate aws tests to new observer predicate API

- dev/all_tests.yaml
- dev/validate_bom__test.py
- testing/citest/tests/appengine_smoke_test.py
- testing/citest/tests/google_server_group_test.py
> fix(validate): Fixed syntax error

- dev/generate_bom.py
> fix(generate_bom): Replace removed config_file.

- testing/citest/tests/azure_smoke_test.py
> chore(validate): Migrated azure test to new ObservationPredicate API

- dev/validate_bom__test.py
- testing/citest/tests/google_kato_test.py
@jtk54 
Two separate changes, one pr
> Log onexit

- dev/build_prevalidation.py
- dev/build_release.py
- dev/generate_bom.py
- dev/requirements.txt
- pylib/spinnaker/run.py
Adds GCB triggered builds. Won't be back until Monday, but drop me some comments/concerns and I'll fix 'em up next week and then we can turn this stuff on for our builds.
> feat(build_release): Add GCB container builds via triggers.

- dev/build_release.py
This is a small fix to syntax issues that crept in in https://github.com/spinnaker/spinnaker/pull/1830, as well as a refinement in how we report build failures at the top level. This way should be much more explicit and informational.
> fix(build_release): Report build errors explicitly.

- dev/build_prevalidation.py
- dev/generate_bom.py
I forgot I had a staged change for testing on the jenkins dev vm - running this fix there now
> fix(release): Tag halyard once

- dev/validate_bom__deploy.py
- dev/validate_bom__test.py
- pylib/spinnaker/run.py
FYI @ewiseblatt didn't make any changes -- seems like a reasonable workaround to me.
> fix(dev): Separate stderr and stdout in run_quick

- dev/publish_halyard.py
I modified the interface for running background processes in `build_release` and didn't change it in `publish_halyard`.
> fix(publish_halyard): Remove BackgroundProcess references.

- install/first_halyard_boot.sh
> fix(halyard-boot): Enable cloud resource manager API

- dev/validate_bom__config.py
- dev/validate_bom__deploy.py
- dev/validate_bom__main.py
> chore(validate): Preinstall monitoring

- testing/citest/tests/appengine_smoke_test.py
> docs(tests/appengine): prerequisites for running app engine smoke test

- packer/aws_ubuntu.json
- packer/aws_ubuntu_release.json
@see https://github.com/hashicorp/packer/issues/2069
@see https://www.packer.io/docs/provisioners/shell.html#inline_shebang
> fix(packer): Set -x in shebang for inline scripts

- dev/refresh_source.py
@jtk54 
This is clumsy but lets you refresh_source using a branch without requiring the branch to exist in all the repos. The point of this is to be able to use your script to build a Bom to feed the test automation over a change in a microservice. The default behavior is as before (requires the branch to be uniform) however if you --allow_master then a branch failure will fallback on master to distinguish between the repository not existing (still required) vs the branch not being present.
> chore(dev): Accomodate mixed-branch checkouts

- dev/build_release.py
> fix(build): skip orca junit tests

- dev/build_release.py
Removes all references to unused `nebula` & `nonebula` flags, as well as removes code to publish install script (which isn't referenced/validated against these releases anyhow).
This is done to make xenial support a bit easier in a coming PR.
> refactor(release): Remove unused nebula code

- dev/validate_bom__config.py
> feat(validate): added google cloud logging to validation instances

- dev/refresh_source.py
- testing/citest/spinnaker_testing/scrape_spring_config.py
> fix(validate): Tolerate 404 when checking resovledEnv in citests.

- testing/citest/tests/appengine_smoke_test.py
> chore(validate): Test appengine storage account.

- testing/citest/tests/aws_smoke_test.py
> fix(validate): Accomodate change in AWS response when validating.

- dev/validate_bom__config.py
- testing/citest/spinnaker_testing/gate.py
- testing/citest/tests/aws_smoke_test.py
- testing/citest/tests/google_server_group_test.py
> Patch release testing

- testing/citest/tests/google_http_lb_upsert_scenario.py
- testing/citest/tests/google_http_lb_upsert_test.py
Updates tests for L7 UHC update. Tested all locally.
> fix(google/lbs): Update tests for L7 upsert update.

- testing/citest/spinnaker_testing/gate.py
> fix(bake&deploy): s/and/or

- testing/citest/spinnaker_testing/jenkins_agent.py
- testing/citest/spinnaker_testing/spinnaker.py
- testing/citest/tests/bake_and_deploy_test.py
> chore(testing): Dont use deprecated optional citest trace parameters.

- testing/citest/citest_contrib/dcos_testing/dcos_contract.py
- testing/citest/citest_contrib/dcos_testing/dcoscli_agent.py
- testing/citest/spinnaker_testing/jenkins_agent.py
- testing/citest/spinnaker_testing/spinnaker.py
- testing/citest/tests/bake_and_deploy_test.py
@duftler 
These changes will be needed to test any future maintainence release on this branch.
> Patch release 1.4.x

- testing/citest/citest_contrib/dcos_testing/dcos_contract.py
- testing/citest/citest_contrib/dcos_testing/dcoscli_agent.py
- testing/citest/spinnaker_testing/jenkins_agent.py
- testing/citest/spinnaker_testing/spinnaker.py
- testing/citest/tests/bake_and_deploy_test.py
@duftler 
These will be needed to test any future 1.5.x maintainence releases.
> Patch release 1.5.x

- dev/build_release.py
This change adds xenial builds for all of our services. 
Once this direction is confirmed, I will put together changes in each repository adding a service configuration for systemd, similar to https://github.com/spinnaker/clouddriver/pull/2182.
> Xenial builds

- testing/citest/spinnaker_testing/azure_scenario_support.py
> fix(testing): Fixed az agent constructor call.

- dev/refresh_source.py
- pylib/spinnaker/run.py
> feat(build): refresh source from bom

- dev/buildtool/command.py
- unittest/buildtool/command_test.py
- unittest/buildtool/custom_test_command.py
@jtk54, @brandonnelson3 
This is the mechanism for adding process steps into the tool.
> feat(buildtool): Added command processor

- dev/buildtool/__main__.py
- unittest/buildtool/main_test.py
@jtk54 @brandonnelson3 
The last bit of scaffolding.
> feat(buildtool): Main program skeleton

- dev/buildtool/__main__.py
- dev/buildtool/source_commands.py
> feat(buildtool): Added fetch_source command.

- dev/buildtool/git.py
- unittest/buildtool/git_test.py
> fix(buildtool): detect variants of the same github repository url

- dev/buildtool/command.py
- dev/buildtool/util.py
> chore(buildtool): Asynchronous subprocesses and more logging.

- dev/buildtool/__main__.py
- dev/buildtool/build_commands.py
- dev/buildtool/command.py
- dev/validate_bom__deploy.py
@jtk54 @brandonnelson3 
This PR is where it gets interesting.
This is just build, not publish/release.
I was able to deploy and validate the boms created by this (bom creation is a future PR) last weekend on VMs. I think I hit an issue on containers that was halyard related and submitted changes there but havent retried yet because I need the reviews to catch up so I dont risk an accident. The GCB containers build without complaint, but I havent deployed them.
The halyard build is sketchy to me because of the release scripts it is using under its control so isnt as clear. I've made some modifications there to be able to inject some control over it but I still am not sure of the different variations and how I can confirm them. Also, the build jars step which also seems to publish some …
> feat(buildtool): Added build_* commands

- dev/buildtool/__main__.py
- dev/buildtool/bom_commands.py
> feat(buildtool): Added BOM commands

- dev/buildtool/__main__.py
- dev/buildtool/changelog_commands.py
- dev/buildtool/source_code_manager.py
> feat(buildtool): Added changelog commands.

- dev/buildtool/__main__.py
- dev/buildtool/apidocs_commands.py
- dev/buildtool/command.py
- dev/buildtool/util.py
> feat(buildtool): Added ApiDocs commands.

- dev/buildtool.sh
- dev/buildtool/flow_generate.sh
- dev/buildtool/ga-defaults.yml
- dev/buildtool/support_functions.sh
@jtk54,
@brandonnelson3 
I'm probably going to send these out as individual reviews for easier feedback/discussion/focus.
However this is a preview of where it is going and how it all comes together.
I have not done the publish_ scripts for release yet, however this is capable of supporting the pre-release build and validation. I've verified this on VMs but not yet on containers (though can build the containers).
> Buildtool.scripts

- dev/buildtool/__main__.py
- dev/buildtool/command.py
- dev/buildtool/git.py
- dev/buildtool/source_commands.py
- unittest/buildtool/command_test.py
- unittest/buildtool/git_test.py
- unittest/buildtool/source_code_manager_test.py
This also refactors GitRunner to accomodate authentication
and to consolidate standard commandline parameters for various
use cases involving git.
@jtk54 @brandonnelson3
> feat(buildtool): Base command for initiating pull requests

- dev/buildtool/apidocs_commands.py
- dev/buildtool/changelog_commands.py
This does not publish the changelog as a gist as before, though does
force it through a PR now. I'm not sure about the gists being useful,
though either way it does seem that the authoritative source of spinnaker
info should be managed in a spinnaker repository, not an external one.
We can talk more about this after the holiday. I can add it in if we
want to continue that route.
This also refactors the changelog generation to get rid of the details
(by default) and to group changes by component so it is more concise
and easier to read.
The apidocs are written as before, not with the versioning changes I
proposed earlier. I'll make those changes later as well.
@jtk54 @brandonnelson3
> feat(buildtool): Added publish commands for changelog and apidocs

- dev/build_google_component_image.sh
- dev/buildtool/__main__.py
- dev/buildtool/bom_commands.py
- dev/buildtool/build_commands.py
- dev/buildtool/ga-defaults.yml
- dev/buildtool/image_commands.py
- dev/buildtool/util.py
- dev/halyard_install_component.sh
This command uses the old bash scripts for the actual work.
However it modifies thos scripts to remove some built in assumptions
that we are using published artifacts.
@jtk54 @brandonnelson3
> feat(buildtool): Build GCE component images.

- dev/build_release.py
> fix(build_release): remove html gen tests flag for orca

- dev/build_release.py
Reverts spinnaker/spinnaker#2228
> Revert "fix(build_release): remove html gen tests flag for orca"

- dev/halyard_install_component.sh
- dev/validate_bom__deploy.py
> feat(dev): control halyard configuration when building images.

- dev/build_google_component_image.sh
- dev/buildtool/image_commands.py
> fix(buildtool): Fixed image generation against test repos.

- dev/buildtool/bom_commands.py
- dev/buildtool/bom_scm.py
- dev/buildtool/container_commands.py
- dev/buildtool/debian_commands.py
- dev/buildtool/flow_build.sh
- dev/buildtool/gradle_support.py
- dev/buildtool/halyard_commands.py
- dev/buildtool/image_commands.py
- dev/buildtool/repository_command.py
- dev/buildtool/rpm_commands.py
- dev/buildtool/support_functions.sh
- unittest/buildtool/bom_command_test.py
@jtk54 
There are three optimizations here.
First is a change to build_bom that, when refreshing an existing bom,
will only refresh the bom if the repository commits have changed.
This makes it transparent to maintain a bom in conjunction with the git
repos (the primitive command requires you explicitly set a parameter to
do this, however the flow script sets the parameter by default unless you
tell it not to, such as for a new branch).
Second, given that boms are easily maintained with source changes, the
"flow_build" script starts a build using the bom from the previous build.
This also adds an interim local bom for "unbuilt" artifacts so that failed
builds can continue where they left off. The next build will still pick up
on any repository changes (e.g. a fix to the build failure). …
> chore(buildtool): Be efficient at doing nothing

- dev/buildtool/inspection_commands.py
> fix(buildtool): prune old transient boms, not just invalid ones.

- dev/buildtool/__init__.py
- dev/buildtool/branch_scm.py
> feat(kayenta): Added kayenta to build

- dev/buildtool/__init__.py
- dev/buildtool/hal_support.py
- dev/buildtool/halyard_commands.py
- dev/buildtool/repository_command.py
- unittest/buildtool/bom_command_test.py
- unittest/buildtool/bom_repository_command_test.py
- unittest/buildtool/repository_command_test.py
Also added exclude repository mechanism to bypass temporarily problematic
repos.
@jtk54
> fix(buildtool): Fixed halyard build

- dev/buildtool/halyard_commands.py
> fix(buildtoo): fixed build_halyard typo

- dev/build_google_component_image.sh
- dev/buildtool/__init__.py
- dev/buildtool/__main__.py
- dev/buildtool/errors.py
- dev/buildtool/inmemory_metrics.py
- dev/buildtool/subprocess_support.py
- dev/validate-config-template.yml
- dev/validate_bom__config.py
- dev/validate_bom__deploy.py
- dev/validate_bom__main.py
- dev/validate_bom__test.py
- testing/citest/requirements.txt
- unittest/buildtool/bom_command_test.py
Replaced all the config parameters with the default_args_file
Added basic metric instrumentation around:
deploy/undeploy execution
test scheduling and execution
this is only in the validation controller script, not the individual test fixtures.
@jtk54
> chore(validate): Utilize buildtool libraries in validator.

- dev/validate_bom__deploy.py
- dev/validate_bom__main.py
- dev/validate_bom__test.py
> fix(validation): Fixed return when doing no work

- testing/citest/spinnaker_testing/gcs_pubsub_trigger_agent.py
- testing/citest/spinnaker_testing/jenkins_agent.py
- testing/citest/spinnaker_testing/spinnaker.py
> chore(testing): Removed deprecated "trace" parameters from interfaces.

- dev/buildtool/bom_commands.py
> fix(buildtool): tolerate no halconfig for kayenta

- dev/validate_bom__deploy.py
> fix(validate): Fixed error collecting log files during validation.

- dev/buildtool/branch_scm.py
> chore(buildtool): Moved kayenta repository

- dev/buildtool/bom_commands.py
> fix(buildtool): dont strip extension of bom alias

- dev/all_tests.yaml
- dev/requirements.txt
- dev/validate_bom__config.py
- dev/validate_bom__main.py
- pylib/spinnaker/validate_configuration.py
- testing/citest/spinnaker_testing/gcs_pubsub_trigger_agent.py
- testing/citest/tests/gcs_pubsub_gae_test.py
Also some small changes to the test and agent, nothing that changes behavior drastically.
> chore(citest/pubsub): Add validation configurators for pub/sub test.

- dev/buildtool/__init__.py
- dev/buildtool/base_metrics.py
- dev/buildtool/errors.py
- dev/validate_bom__deploy.py
> fix(validate): Tolerate some bintray unreliability.

- dev/buildtool/base_metrics.py
- dev/buildtool/bom_commands.py
- dev/buildtool/bom_scm.py
- dev/buildtool/changelog_commands.py
- dev/buildtool/config-template.yml
- dev/buildtool/container_commands.py
- dev/buildtool/debian_commands.py
- dev/buildtool/flow_build.sh
- dev/buildtool/git_support.py
- dev/buildtool/gradle_support.py
- dev/buildtool/halyard_commands.py
- dev/buildtool/image_commands.py
- dev/buildtool/inspection_commands.py
- dev/buildtool/repository_command.py
- dev/buildtool/rpm_commands.py
- dev/buildtool/spinnaker_commands.py
- dev/buildtool/support_functions.sh
- unittest/buildtool/bom_command_test.py
@lwander buildtool cherrypicks for release support
> Cherrypick gist

- dev/buildtool/bom_scm.py
@lwander 
Please patch this into 1.6.x too
> fix(buildtool): Skip null service entries in Bm

- dev/buildtool/spinnaker_commands.py
> fix(buildtool): Handle only_repositories in publish_spinnaker

- dev/validate-config-template.yml
- dev/validate_bom__deploy.py
- dev/validate_bom__test.py
> chore(buildtool): Added additional validatino parameters

- dev/buildtool/bom_commands.py
- dev/buildtool/git_support.py
> feat(buildtool): Support git ssh

- dev/buildtool/spinnaker_commands.py
> fix(buildtool): supply branch for pushing changelog entry to github.io

- dev/buildtool/halyard_commands.py
- dev/buildtool/spinnaker_commands.py
- dev/validate-config-template.yml
- dev/validate_bom__deploy.py
- dev/validate_bom__test.py
> More cherry picks

- dev/buildtool/git_support.py
- dev/buildtool/spinnaker_commands.py
- unittest/buildtool/git_support_test.py
> fix(buildtool): Dont tag unchaged repos

- dev/buildtool/halyard_commands.py
> fix(buildtool): moved halyard_version_check

- dev/build_google_component_image.sh
> chore(build): Build component images for kayenta

- dev/buildtool/git_support.py
- dev/validate_bom__test.py
- unittest/buildtool/git_support_test.py
> Fix version numbering

- dev/buildtool/spinnaker_commands.py
> fix(build): Get tag version from bom

- dev/buildtool/changelog_commands.py
- dev/buildtool/spinnaker_commands.py
> fix(buildtool): Publish release bom to halyard

- dev/buildtool/apidocs_commands.py
- dev/buildtool/changelog_commands.py
- dev/buildtool/git_support.py
> fix(buildtool): Git branch pushes tolerates command retries

- dev/buildtool/halyard_commands.py
@lwander 
Lars, make sure this is publishing halyard the way you expect
@jtk54 
This depends on the earlier git PR
> chore(buildtool): publish halyard releases

- dev/buildtool/bom_commands.py
- dev/validate-config-template.yml
- dev/validate_bom__config.py
@duftler 
First pass is only deploying on GCE for google with stackdriver.
> chore(validate): Deploy kayenta

- dev/buildtool/bom_commands.py
- dev/buildtool/image_commands.py
> fix(buildtool): Use image project from BOM

- dev/validate_bom__deploy.py
Halyard no longer uses upstart.
@lwander 
I dont like any of this PR from an API perspective.
I think hal should have startup/shutdown commands for the server.
But the critical omission is being able to supply credentials in the config file.
That should be there along with a complement to the --config-bucket parameter that I'm using to change the bucket. If you can change the bucket then it stands to reason you might need to change [provide] credentials so the two should be managed together. If I could set the credentials to begin with, then I wouldnt need to stop and start the server again for this use case (nor would I need to hack to startup script to inject them as I am doing here).
This should work in the short term if it is easier to add the credential scopes. However if you can add …
> chore(validate): Modernized halyard validation restart

- dev/buildtool/bom_commands.py
- dev/buildtool/image_commands.py
- dev/buildtool/inspection_commands.py
- dev/validate_bom__deploy.py
cherry-picks of:
#2675
#2676
#2677
> Release 1.7.x cherry pick modernize hal validation changed bom use image project

- .github/ISSUE_TEMPLATE.md
> Typing is hard

- dev/buildtool/inspection_commands.py
@ezimanyi 
This is the change I suggested the other week to audit from a minimum bom version to accomodate obsolete version images being purged.
The change is complicated because the intermediate data model that the commands make is keyed by service version, not bom version. The audit later collects the bom versions by collecting all those referenced by the services.
Therefore this filters the map of published services from the low level leaves rather than top level nodes.
> feat(buildtool): Audit released boms after minimum version.

- spinbot/gh/__init__.py
- spinbot/gh/client.py
- spinbot/gh/conventions.py
- spinbot/gh/util.py
- spinbot/manifests/deploy.yml
- spinbot/policy/log_issue_policy.py
- spinbot/policy/policy_registry.py
- spinbot/policy/stale_issue_policy.py
This is very expensive (in API calls) to run, and probably should only
be run infrequently. Will update cron settings to reflect this later.
> feat(spinbot): adds 'stale issue policy'

- README.adoc
JustCorrected Cloud Providers hyperlink on README (no code changes), thanks
---
1. We prefer small, well tested pull requests.
2. Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).
3. When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](https://www.spinnaker.io/community/contributing/submitting/).
4. We are unlikely to accept pull …
> Corrected Cloud Providers hyperlink on README

- spinbot/event/args.py
- spinbot/event/command.py
- spinbot/event/issue_event.py
- spinbot/event/label_issue_comment_event_handler.py
- spinbot/gh/client.py
- spinbot/gh/util.py
- spinbot/manifests/deploy.yml
>  feat(spinbot): label issues when requested

- dev/all_tests.yaml
- testing/citest/tests/google_front50_test.py
> Update front50 test

- testing/citest/tests/kube_smoke_test.py
Use explicit error predicates on the failure observations rather than
the deprecated "ObserverVerifier".
@jtk54
> chore(validate): Refactor deprecated API from kube_smoke_test

- spinbot/gh/client.py
- spinbot/gh/util.py
- spinbot/manifests/deploy.yml
- spinbot/policy/executor.py
- spinbot/policy/log_repository_policy.py
> feat(spinbot): collect repo-level stats

- dev/validate_bom__deploy.py
> fix(validate): collect kayenta and monitoring logs

- codelabs/cicd-k8s-best-practice/app/manifests/demo/.helmignore
- codelabs/cicd-k8s-best-practice/app/manifests/demo/Chart.yaml
- codelabs/cicd-k8s-best-practice/app/manifests/demo/templates/_helpers.tpl
- codelabs/cicd-k8s-best-practice/app/manifests/demo/templates/configmap.yaml
- codelabs/cicd-k8s-best-practice/app/manifests/demo/templates/deployment.yaml
- codelabs/cicd-k8s-best-practice/app/manifests/demo/templates/service.yaml
- codelabs/cicd-k8s-best-practice/app/manifests/demo/values.yaml
- codelabs/cicd-k8s-best-practice/app/manifests/production/values.yaml
- codelabs/cicd-k8s-best-practice/app/manifests/staging/values.yaml
- codelabs/cicd-k8s-best-practice/app/scripts/build-image.sh
- codelabs/cicd-k8s-best-practice/app/scripts/update-chart.sh
- codelabs/cicd-k8s-best-practice/app/scripts/update-production-env.sh
- codelabs/cicd-k8s-best-practice/app/scripts/update-staging-env.sh
- codelabs/cicd-k8s-best-practice/app/src/Dockerfile
- codelabs/cicd-k8s-best-practice/app/src/content/index.html
- codelabs/cicd-k8s-best-practice/app/src/main.go
initial commit for "best practices" demo/presentation
> feat(codelabs): best practices initial commit

- codelabs/base/install/cleanup.sh
- codelabs/base/install/connect.sh
- codelabs/base/install/manifests.yml
- codelabs/base/install/properties
- codelabs/base/install/setup.sh
- codelabs/base/publish
Gets spinnaker in a state where it'll be easier for other codelabs to
automate setup
Will likely extend this into a canary codelab (fyi @duftler).
> feat(codelabs): base spinnaker setup for GCP codelabs

- testing/citest/README.md
Updated link for bake_and_deploy_test.py test script.
> docs(tests/Readme): updated link for bake_and_deploy_test.py test script

- testing/citest/tests/kube_v2_smoke_test.py
> test(kube_v2_smoke): Add tests for patching manifests.

- dev/all_tests.yaml
- testing/citest/tests/kube_v2_artifact_test.py
This is just the start, will test a few more flows in subsequent PRs
> test(provider/kubernetes): v2 artifact tests

- testing/citest/tests/google_front50_test.py
> fix(testing): Accomodate race condition in google frton50 test

- testing/citest/spinnaker_testing/jenkins_agent.py
- testing/citest/spinnaker_testing/spinnaker_test_scenario.py
- testing/citest/tests/bake_and_deploy_test.py
> fix(testing): Restructure BakeAndDeploy test reduces timeout flakiness.

- dev/buildtool/changelog_commands.py
- dev/buildtool/git_support.py
- unittest/buildtool/git_support_test.py
> feat(buildtool): Can produce changelog relative to bom

- codelabs/README.md
> doc(codelabs): explain publish process

- testing/citest/spinnaker_testing/gate.py
- testing/citest/spinnaker_testing/gcs_pubsub_trigger_agent.py
- testing/citest/spinnaker_testing/jenkins_agent.py
- testing/citest/spinnaker_testing/spinnaker.py
> chore(testing): added custom status summarization

- dev/all_tests.yaml
- dev/validate_bom__config.py
Tests passing on jenkins from this branch
> test(provider/kubernetes): enable artifact tests

- testing/citest/spinnaker_testing/gcs_pubsub_trigger_agent.py
> fix(testing): Fixed GcsPubsubTriggerOperationStatus snapshot

- testing/citest/spinnaker_testing/gcs_pubsub_trigger_agent.py
> fix(test): Fixed bug in gcs_pubsub_gae test.

- dev/all_tests.yaml
- testing/citest/tests/kube_v2_cache_test.py
contains commits for https://github.com/spinnaker/spinnaker/pull/3044 (will rebase once the other test changes are merged).
> test(provider/kubernetes): test manifest cache endpoint

- dev/all_tests.yaml
- testing/citest/tests/gcs_front50_test.py
This isn't testing the google provider, while all other `google_*` tests are.
> chore(tests): rename gcs front50 test for consistency

- dev/buildtool/halyard_commands.py
- dev/validate_bom__deploy.py
- dev/validate_bom__test.py
> Fix collect

- README.adoc
dont merge until https://github.com/spinnaker/spinnaker.github.io/pull/915 is in
> feat(readme): update the link to dev setup guide

- dev/buildtool/spin_commands.py
Instrument spin_build and capture command output
@jtk54
> feat(buildtool): Instrument spin_build

- dev/buildtool/__init__.py
- dev/buildtool/apidocs_commands.py
- dev/buildtool/base_metrics.py
- dev/buildtool/changelog_commands.py
- dev/buildtool/errors.py
- dev/buildtool/git_support.py
- dev/buildtool/gradle_support.py
- dev/buildtool/hal_support.py
- dev/buildtool/influxdb_metrics.py
- dev/buildtool/inspection_commands.py
- dev/buildtool/spinnaker_commands.py
- dev/buildtool/subprocess_support.py
> chore(buildtool) Port buildtool to python3

- dev/buildtool/bom_scm.py
- dev/buildtool/git_support.py
- dev/buildtool/subprocess_support.py
- dev/buildtool/util.py
- unittest/buildtool/bom_command_test.py
- unittest/buildtool/bom_repository_command_test.py
- unittest/buildtool/bom_scm_test.py
- unittest/buildtool/branch_scm_test.py
- unittest/buildtool/git_support_test.py
- unittest/buildtool/gradle_support_test.py
- unittest/buildtool/main_test.py
- unittest/buildtool/repository_command_test.py
- unittest/buildtool/spinnaker_commands_test.py
- unittest/buildtool/subprocess_test.py
- unittest/buildtool/util_test.py
> chore(buildtool): Python3 port

- dev/buildtool/changelog_commands.py
- dev/buildtool/subprocess_support.py
- dev/buildtool/util.py
Seems the encoding has changed to ascii with the upgrade to python3 on the system we're running on
> fix(build): fix stdout encoding with change to python 3

- dev/requirements.txt
- dev/validate_bom.sh
- dev/validate_bom__deploy.py
- dev/validate_bom__main.py
- dev/validate_bom__test.py
- testing/citest/citest_contrib/dcos_testing/__init__.py
- testing/citest/spinnaker_testing/__init__.py
- testing/citest/spinnaker_testing/expression_dict.py
- testing/citest/spinnaker_testing/gate.py
- testing/citest/spinnaker_testing/gcs_pubsub_trigger_agent.py
- testing/citest/spinnaker_testing/jenkins_agent.py
- testing/citest/spinnaker_testing/scrape_spring_config.py
- testing/citest/spinnaker_testing/spinnaker.py
- testing/citest/tests/gcs_front50_test.py
- testing/citest/tests/google_http_lb_upsert_test.py
- unittest/buildtool/git_support_test.py
> chore(validate): port to python3

- dev/buildtool/changelog_commands.py
Also changes title to major.minor only.
---
1. We prefer small, well tested pull requests.
2. Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).
3. When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](https://www.spinnaker.io/community/contributing/submitting/).
4. We are unlikely to accept pull requests that add features without prior …
> chore(build): Removes extraneous heading from generated changelog

- dev/bootstrap_dev.sh
- dev/create_google_dev_vm.py
- dev/create_google_dev_vm.sh
- dev/install_development.sh
@jtk54 
Removed deprecated dependencies and modernized
> fix(dev):  Fixed create_google_dev_vm script

- dev/buildtool/image_commands.py
> fix(build): more stdout encoding fixes

- dev/validate_bom__config.py
> feat(validate): push monitoring filters

- dev/buildtool/inspection_commands.py
Also fixed old versions affecting audit.
@jtk54
> fix(buildtool): Accomodate pre-release services in bom audit.

- testing/citest/spinnaker_testing/scrape_spring_config.py
> fix(validate): tolerate 401 scraping spring config

- spinbot/gh/__init__.py
- spinbot/gh/client.py
- spinbot/gh/util.py
- spinbot/manifests/deploy.yml
- spinbot/policy/executor.py
- spinbot/policy/log_pull_request_policy.py
So far we only captured pull request stats on merge, now we capture them
for all open pull requests as well
> feat(spinbot): more detailed pull stats

- dev/buildtool/subprocess_support.py
> fix(buildtool): Fixed unicode encoding in subprocess output.

- dev/buildtool/bom_scm.py
> fix(buildtool/spin): Remove spin from the BOM.

- dev/buildtool/flow_build.sh
- dev/buildtool/spin_commands.py
In the process of testing, don't merge yet. Still PTAL.
> feat(buildtool/spin) Adds spin publish command.

- spinbot/event/filetype_check_pull_request_handler.py
- spinbot/event/master_branch_pull_request_handler.py
- spinbot/manifests/deploy.yml
As discussed in https://github.com/spinnaker/clouddriver/pull/2838
> feat(spinbot): check for new groovy files

- dev/buildtool/spin_commands.py
Depends on: https://github.com/spinnaker/spin/pull/54/files.
> fix(buildtool/spin): Set spin CLI version in binary.

- spinbot/event/label_issue_comment_event_handler.py
- spinbot/gh/__init__.py
- spinbot/gh/util.py
- spinbot/policy/stale_issue_policy.py
@duftler please check the wording
> feat(spinbot): close stale issues after warning

- dev/buildtool/spin_commands.py
> fix(buildtool): Fixed index access.

- testing/citest/spinnaker_testing/google_scenario_support.py
- testing/citest/spinnaker_testing/spinnaker_test_scenario.py
@jtk54 
Not intended to be normal use case, just for occasional auditing purposes.
> feat(testing): audit gcp quota needed for tests.

- testing/citest/tests/appengine_smoke_test.py
> fix(validate): Bind appengine_ smok-ttest to TEST_GCE_REGION

- testing/citest/spinnaker_testing/google_scenario_support.py
> feat(testing): fixed fixture name emitted when collecting quota.

- dev/all_tests.yaml
- dev/validate_bom__config.py
- dev/validate_bom__test.py
- testing/citest/tests/bake_and_deploy_test.py
- testing/citest/tests/google_server_group_test.py
- testing/citest/tests/kube_v2_artifact_test.py
- testing/citest/tests/kube_v2_helm_test.py
- testing/citest/tests/kube_v2_smoke_test.py
Cherry-pick of #3152, #3163, #3171, #3172,  #3179, #3208
> fix(citest): Fix flaky tests in 1.9 branch

- dev/buildtool/__main__.py
- dev/buildtool/bom_commands.py
- dev/buildtool/bom_scm.py
- dev/buildtool/changelog_commands.py
- dev/buildtool/container_commands.py
- dev/buildtool/git_support.py
- dev/buildtool/hal_support.py
- dev/buildtool/halyard_commands.py
- dev/buildtool/inspection_commands.py
- dev/buildtool/scm.py
- dev/buildtool/spinnaker_commands.py
- dev/publish_halyard.py
- dev/validate_bom__main.py
- dev/validate_bom__test.py
- google/release/ha_image_janitor.py
- spinbot/config.py
- spinbot/storage/gcs_storage.py
- spinbot/storage/local_storage.py
- testing/citest/spinnaker_testing/yaml_accumulator.py
- unittest/buildtool/bom_command_test.py
- unittest/buildtool/bom_repository_command_test.py
- unittest/buildtool/git_support_test.py
- unittest/buildtool/main_test.py
- unittest/buildtool/test_util.py
@lwander 
I did not test spinbot, but ran a build and validate
> fix(python): Load yaml securely.

- dev/buildtool/halyard_commands.py
> fix(buildtool): Use desired commit when publishing halyard.

- dev/buildtool/container_commands.py
> fix(buildtool): Use Dockerfile.slim if present.

- dev/buildtool/branch_scm.py
- dev/buildtool/halyard_commands.py
- dev/buildtool/scm.py
- unittest/buildtool/branch_scm_test.py
> fix(buildtool): enforce pinned repo commits.

- testing/citest/spinnaker_testing/gate.py
> fix(validate): surface more status error details

- dev/validate_bom__deploy.py
> fix(validate): Collect monitoring logs.

- dev/all_tests.yaml
- dev/validate_bom__config.py
- dev/validate_bom__test.py
@stewchen 
cherry picks to be consistent with external validation scripts
> Cherry pick 1.8

- dev/buildtool/container_commands.py
Regression in https://github.com/spinnaker/spinnaker/pull/3261. @joonlim PTAL also.
> fix(build/containers): Exclude echo from slim docker builds.

- testing/citest/tests/appengine_smoke_test.py
This reverts commit f896f0f1a0dbe5353b0e078811d0f876b14d1640.
> fix(validate): Revert bind appengine_ smoke-test to TEST_GCE_REGION

- google/release/ha_image_janitor.py
> chore(janitor): fixed image cleanup.

- dev/validate_bom__config.py
Allows us to inspect the storage class etc of buckets we are creating for validation purposes.
> chore(buildtool/validate): Adds debug logging for bucket creation.

- dev/buildtool/git_support.py
- dev/buildtool/halyard_commands.py
> fix(buildtool): Respect github_push_ssh for halyard.

- dev/buildtool/flow_build.sh
> fix(buildtool): Build halyard from master by default.

- codelabs/gke-base/install/enable_apis.sh
- codelabs/gke-base/install/setup.sh
- codelabs/gke-kayenta-workshop/overrides/postdeploy.sh
- codelabs/gke-kayenta-workshop/overrides/properties
- codelabs/gke-kayenta-workshop/overrides/publish_samples.sh
- codelabs/gke-kayenta-workshop/publish
- codelabs/gke-kayenta-workshop/services/LICENSE.txt
- codelabs/gke-kayenta-workshop/services/README.md
- codelabs/gke-kayenta-workshop/services/backend/Dockerfile
- codelabs/gke-kayenta-workshop/services/backend/build.sh
- codelabs/gke-kayenta-workshop/services/backend/main.go
- codelabs/gke-kayenta-workshop/services/frontend/Dockerfile
- codelabs/gke-kayenta-workshop/services/frontend/build.sh
- codelabs/gke-kayenta-workshop/services/frontend/check.sh
- codelabs/gke-kayenta-workshop/services/frontend/content/index.html
- codelabs/gke-kayenta-workshop/services/frontend/get-ingress.sh
- codelabs/gke-kayenta-workshop/services/frontend/main.go
- codelabs/gke-kayenta-workshop/services/manifests/backend.yml
- codelabs/gke-kayenta-workshop/services/manifests/frontend.yml
- codelabs/gke-kayenta-workshop/services/manifests/seeding.yml
- codelabs/gke-kayenta-workshop/services/manifests/update-backend.sh
- codelabs/gke-kayenta-workshop/services/manifests/update-frontend.sh
Will resolve the duplication with gke-source-to-prod later. Have not customized the README either.
> feat(codelab/kayenta-workship): Add services and supporting artifacts.

- approvers.md
**From TOC**: Previously had approver access prior to governance; meets criteria.
> chore(*): Add @csanden to list of approvers

- spinbot/manifests/deploy.yml
This is an unpushed change that fixed the change in the monitoring endpoint & port
> fix(spinbot): update monitoring endpoint

- dev/buildtool/halyard_commands.py
> fix(build): Fixed halyard composite build.

- dev/validate_bom__test.py
@danielpeach 
I did not validate this yet so try before patching.
> fix(validate): Tolerate missing GCE quota metric tags.

- dev/buildtool/halyard_commands.py
> fix(devtool): Fix publish halyard with composite build.

- dev/validate_bom__deploy.py
> chore(validate): show payload when it wasnt valid json

- dev/validate_bom__deploy.py
> fix(validate): Fixed typo in last submit

- dev/validate_bom__config.py
> chore(validate): Pass metric filters to halyard to install.

- spinbot/manifests/deploy.yml
> fix(spinbot): reduce bot run frequency

- dev/validate_bom__config.py
> feat(validate): Added --halyard_profile_dir

- spinbot/gh/client.py
https://pygithub.readthedocs.io/en/latest/github_objects/RateLimit.html#github.RateLimit.RateLimit
> chore(spinbot): rate object is deprecated

- spinbot/event/executor.py
- spinbot/policy/executor.py
Makes it easier to co-locate logged errors with the ones we push to influx
> fix(spinbot): log error message that will tagged in monitoring

- dev/validate_bom__deploy.py
> fix(validate): Confirm AWS tags when looking for public ip

- dev/buildtool/__init__.py
- dev/buildtool/branch_scm.py
- dev/buildtool/scm.py
- dev/buildtool/spinnaker_commands.py
> fix(buildtool): Branch and tag spinnaker repository

- dev/buildtool/apidocs_commands.py
- dev/buildtool/subprocess_support.py
> fix(buildtool): Removed obsolete bootRun task reference

- testing/citest/tests/bake_and_deploy_test.py
> fix(validate): Temporarily disable disable stage for one test.

- dev/buildtool/spinnaker_commands.py
> fix(buildtool): Fixed tagging for branches in non-BOM repositories.

- dev/buildtool/spinnaker_commands.py
> fix(buildtool): publish spinnaker versions from non-bom repos.

- dev/buildtool/__init__.py
- dev/buildtool/source_commands.py
- dev/buildtool/spinnaker_commands.py
> fix(buildtool): Dont tag kork and spinnaker-dependencies afterall.

- dev/buildtool/spin_commands.py
> fix(buildtool/spin): Override GOPATH to preserve buildtool input/output

- dev/validate_bom__config.py
> chore(validate): update prometheus node_exporter to 0.17 for validation

- dev/buildtool/git_support.py
- unittest/buildtool/git_support_test.py
> fix(buildtool): Fixed changelog generation

- unittest/buildtool/bom_command_test.py
- unittest/buildtool/branch_scm_test.py
- unittest/buildtool/repository_command_test.py
> fix(buildtool): Fixed unit tests

- gradle/buildViaTravis.sh
> fix(travis): Dont trigger on OSS tags

- reviewers.md
Following latest TOC meeting, new reviewers.
FYI @ethanfrogers @imosquera @andrewbackes @dotdotdotpaul @kevinawoo @claymccoy
> chore(reviewers): Update reviewers list

- approvers.md
According to latest TOC meeting, promoting @claymccoy to approver role.
> chore(approvers): Adding claymccoy

- dev/buildtool/apidocs_commands.py
> chore(buildtool): Build apidocs statically or from server.

- dev/buildtool/errors.py
@ttomsu 
FYI your scenario was a 502 Bad Gateway.
> fix(buildtool): Process exceptions that have no message.

- testing/citest/spinnaker_testing/google_scenario_support.py
- testing/citest/tests/google_kato_test.py
> chore(testing): Modernized GCE image version references.

- dev/buildtool/spin_commands.py
Also fixes tag pushing on publish.
> fix(buildtool/spin): Set internal patch version properly.

- .github/ISSUE_TEMPLATE.md
> chore(github): Add note to issue template about @spinnaker/ui-ux-team.

- approvers.md
dpeach is not @danielpeach username. also, since daniel isn't working on this team anymore, do we want to continue to allow approvals?
> fix(approvers): update danielpeach  username

- dev/buildtool/spin_commands.py
> chore(buildtool): Log "go get" when building spin

- testing/citest/spinnaker_testing/gcs_pubsub_trigger_agent.py
@jtk54 
Seems to work, but I'm not exactly sure there arent other issues (possibly introduced).
Take a critical look.
A few changes here
First, rather than rebinding the operation midstream from the gcs pubsub agent
to the gate agent, construct the operation with both agents and use the pubsub
agent to handle the pubsub operations, but bind the gate agent to the operation.
This is because the gate agent is used to check the status, which is what the
bound agent is for.
The PubsubTriggerOperationStatus seemed to have too much state.
It mostly delegates to the __trigger_status instead. Its only real added
state is whether or not it timed out.
Clarify between the trigger status and the trigger response to avoid confusing
the two.
> fix(testing): Fixed gcs pubsub operation

- dev/buildtool/apidocs_commands.py
- dev/buildtool/base_metrics.py
- dev/buildtool/inspection_commands.py
- dev/buildtool/metrics.py
- dev/buildtool/spin_commands.py
- dev/buildtool/spinnaker_commands.py
- dev/buildtool/subprocess_support.py
- dev/buildtool/util.py
Also some lint warnings
@jtk54
> fix(buildtool): Fixed python3 compatability in subprocess support

- codelabs/gke-source-to-prod/install/setup.sh
Fix for https://github.com/spinnaker/spinnaker/issues/3840
> GCR token exchange error

- dev/buildtool/inspection_commands.py
> fix(buildtool): Prune spinnaker-monitoring artifacts.

- dev/buildtool/git_support.py
- unittest/buildtool/git_support_test.py
- unittest/buildtool/test_util.py
> chore(buildtool): Refactored sorting on semantic versions

- dev/buildtool/errors.py
- dev/buildtool/inspection_commands.py
- dev/buildtool/subprocess_support.py
- dev/buildtool/util.py
- testing/citest/tests/appengine_smoke_test.py
> fix(buildtool): More python3 fixes

- dev/buildtool/command.py
- dev/buildtool/subprocess_support.py
- dev/buildtool/util.py
- unittest/buildtool/subprocess_test.py
- unittest/buildtool/util_test.py
> fix(buildtool): Added unit test

- dev/requirements.txt
- testing/citest/requirements.txt
@jtk54 
I thought this would fix something which turned out to be a different cause.
But might as well update these anyway to current versions.
> chore(buildtool): Updated pypi dependencies

- dev/buildtool/inspection_commands.py
> fix(audit): Dont require jars for non-java repositories

- codelabs/gke-source-to-prod/install/properties
- codelabs/gke-source-to-prod/install/setup.sh
- codelabs/gke-source-to-prod/publish
It seems to be eventually consistent, so occasionally doesn't return the
account we just created.
> Don't use `gcloud iam service-accounts list`.

- solutions/kayenta/ci/scripts/first-deployment.sh
The behaviour of spin was changed by spinnaker/spin#152
> Fix Kayenta tutorial CI

- testing/citest/README.md
> docs(citest): fix some formatting I broke in the last commit

- dev/buildtool/debian_commands.py
- dev/buildtool/gradle_support.py
> fix(buildtool): Support spinnaker-gradle-plugins-6.0.0

- dev/buildtool/halyard_commands.py
Fixes regression in https://github.com/spinnaker/spinnaker/commit/50dde9eaaf8e9968304bd865f9592c956b870235. @plumpy PTAL also.
> fix(buildtool/halyard): Fixes versions for halyard commands.

- testing/citest/requirements.txt
> chore(buildtool): Remove openstack client from buildtool.

- dev/buildtool/git_support.py
- spinbot/event/release_branch_pull_request_handler.py
These should be considered in the same category as fix tasks
> fix(build): Don't increase minor version for perf tasks

- testing/citest/spinnaker_testing/azure_scenario_support.py
- testing/citest/tests/azure_bake_and_deploy_test.py
Enable Azure e2e automation testing for a P0 scenario.
> test(provider/azure):add basic test case

- solutions/kayenta/ci/scripts/first-deployment.sh
- solutions/kayenta/ci/scripts/setup.sh
spinnaker/spin#173 is why I rollback to spin 1.6.0
> Kayenta tutorial: Update Spinnaker to 1.13.8

- dev/buildtool/container_commands.py
Instead of generating a GCB configuration on-the-fly for each repository (with switches to handle special cases), just used the GCB configuration checked into each repo to do builds.
This PR also removes some unused parameters, greatly simplifying the logic:
* The ability to build via docker instead of GCB
* The ability to delete and existing image instead of skipping it
* The ability to set force_clean_gradle_cache to false
> feat(build): Use cloudbuild.yaml files from each repo

- testing/citest/requirements.txt
Seems to have fixed the error...
> fix(citest): add 'retrying' to the citest requirements

- sponnet/pipeline.libsonnet
> Add stage type runJobManifest

- sponnet/pipeline.libsonnet
fixed withManifestName - previous implementation drop whole json section
> fixed withManifestName - previous implementation drop whole json section

- sponnet/pipeline.libsonnet
New stage evaluateVariable added
> (added) sponnet - evaluateVariable stage

- sponnet/pipeline.libsonnet
'kind' parameter added to withManifestName
> (fix) sponnet - findArtifactsFromResource stage

- sponnet/application.libsonnet
- sponnet/pipeline.libsonnet
- sponnet/v2PipelineTemplate.libsonnet
- Automatic correction by jsonnet plugin for vim
- Add moniker to withClusterSize in checkPreconditions
- Fixed regions of withClusterSize in checkPreconditions
> fix(sponnet): Fix syntaxes and withClusterSize

- testing/citest/spinnaker_testing/gate.py
- testing/citest/tests/appengine_gcs_pubsub_test.py
- testing/citest/tests/appengine_smoke_test.py
- testing/citest/tests/aws_smoke_test.py
- testing/citest/tests/bake_and_deploy_test.py
- testing/citest/tests/google_server_group_test.py
- testing/citest/tests/google_smoke_test.py
- testing/citest/tests/kube_smoke_test.py
- testing/citest/tests/kube_v2_artifact_test.py
- testing/citest/tests/kube_v2_cache_test.py
- testing/citest/tests/kube_v2_gcs_test.py
- testing/citest/tests/kube_v2_helm_test.py
- testing/citest/tests/kube_v2_smoke_test.py
Proves changes made for https://github.com/spinnaker/spinnaker/issues/5168 actually work (which it does: ![2RrYNFctJbE](https://user-images.githubusercontent.com/13141550/69572018-4295a780-0f91-11ea-9762-f6c79816c5b6.png) )
> feat(stats): Include  field during citest application creation

- dev/buildtool/inspection_commands.py
Our current `Admin_AuditBoms` job generates a reverse index of artifacts (such as container images, debians and jars) back to their source BOMs. Coupled with `Admin_DeleteObsoleteArtifacts`, the two jobs generate a list of orphaned and deletable artifacts, and then deletes them.
This PR adds the generation of unused configs that have been collecting in the `halconfig` bucket since the beginning of the release process. These are effectively copies of all files in each service repo's `halconfig` directory ([example](https://github.com/spinnaker/gate/tree/master/halconfig)).
You can see the candidate list of files to be deleted by viewing the `prune_configs.txt` [here](https://builds.spinnaker.io/view/5%20Admin/job/Admin_AuditBoms/68/artifact/build_output/audit_artifact_versions/*config*) - …
> feat(auditing): Add config files to the auditing and pruning code

- dev/buildtool/bom_commands.py
> fix(log): fix a log message in the build tool

- .github/build-cop-template.md
Experimenting with GH Actions.
> chore(buildcop): Adds build-cop rotation template

- .github/build-cop-template.md
Merge after https://github.com/spinnaker/spinnaker.github.io/pull/1741 is submitted.
> chore(buildcop): Add troubleshooting playbook link to build cop template

- .github/workflows/build-cop-rotation.yml
Otherwise we'd have to wait 15 days to see if any changes actually worked.
> fix(build-cops): Execute build cop rotation GHA on change

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2020-06-14

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2020-06-30

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2020-07-14

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2020-07-31

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2020-08-14

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2020-08-30

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2020-09-13

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2020-09-30

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2020-10-14

- .github/build-cop/schedule.yaml
> chore(build-cop): swap mneterval@ and plumpy@ build rotations

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2020-10-31

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2020-11-14

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2020-11-30

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2020-12-14

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2020-12-31

- codelabs/gke-base/install/manifests.yml
- codelabs/gke-kayenta-workshop/front50/deploy-to-staging-pipeline.json
- codelabs/gke-kayenta-workshop/overrides/publish_samples.sh
- codelabs/gke-source-to-prod/front50/pipelines/f1d724be-7f75-43fc-b0f5-d7efa4b173af/specification.json
- codelabs/gke-source-to-prod/install/manifests.yml
- codelabs/gke-source-to-prod/install/setup.sh
- solutions/bluegreen/README.md
- solutions/bluegreen/manifests/replicaset-v1.yaml
- solutions/bluegreen/pipelines/pipeline.json
- solutions/kayenta/README.md
- solutions/kayenta/pipelines/automated-canary-1-10.json
- solutions/kayenta/pipelines/automated-canary-1-9.json
- solutions/kayenta/pipelines/canary-deploy.json
- solutions/kayenta/pipelines/simple-deploy.json
I made sure to copy all the demo images to the new 'codelabs'
repository.
> fix(codelabs): update all the codelabs to new Docker registries

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2021-01-14

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2021-01-30

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2021-02-13

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2021-03-02

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2021-03-14

- .github/build-cop/schedule.yaml
> Extend build cop schedule to 2021-04-02

- README.adoc
> docs(readme): Remove duplicate sentence.

- README.adoc
Rewrote the starting sentence for the question why do I need spinnaker?
> Rewrote the starting sentence.

- README.adoc
> Fix broken URLs in README

- README.adoc
- codelabs/cicd-k8s-best-practice/app/src/content/index.html
see Project status and updates section.
> style: bit misspell README

- deck/packages/core/src/navigation/UrlBuilder.ts
- echo/echo-core/src/main/java/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgent.java
- echo/echo-core/src/test/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgentSpec.groovy
- fiat/fiat-google-groups/src/main/java/com/netflix/spinnaker/fiat/roles/google/GoogleDirectoryUserRolesProvider.java
- fiat/fiat-google-groups/src/test/groovy/com/netflix/spinnaker/fiat/roles/google/GoogleDirectoryUserRolesProviderSpec.groovy
Action run: https://github.com/spinnaker/spinnaker/actions/runs/14912604526
Merge failed for `deck-kayenta` - run the following command, resolve conflicts, and push:
```zsh
./pull.sh deck-kayenta
git commit -a -F SUBTREE_MERGE_MSG
```
<details>
<summary>Output</summary>
```zsh
CONFLICT (modify/delete): deck-kayenta/.github/workflows/ci.yml deleted in HEAD and modified in deck-kayenta/master. Version deck-kayenta/master of deck-kayenta/.github/workflows/ci.yml left in tree.
Automatic merge failed; fix conflicts and then commit the result.
```
</details>
Successfully merged: clouddriver, deck, echo, fiat, front50, gate, halyard, igor, kayenta, keel, kork, orca, rosco, spin, spinnaker-gradle-project
> Auto-merge of individual repos (main)

- .github/workflows/spinnaker-release.yml
This should be backported to 2025.0.x as well
> fix(build): Publish debs on release

- .github/workflows/clouddriver-integration-tests-kubernetes.yml
- clouddriver/clouddriver-kubernetes/clouddriver-kubernetes.gradle
using both kubectl 1.30.13 and 1.22.17 (the default).
> test(clouddriver/kubernetes): test against a 1.30.13 k8s cluster

- clouddriver/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/AmazonNamedImageLookupController.groovy
- clouddriver/clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/AmazonNamedImageLookupControllerSpec.groovy
when AmazonNamedImageLookupController.list discards images.  That is, when a query would otherwise return more than the MAX_SEARCH_RESULTS threshold (currently 1000).
> feat(aws): add to a new counter metric named aws.discardedImages
