README.adoc
Let "users" know where to go to get started using Spinnaker.
=> Point non-devs to getting started user docs

InstallSpinnaker.sh, pylib/spinnaker/spinnaker_runner.py
using apt-mark within the InstallSpinnaker script to put a hold on cassandra and cassandra-tools to keep them at the required 2.1 version
=> change to put a "hold" on cassandra packages

dev/build_google_image.packer, dev/build_release.py
This also changes dev/build_release to publish all ubuntu distributions
and put the InstallSpinnaker.sh under scripts/ to mirrot the standard release.
And fixes the default repository url (which is typically injected anyway).
@duftler
=> Up GCE source image to trusty-v20151113

dev/create_google_dev_vm.py
@duftler 
Just a recap of the past few commits:
I used to explicitly set the mode of files after copying them over within create_dev_vm.
I took that out to simplify a bit since gcloud already preserves files. However, there is a temp file created within create_dev to transform the jsonPath used in the new instance. That temp file was not being protected. In this PR, I copy the original file modes for the temp file.
When all is said and done, this can still result in new failures due to the check of sensitive file permissions within run_dev. However, these are legit in the sense that they would only occur if the source machine files were not properly protected.
=> Preserve original credentials of spinnaker-local.yml when transforming it.

config/settings.js
`primaryAccounts` and `challengeDestructiveActions` should be coming from Clouddriver now (https://github.com/spinnaker/clouddriver/blob/master/clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/CredentialsController.groovy#L73), as should `preferredZones` (https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentials.java#L132)
`whatsNew` is a Netflix-only component, so should not need to be in settings.js.
@duftler or @ewiseblatt can you review/sanity-check this?
=> update settings.js, removing preferredZones config

config/gate.yml
This aligns with changes here:
https://github.com/spinnaker/gate/pull/159
Also is completely a noop since the edits are all in yml comments
Can't change the parent spinnaker.yml to remove oort/mort/kato until orca no
longer uses those config values
=> Remove references to oort/mort/kato in gate.yml

config/settings.js, experimental/packer/configure.sh, pylib/spinnaker/configurator.py, unittest/configurator_test.py
Safari and (possibly) Firefox throw exceptions on `let` statements in strict mode. This changeset attempts to get around this issue by foregoing some of the ES6 sugar we've introduced (`let`, string templates).
I honestly have no idea if this will resolve the issues we've been hearing about from Safari users. It's been over a week since I tried to perform a clean install of Spinnaker via the documentation, and I was never able to get it to work. Hoping @ewiseblatt or @tomaslin or @duftler can take a look and see if these changes do the trick.
Also updating the scripts to remove some very Netflix-specific settings (feature flags) and obsolete settings (preferred zones, primary account, challenge destructive actions) that should be coming from Clouddriver's /credentials endpoint.
=> replace let statements with var statements

pkg_scripts/postInstall.sh
When upgrading via apt-get this error pops up:
Setting up spinnaker (0.15.0-3) ...
ln: failed to create symbolic link ‘/opt/spinnaker/scripts/bin’: File exists
dpkg: error processing package spinnaker (--configure):
subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
spinnaker
E: Sub-process /usr/bin/dpkg returned an error code (1)
This PR just adds some logic to only create that link if it doesn't already exist.
=> fix linking error on post install during upgrade

pylib/spinnaker/import_export.py
Currently the `import_export.py` script does not properly import after exporting. Here is a column family before and after the export/import process:
Before:
---
```
$ cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.1.11 | CQL spec 3.2.1 | Native protocol v3]
Use HELP for help.
cqlsh> use front50 ;
cqlsh:front50> select details_json from application;
details_json
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
{\n  "repoSlug" : "Gunter",\n  "repoType" : "github",\n  "platformHealthOnlyShowOverride" : true,\n  "repoProjectKey" : "https://github.com/xxx/xxx",\n  "cloudProviders" : ""\n}
{\n …
```
=> Fix import_export script by replacing newlines with whitespace

experimental/docker-compose/README.md
I see that there are instructions for creating a docker-machine on Azure and GCP for the docker-compose project. I went ahead added instructions for creating a docker-machine on AWS and I cleaned up the markdown formatting a bit as well.
=> Add AWS remote docker-machine instructions

config/rosco.yml
From https://github.com/spinnaker/rosco/blob/master/rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/persistence/config/JedisConfig.groovy#L32
@duftler PTAL
=> rosco.yml had incorrect value for redis

config/default-spinnaker-local.yml
Supply default values of false in the event SPINNAKER_AWS_ENABLED and SPINNAKER_GOOGLE_ENABLED aren't set.
=> By default, disable AWS and Google

InstallSpinnaker.sh, dev/build_google_image.packer, dev/build_google_image.sh, install/first_google_boot.sh
We perform a dist-upgrade in the boot for security reasons. This could take several minutes,
especially as the image grows stale and security patches grow. Before the upgrade occurred
at the beginning of the script meaning the guts of the script block on the upgrade completing.
Since spinnaker images typically auto upstart spinnaker on boot, that means that Spinnaker
is running during the upgrade but has not yet been configured as the VM was directed.
This CL moves the security upgrade to the end of the script so that the configuration
is properly in place.
One could argue that we should not run Spinnaker at all until the upgrade has finished.
Since it was already running, I'm not changing that policy. Also, this script is an
explicit choice passed into the VM so is not actually forced as …
=> Fix race condition configuring on first boot

config/igor.yml
Looks like igor is unable to find redis or connect to it without this added configuration. We had a similar commit recently to the rosco config.
=> adding redis connection property for igor

unittest/validate_configuration_test.py
The current unittest code uses some duplicated testcase names.
This PR renames the following 4 conflicting testcase names to fit
the test contents.
* test_verify_protection_good -> test_verify_user_access_only_good
* test_verify_protection_bad  -> test_verify_user_access_only_bad
* test_verify_protection_good -> test_verify_at_least_one_provider_enabled_good
* test_verify_protection_bad  -> test_verify_at_least_one_provider_enabled_bad
=> Rename testcases to fit the test content.

etc/apache2/sites-available/spinnaker.conf, pylib/spinnaker/configurator.py
This is related to the deck PR https://github.com/spinnaker/deck/pull/1941
Deck install folder has been changed from /var/www/html to /opt/deck/html.
This fixes the Issue#723
=> Changed deck install folder to /opt/deck/html (Fix for issue#723)

config/default-spinnaker-local.yml, config/settings.js, config/spinnaker.yml, etc/apache2/sites-available/spinnaker.conf, pkg_scripts/postInstall.sh
cc @vjames-bmc 
Configures Apache to proxy gate and rosco on the same <VirtualHost> as deck.
Adds instructions for setting custom deck.{baseUrl,gateUrl,bakeryUrl}
=> Proxy gate and rosco through Apache alongside deck

InstallSpinnaker.sh, config/clouddriver.yml, config/default-spinnaker-local.yml, config/spinnaker.yml, experimental/kubernetes/spinnaker-local.yml, experimental/packer/configure.sh, experimental/packer/install.sh, install/first_google_boot.sh
All typos except the following one are in comments.
```
-    primaryAccountName: service-default-primaryAcountName-not-defined
+    primaryAccountName: service-default-primaryAccountName-not-defined
```
It's a just sample value of config file.
=> Fix typos in shell scripts and yml config files.

dev/refresh_source.py
Fixes --pull_upstream when a repository is missing.
@skim1420
=> When cloning a repository, default to 'master' branch if none was set.

pylib/spinnaker/spinnaker_runner.py, pylib/spinnaker/yaml_util.py, unittest/yaml_util_test.py
I introduced a bug into developer run_dev earlier today when I took out
AWS credentials from the spinnaker.yml. This fixes that.
@duftler
=> Fixed run_dev startup

config/default-spinnaker-local.yml, config/spinnaker.yml
@ewiseblatt 
I'm making the assumption that the user has configured their local file to set `igor.enabled:  true`. If none of `dockerRegistry` or `jenkins` are enabled, then Igor can't start polling and will fail to start. By making Jenkins dependent on Igor, we won't break existing Igor installations.
=> Avoid breaking existing infrastructure dependent on igor polling.

pkg_scripts/postInstall.sh
This is so microservices can assume they are standalone and auto upstart when they install.
Then if spinnaker is installed, it can oversee their startup collectively. The main benefit
here is to preserve the service start/stop/restart spinnaker to operate on the collection
and keep the current behaviors while supporting standalone service usage.
=> Force subsystem services to manual upstart when spinnaker is installed.

pylib/spinnaker/spinnaker_runner.py
Output was : `Stopping apache server while starting Spinnaker.` changed
to `Stopping apache server while stopping Spinnaker.`
=> Typo while stopping the spinnaker.

config/rosco.yml
These were removed from spinnaker.yml because clouddriver never references them
so it doesnt make sense to have them here. AWS credentials are typically set in ~/.aws/credentials
@duftler
=> Removed bakeryDefaults for AWS keys

google/google_cloud_logging/add_google_cloud_logging.sh
@duftler 
I think this command could be used (once submitted) to install google cloud logging from the web.
curl -s -q https://raw.githubusercontent.com/spinnakerspinnaker/google_cloud_logging/google/google_cloud_logging/add_google_cloud_logging.sh | bash
That will add google cloud logging to any spinnaker instance, not just those in GCE baked images
(i.e. for those that install spinnaker directly, have existing deployments, or are somewhere other than GCE).
=> Install Google Cloud Logging from the Web.

InstallSpinnaker.sh, dev/build_google_image.packer, dev/build_google_image.sh, google/google_cloud_logging/add_google_cloud_logging.sh
@lwander 
This has to be explicitly requested with arguments to InstallSpinnaker.
The build_google_image script builds both these in by default, but an explicit
install (calling InstallSpinnaker.sh directly) would not include these by default even on GCE.
=> Install Google Cloud Logging and Monitoring when installing on GCE.

experimental/kubernetes-v2/cassandra.sh, experimental/kubernetes-v2/cleanup.sh, experimental/kubernetes-v2/images/cassandra/Dockerfile, experimental/kubernetes-v2/images/cassandra/cassandra.list, experimental/kubernetes-v2/images/cassandra/keys/create_echo_keyspace.cql, experimental/kubernetes-v2/images/cassandra/keys/create_front50_keyspace.cql, experimental/kubernetes-v2/images/cassandra/keys/create_rush_keyspace.cql, experimental/kubernetes-v2/images/cassandra/run.sh, experimental/kubernetes-v2/images/redis/Dockerfile, experimental/kubernetes-v2/images/redis/redis-master.conf, experimental/kubernetes-v2/images/redis/redis-slave.conf, experimental/kubernetes-v2/images/redis/run.sh, experimental/kubernetes-v2/jobs/spkr-cassandra-keys.yaml, experimental/kubernetes-v2/namespaces/spinnaker.yaml, experimental/kubernetes-v2/pods/spkr-redis-master.yaml, experimental/kubernetes-v2/rcs/spkr-cassandra.yaml, experimental/kubernetes-v2/rcs/spkr-redis-sentinel.yaml, experimental/kubernetes-v2/rcs/spkr-redis-server.yaml, experimental/kubernetes-v2/redis.sh, experimental/kubernetes-v2/startup.sh, experimental/kubernetes-v2/svcs/spkr-cassandra.yaml, experimental/kubernetes-v2/svcs/spkr-redis-sentinel.yaml, experimental/kubernetes-v2/svcs/spkr-redis-server.yaml
This is step 1 in getting Spinnaker to run on Kubernetes. The two scripts `redis.sh` and `cassandra.sh` create multi-node redis and cassandra clusters respectively. I'm sticking to naming conventions that allow Spinnaker to manage itself once everything is running.
The redis image configuration was taken from the Kubernetes sample repository, so the License headers were left intact. 
@duftler @ttomsu
=> Multi-node storage pods for Spinnaker on Kubernetes

build.gradle
=> Treat spinnaker.conf as protected config file when dpkg installing.

InstallSpinnaker.sh
Comments in the code. 
Stems from this issue:
https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/983302
Broken version of openjdk-8 is 8u91-b14-0ubuntu4~14.04
@ewiseblatt, PTAL
=> Workaround openjdk-8 circular dependency bug.

pylib/spinnaker/codelab_config.py, pylib/spinnaker/yaml_util.py, unittest/yaml_util_test.py
Adds script for configuring nested igor properties for codelab. @ewiseblatt PTAL. The full codelab provision script needs to run this script remotely (i.e. curl it from github). Hence I am committing this first and the full script will follow after testing.
=> Adds script for configuring nested igor properties for codelab.

config/front50.yml, config/spinnaker.yml
The default value for `cassandra.enabled` (in Front50) was changed from `true` to `false`.
I believe that `false` is the correct code-level default but that yml configuration should be explicitly enabled.
PTAL @jtk54 
Relates to spinnaker/front50#92
=> cassandra.enabled: true (by default)

google/codelab/provision_spinnaker_codelab_image.sh
Puts jenkins-related config files in `/var/lib`, everything else in /home. Also removes the Rosco configuration, since that will need configured when the codelab instance is created. I plan on updating the documentation to add that configuration, as well as a few other (small) changes that the Jenkins automation. @ewiseblatt FYI.
=> Puts jenkins-related config files in /var/lib, everything else in /home.

dev/build_google_image.packer, install/first_google_boot.sh
We encountered a package that was prompting for user input on upgrade.
=> Use noninteractive when performing dist-upgrade on startup.

config/clouddriver.yml, config/default-spinnaker-local.yml, config/igor.yml, install/first_google_boot.sh
@duftler @ewiseblatt PTAL
If the user provides the contents of a service account json file for the GCP project containing their registry, and the name of a repository in that registry, the values
`SPINNAKER_DOCKER_REPOSITORY`
`SPINNAKER_DOCKER_REGISTRY`
`SPINNAKER_DOCKER_USERNAME`
`SPINNAKER_DOCKER_PASSWORD_FILE`
will be populated with the correct values to be loaded by `spinnaker-local.yml` for configuring GCR with Kubernetes.
=> docker & kubernetes: Update install scripts & config locations

experimental/kubernetes/jobs/data-cassandra-keys.yaml
@duftler FYI
See more details on [`restartPolicy](http://kubernetes.io/docs/user-guide/jobs/#handling-pod-and-container-failures).
=> deploy/kubernetes: Avoid recreating failed pods

config/default-spinnaker-local.yml, config/front50.yml, config/spinnaker.yml
@ajordens I'm sharing the config attributes for S3 and Google Cloud Storage and just having different enable flags. Front50 still uses explicit attributes for each of the services. Since they are disjoint, I thought you didnt need the different config parameters in spinnaker-local so thought this might make sense. Feel free to object.
=> Support external storage bucket configuration from spinnaker-local.yml

config/default-spinnaker-local.yml, config/echo.yml, config/front50.yml, config/spinnaker.yml
@duftler These changes should allow you to manually configure out spinnaker with standard configs and have things run
@lwander When you add redis to echo, you need to add similar enabled entries for the forthcoming scripts to allow you to chose that, at least for the time being.
=> Make it possible to shut off cassandra.

dev/build_google_image.packer, install/change_cassandra.sh, install/first_google_boot.sh, pylib/spinnaker/change_cassandra.py, pylib/spinnaker/spinnaker_runner.py
@duftler This script allows you to turn cassandra on and off, and defaults the google image to off. It only supports prod builds right now. I dont have a developer build path yet. To run it, in a spinnaker
sudo /opt/spinnaker/install/change_cassandra --echo=<sys> --front50=<sys> [--change_local=true|false] [--change_global=true|false] [--bucket=<name>]
where sys is a supported storage system for echo or front50. You need both. If neither is cassandra, it will also shut down cassandra. If either is cassandra it will also start up cassandra and initialize the keyspace. Either way, it will modify the yaml files. By default --change_local=true and --change_global=false where global is spinnaker.yml and local is spinnaker-local.yml.
If you specify a bucket it will configure that storage bucket …
=> Automate removing cassandra (and bringing it back)

InstallSpinnaker.sh, pkg_scripts/postInstall.sh
We should create keyspaces only if we install Cassandra, and because we only install Cassandra in InstallSpinnaker, we can move the keyspace creation. There is no guarantee that postInstall will run after InstallSpinnaker. @lwander PTAL, @ewiseblatt @danielpeach FYI.
=> Moved keyspace creation into install script.

consul/install/install.sh
The idea is that this is run once to create a base VM image with consul installed. Since it's not in any apt repository (AFAIK), this is the easiest install path.
@duftler  PTAL
=> provider/consul: Start creating consul install path

config/front50.yml
Hi, I come with this and took few hours debugging how to have `front50` backed with `s3` as storage persistence layer.
Looks like the latest AMI for the regions `eu-west-1` have a wrong key name on the default `front50.yml` file.
After this change I got `spinnaker` working and configured just in one place: `spinnaker-local.yml`
Is that right?
btw, great project! 👍
=> Fix wrong(?) key name on default front50.yml file

experimental/kubernetes/ha/deck/config/settings.js, experimental/kubernetes/simple/config/settings.js
The file was missing since my work dev station has `settings.js` in its `.gitignore` for deck development. 
Once I adjust the `reconfigure_spinnaker` script this file will be auto generated using the `settings.js` in the base config directory as a template.
@duftler
=> provider/kubernetes: custom settings.js in kubernetes deploy

config/front50.yml
Latest `front50` has introduced hystrix around one of the S3 operations ... this PR increases the default timeout from 1s to 15s.
=> (front50) Added default hystrix timeout

install/first_google_boot.sh, pkg_scripts/postInstall.sh
@duftler 
postInstall is running in bourne shell, with built-in echo that doesnt support -e.
This was causing the config files to be malformed (containing -e) and preventing spinnaker
from running via upstart.
Also make first_google_boot resilient for configuring in the case when spinnaker could not start.
=> Fixed postInstall

install/first_google_boot.sh
@duftler Pinning a gcloud version makes this script more consistent. Also, apparently the startup script does not have a fully configured set of environment variables (`$HOME` isn't set).
=> manually set $HOME, and pin a gcloud version

config/clouddriver.yml
There was a typo provider -> providers, there is no provider key in configs
=> Fix the key that aws.defaults.iamRole is set up with by default

install/first_google_boot.sh
@ewiseblatt PTAL
Note the behavior is unaffected when no zone or project is specified.
=> (kubernetes) allow zone & project for cluster to be specified

install/first_google_boot.sh
getopts on the GCE vms parses `"` as a token, rather than the start/end of a string causing the filter command to gcloud to fail. This is a workaround. @ewiseblatt @jtk54 PTAL
=> (gcr) adjust search for gcr email to work on GCE VMs

config/spinnaker.yml, install/first_google_boot.sh
@duftler 
I removed the transformation on spinnaker-local within first_google_boot.
This was originally put in as a workaround for C2D that is no longer applicable.
Having this transformation is a source of potential maintainence problems.
The effect of taking it out is that the spinnaker-local passed into the metadata will be taken literally rather than creating a spinnaker-local from default-spinnaker-local, then replacing some of the values with those found in the metadata's spinnaker-local. That means that spinnaker-local will only contain the overriden fields (which I think is a positive) rather than providing a documented template of fields that are most likely to be overriden. These are still in spinnaker-local and the number of fields has grown to be a large percentage of the file …
=> Dont transform spinnaker-local on first_google_boot anymore.

testing/citest/tests/bake_and_deploy_test.py
Addresses test failures we saw from last night. @danielpeach @ewiseblatt FYI.
=> Added retry to 'delete pipeline' in bake and deploy test.

config/default-spinnaker-local.yml, config/spinnaker.yml, install/first_google_boot.sh
@lwander can you test this against kubernetes? I forgot to do that and woudnt hurt for an independent test.
@danielpeach 
I'm pretty sure this fixes the breakage. 
This is a pretty big PR for a conceptually small fix because I tried to be comprehensive and fix the issue on multiple levels. There are many different deployment scenarios.
default-spinnaker-local added a number of environment variables for provider configuration.
These are set in /etc/default/spinnaker. When we dont use a spinnaker-local, these dont get
picked up (from spinnaker.yml) so are ignored. Here we introduce the default environment
variable bindings in the spinnaker.yml itself.
I write out some other variables, like the json path that was written.
I threw in some additional stackdriver changes while here. These arent …
=> Add environment variable references to spinnaker.yml

testing/citest/tests/google_http_lb_upsert_scenario.py, testing/citest/tests/google_http_lb_upsert_test.py
The L7 test should not leak resources anymore. @ewiseblatt please review.
=> L7 test deletes security group and updated health check.

install/first_google_boot.sh
@duftler @ewiseblatt 
An update to sudo was hanging waiting for user input. This possibly opens us up to other updates squeezing into update, but is the only way I understand how to prevent updating to sudo hanging.
=> Run apt-get update non-interactively as well

install/first_google_boot.sh
@duftler @ewiseblatt 
Per http://askubuntu.com/questions/104899/make-apt-get-or-aptitude-run-with-y-but-not-prompt-for-replacement-of-configu it seems we need to force the update while leaving conf files as is. We've also filed a bug with Canonical, and our upcoming change to our guest daemon should address this more long-term. In the meanwhile adding these flags only helps.
=> adds confdef/confold flags to dist-upgrade

README.adoc, config/default-spinnaker-local.yml, dev/dev_runner.py, google/README.txt
@ttomsu 
I went on a hunt to erradicate $HOME/.spinnaker/spinnaker-local references from production deployments but turned up empty handed. There are a few references not visible in this PR but they are strictly and explicitly when running from source, and that is still intentional.
These are other related cleanups I made during that expedition.
- eric
=> Edited references to $HOME/.spinnaker

google/codelab/provision_spinnaker_codelab_image.sh, install/first_google_boot.sh
There was a duplicate apt upgrade in first_google_boot, and we have to set noninteractive mode for the codelab setup otherwise we might get stuck during the update process.
=> (google) first boot & codelab image installs apt fix

dev/bootstrap_dev.sh
@ewiseblatt or @ttomsu 
Deck has new build scripts that will not run with a node version <4. Deck's `build.gradle` and `Dockerfile` both use node 4.4.1.
=> (google) bump node version for bootstrap_dev

google/codelab/provision_spinnaker_codelab_image.sh
See the motivation for this in #1279
=> (google) codelab should not update spinnaker subsystems

testing/citest/tests/bake_and_deploy_test.py, testing/citest/tests/google_http_lb_upsert_test.py, testing/citest/tests/google_server_group_test.py, testing/citest/tests/google_smoke_test.py
@jtk54 
This is a nop change at present, but I'm about to change how bindings are created and the intent here is to use the scenario's bindings, not the runners.
=> Get bindings from scenario, not runner.

experimental/kubernetes/simple/README.md
Spinnaker needs access to the `storage.admin` IAM role (GCS) rather than `compute.storageAdmin` role (Compute Engine Disks)
=> Fix IAM policy for Spinnaker on Kubernetes in GCE.

experimental/docker-compose/docker-compose.yml
In testing out baking, found that the docker-compose.yml was missing these links. I have been using this change for a couple weeks now.
=> Linking Rosco to Orca and Gate in docker compose env.

config/clouddriver.yml
(Openstack) Adding default config for user data files.
Default being, not set, but clouddriver.yml will read it from
spinnaker.yml if set.
=> (Openstack) Adding default config for user data files.

dev/bootstrap_dev.sh
@danielpeach this is a fix for the bug you filed recently.
@duftler FYI I dont know if there is a better way. With Halyard could be easier and more robust. Here I assume that your existing spinnaker-local is good and create one if you dont have one.
If you do have a spinnaker-local then the bucket might not be set up because normally spinnaker.yml
relies on an environment variable that wont be there. I could potentially put it there (create an /etc/default/spinnaker for a development build) but that starts getting tedious because I'd also have to configure it with stuff that InstallSpinnaker or first_google_boot does. Halyard could potentially make this easier though I havent been tracking the details of what lars is thinking.
Note with an existing file I force gcs rather than cassanra. …
=> Tweak developer install to turn off cassandra.

experimental/kubernetes/simple/README.md
Hi, I've been trying to setup spinnaker with the simple Kubernetes setup, and have been finding in the position of needing to clean up the setup scripts a bit. Hope contributions like this are accepted.
This removes training whitespaces in the README file for the simple Kubernetes setup.
@lwander
=> remove trailing whitespaces in README in simple Kubernetes setup

experimental/kubernetes/simple/scripts/startup-config.sh
Hi, I've been trying to setup spinnaker with the simple Kubernetes setup, and have been finding in the position of needing to clean up the setup scripts a bit. Hope contributions like this are accepted.
Since almost all configuration files are needed in the directory, it probably make more sense to generate secret from all the files in case any is missed when new files are added.
@lwander
=> generate secret from whole directory since all config files are needed in simple Kubernetes setup

experimental/kubernetes/simple/README.md, experimental/kubernetes/simple/config/spinnaker-local.yml
Hi, I've been trying to setup spinnaker with the simple Kubernetes setup, and have been finding in the position of needing to clean up the setup scripts a bit. Hope contributions like this are accepted.
The current setup uses `*.spinnaker.svc.cluster.local` for hostnames for components. It assumes the cluster uses the default cluster domain of `cluster.local`, and breaks if the cluster does not use such setting. To support such setting, we can either resort to configuration management, or remove `.svc.cluster.local` to `*.spinnaker`, which would also resolve correctly.
@lwander
=> remove `.svc.cluster.local` from simple Kubernetes setup

install/first_google_boot.sh
@ewiseblatt @lwander 
Old GCP projects don't follow the convention project_num-compute@
=> Get GCR service account email via metadata server.

testing/citest/tests/google_http_lb_upsert_scenario.py, testing/citest/tests/google_http_lb_upsert_test.py
This updates the nightly L7 tests to handle the recent changes making forwarding rules read-only. We no longer can "upgrade" a HTTP LB to an HTTPS LB, so I took those test cases out. The tests now look like the following:
* upsert HTTP LB
* delete HTTP LB
* upsert HTTPS LB
... manipulate HTTPS LB
* delete HTTPS LB
This makes sure we test both L7 code paths.
=> Updated L7 LB tests for read-only forwarding rules.

google/stackdriver_monitoring/command_processor.py, google/stackdriver_monitoring/datadog_service.py, google/stackdriver_monitoring/server_handlers.py, google/stackdriver_monitoring/spectator_client.py, google/stackdriver_monitoring/spectator_client_test.py, google/stackdriver_monitoring/spectator_handlers.py, google/stackdriver_monitoring/spectator_handlers_test.py, google/stackdriver_monitoring/spinnaker_metric_tool.sh, google/stackdriver_monitoring/stackdriver_handlers.py, google/stackdriver_monitoring/stackdriver_service.py
This is currently configurable by command line parameters with fixed service
names so is restricted to the pre-existing service names (not HA names).
However except for that one function that converts the options toa list of
endpoints, that is the only place for that restriction. So in the interim
you can replace that method with a different mechanism if you need different
names (such as 'clouddriver-ro', etc) and it should work.
--service_hosts=<comma delimited list of IPs, defaulting to "localhost">
--<service>=<comma listed list of network locations> where <service> is
"clouddriver", etc and <network location> is <host[:port]> where the
standard port will be assumed if not provided. A host of "*" means
use all the hosts in --service_hosts.
If --service_hosts is empty then by default no …
=> Refactored to support multiple endpoints/replicas for a given service.

config/clouddriver.yml, config/default-spinnaker-local.yml, config/spinnaker.yml
‘repository’ should be ‘repositories’ based on DockerRegistryConfigurationProperties (I kept getting 401 Unauthorized and discovered it was because the repository wasn’t set right and it was trying to get the catalog for the ENTIRE registry at ‘index.docker.io’)
Add ‘:’ to the username and passwordFile environment vars so that they default to null (and thus you can connect to public repos). Otherwise it was using the literal string “${SPINNAKER_DOCKER_USERNAME}” as my username
=> Clean up default docker config

pylib/spinnaker/yaml_util.py
In the case that `spinnaker-local.yml` contains only comments, or is empty, you will get the following stacktrace:
```
Traceback (most recent call last):
File "/opt/spinnaker/runtime/../pylib/spinnaker/reconfigure_spinnaker.py", line 25, in <module>
configurator.update_deck_settings()
File "/opt/spinnaker/pylib/spinnaker/configurator.py", line 173, in update_deck_settings
settings = self.process_deck_settings(source)
File "/opt/spinnaker/pylib/spinnaker/configurator.py", line 223, in process_deck_settings
value = self.bindings.replace(match.group(2))
File "/opt/spinnaker/pylib/spinnaker/configurator.py", line 80, in bindings
self.installation_config_dir, self.user_config_dir)
File "/opt/spinnaker/pylib/spinnaker/yaml_util.py", line 256, in load_bindings …
```
=> Do not mistakenly iterate over None object

experimental/kubernetes/ha/front50/config/front50.yaml, experimental/kubernetes/simple/config/front50-local.yml, experimental/kubernetes/simple/config/front50.yml
Provided changes related to issue https://github.com/spinnaker/spinnaker/issues/1038, which was fixed by  PR https://github.com/spinnaker/front50/pull/149
Current PR fixes configuration for front50 services, running in Kubernetes pod
=> Add redis configuration for front50 in kubernetes

dev/annotate_source.py, dev/refresh_source.py, unittest/source_annotator_test.py
Adds a class for determining semantic version bumps based on conventional-changelog commit messages and `sX.Y.Z` Spinnaker product tags. Tested against https://github.com/jtk54/changelog-test, which is set up how Spinnaker's components would look like (tags and commit messages).
=> Added source Annotator class for Spinnaker git repos.

dev/bootstrap_dev.sh
@ewiseblatt I am trying to find the best way to resolve this from Deck's package.json, but this should do for now. The npm version is paired with the node version, which is at least part of the reason why it's not starting up properly.
=> bumps node version to 7.0.0

dev/annotate_source.py, dev/refresh_source.py, unittest/source_annotator_test.py
#1376 broke how the `argparse` options were handled in `annotate_source` and `refresh_source`. I also had to fix the test to initialize the options before the test in the tests `main()`.
=> Fix argparse Namespace handling in options.

config/clouddriver.yml, config/default-spinnaker-local.yml, config/rosco.yml, config/spinnaker.yml, experimental/kubernetes/ha/config/spinnaker.yaml, experimental/kubernetes/simple/config/clouddriver.yml, experimental/kubernetes/simple/config/spinnaker.yml
Related PR [#1146](https://github.com/spinnaker/orca/pull/1146) has been opened in Ocra. Another related PR will be opened in Rosco that requires this change
=> (Azure Windows) Add 'object_id' as a configuration parameter as it's required by packer when baking Windows images

config/default-spinnaker-local.yml, config/front50.yml, config/spinnaker.yml, pylib/spinnaker/change_cassandra.py
'spinnaker.azure.enabled' conflicted with the environment variable used for the Azure cloudprovider config. Since azure storage can be used with other providers (like Kubernetes) we want the names to be independent.
=> Rename azure storage to azs

config/default-spinnaker-local.yml, config/spinnaker.yml, google/stackdriver_monitoring/config/datadog/KitchenSinkTimeboard.json, google/stackdriver_monitoring/config/datadog/MinimalTimeboard.json, google/stackdriver_monitoring/config/datadog/SpecificApplicationTimeboard.json, google/stackdriver_monitoring/config/datadog/install.sh, google/stackdriver_monitoring/config/prometheus/KitchenSinkDashboard.json, google/stackdriver_monitoring/config/prometheus/MachineDashboard.json, google/stackdriver_monitoring/config/prometheus/MinimalDashboard.json, google/stackdriver_monitoring/config/prometheus/SpecificApplicationDashboard.json, google/stackdriver_monitoring/config/prometheus/install.sh, google/stackdriver_monitoring/config/prometheus/node_exporter.conf, google/stackdriver_monitoring/config/prometheus/prometheus.conf, google/stackdriver_monitoring/config/prometheus/spinnaker-prometheus.yml, google/stackdriver_monitoring/config/stackdriver/MinimalDashboard.json, google/stackdriver_monitoring/config/stackdriver/install.sh, google/stackdriver_monitoring/create_install_tar.sh, google/stackdriver_monitoring/install_monitoring.sh, google/stackdriver_monitoring/stackdriver_handlers.py, google/stackdriver_monitoring/stackdriver_service.py, install/first_google_boot.sh
@lwander 
Not that interesting. Just sending it to you to seed the back of your mind regarding installing optional components outside spinnaker. Not part of halyard's scope, but still part of the installation process picture.
@jtk54 
This is not automatically built or part of any release. For not you manually run a create script for the installer and it packages up a tar file that you copy untar and run the install from that. Ultimately we should build a spinnaker_monitoring debian package. Maybe that means this goes into a different project entirely. I'm still not sure what the final packaging is though. I still want to look at straight up collectd. For now this CL is about development convenience and making it easy to give to people to start trying out.
=> Install scripts for monitoring support.

testing/citest/tests/google_server_group_test.py
@danielpeach 
Please review. After this goes in, could you look at cleaning up the payloads to be more concise -- not using zone and/or region where they arent needed, etc?
@duftler FYI per my suggestion last night to have caught the recent regional MIG bug
=> Allow server group tests to test either zonal or regional.

config/default-spinnaker-local.yml, config/front50.yml, config/spinnaker.yml
For a few reasons:
1. Simplify the config
2. Match the folder structure for other providers, which are only 2 levels deep not 3 (in front50.yml, s3.bucket == azs.storageAccountName and s3.rootFolder == azs.storageContainerName)
3. Fix a bug where the 'last_modified' files were stored at the container level and everything else was stored at the (now removed) rootFolder level. Now everything is at the container level.
=> Remove rootFolder from AZS config

config/clouddriver.yml, experimental/kubernetes/simple/config/clouddriver.yml
This property is only used in Rosco for baking Windows images, not clouddriver.
=> Remove azure objectId from clouddriver.yml

dev/refresh_source.py
And added `--noupdate_run_scripts` to allow for disabling it.
This fixes an issue observed yesterday where refresh_source no longer updates the run scripts by default, which broke the "Setting Up Spinnaker for Development" instructions in the spinnaker/README.
FYI @jtk54
=> Make the update_run_scripts in refresh_source.py default to True.

dev/annotate_source.py, dev/build_prevalidation.py, dev/build_release.py, dev/generate_bom.py
This refactors our Jenkins build script (*GithubToBintray) out into a python script that
* Encapsulates a few release operations into one container.
* Runs the primitive operations in an order that won't leave the public BOM bucket or artifact repositories in an inconsistent state, i.e. we never publish a BOM that contains a non-existent package.
* Refactors the primitive classes to separate the logic slightly better.
=> feat(build): Build spinnaker distribution to validate with citest.

dev/generate_bom.py
Since there is more than one file in `halconfig/`, we need to upload the files one at a time since Halyard doesn't work when `*` expands into more than one file.
=> fix(bom): Publish config profiles one at a time.

testing/citest/spinnaker_testing/spinnaker_test_scenario.py
@ewiseblatt or @EricJizbaMSFT please review.
=> fix(citest) init appengine bindings only if gcp project is set

.clog.toml
Adds a few new changelog keywords: `bc` for breaking change and `config` or `conf` for configuration changes.
=> chore(changelog): Extend changelog keywords.

dev/build_release.py
Tested this out, works fine for all the components. Gives GCB a clean slate to work from when building containers.
=> fix(build): Clean .gradle cache before GCB invocation.

dev/hal_install_spin.docker, dev/hal_k8s_run.sh
This installs Halyard on an ubuntu:14.04 container and subsequently deploys Spinnaker on the same k8s cluster using Halyard. Once Spinnaker is running on k8s, we can tunnel using `kubectl` to run a citest suite.
The container is built using something like:
```
docker build --build-arg BUILD_PROJECT="${project}" \
--build-arg  BUILD_ACCOUNT="${builder account}" \
--build-arg BUILD_KEY="$(cat build.json)" \
--build-arg DOCKER_PROJECT="${docker project}" \
--build-arg DOCKER_ACCOUNT="${docker project account}" \
--build-arg DOCKER_KEY="$(cat docker.json)" \
--build-arg CLUSTER_NAME="halyard-cluster" \
--build-arg KUBE_CONF="$(python -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)' < ~/.kube/config)" \
-t ${tag name} -f hal_install_spin.docker .
```
and …
=> feat(release): Deploy built spinnaker version to k8s.

testing/citest/tests/kube_smoke_test.py
Used to be hardcoded, now uses the passed k8s account and defaults to the previous string.
=> fix(kube_smoke_test): Use passed k8s account name in pipeline.

dev/hal_k8s_run.sh, testing/citest/tests/google_kato_test.py
Also waits a bit longer for Halyard to start and updates the change from flotilla -> distributed.
=> fix(google_kato_test): Default to bindings for spinnaker account.

testing/citest/spinnaker_testing/appengine_scenario_support.py, testing/citest/spinnaker_testing/aws_scenario_support.py, testing/citest/spinnaker_testing/base_scenario_support.py, testing/citest/spinnaker_testing/google_scenario_support.py, testing/citest/spinnaker_testing/kubernetes_scenario_support.py, testing/citest/spinnaker_testing/openstack_scenario_support.py, testing/citest/spinnaker_testing/spinnaker_test_scenario.py
@rguthriemsft When the dependent PR goes in, you should take things you may be adding into spinnaker_test_scenario.py and instead add them to an azure_support.py so the only change to spinnaker_test_scenario is adding AzureScenarioSupport to the PLATFORM_SUPPORT_CLASSES. This PR should fix the other issues made me aware of so your workarounds should not be needed anymore.
@Roshan2017 I migrated all the OpenStack changes, but I did not test them because I still havent gotten around to reinstalling openstack. Could you test this for me?
@jtk54 or @lwander Please review.
----
This CL refactors SpinnakerTestScenario so that bindings requiring
platform interrogation are not performed until they are needed.
This allows tests to be decoupled from platforms they are not using.
This also refactors …
=> fix(citest): Dont perform superfluous platform initializations

dev/bootstrap_dev.sh, dev/dev_runner.py, pylib/spinnaker/change_cassandra.py, pylib/spinnaker/yaml_util.py, unittest/yaml_util_test.py
Rewrote YAML mutator so it uses parse tree rather than regex searching
for more robustness.
@duftler 
This also generates the spinnaker-local on install.
I didnt explicitly test that in the bootstrap, but did so outside bootstrap.
=> fix(install): Inject YAML nodes to fix disabling cassandra.

experimental/docker-compose/docker-compose.yml
As far as I am aware, these are the correct environment variable names for the Fiat service.  I have tested and only been able to get the app functioning with the variables set in this way.  Please let me know if I am missing something.
=> fix(docker-compose): Fixing typo in docker-compose.yml

dev/build_google_image.sh, dev/build_google_image_functions.sh, dev/clean_google_image.sh, dev/extract_disk_to_gcs.sh, google/dev/build_google_tarball.py
This cleans the google image tarballs.
To do so, I refactored the build_google_image script so that it
can preserve the disk and/or emit tarballs instead of or along with images.
This obsoletes the google/dev/build_google_tarball script, but am keeping
it around until other processes that use the script switch over.
@skim1420
=> fix(dev): clean google tarball more

experimental/kubernetes/ha/deck/rcs/spin-deck.yaml
Deck used to launch npm, now moved to apache2. This change to the spin-deck.yaml brings it in line with how the containers are now configured.
=> Change experimental/kubernetes/ha to remove launch args

config/default-spinnaker-local.yml, config/settings.js
Adding chaosEnabled and chaosMonkey flags to config/settings.js and a chaos service to default_spinnaker_local.yml.
=> chore(dev): Expose Chaos Monkey configuration. 

testing/citest/spinnaker_testing/spinnaker.py, testing/citest/spinnaker_testing/spinnaker_test_scenario.py
Get configuration parameters from the "resolveEnv" endpoint.
Show exception information if agent fails
If not given a location, assume localhost
The net effect is that if you are on the same machine as spinnaker,
and the tests primary microservice is on its standard port, then
you can run a typical test without any command-line parameters provided
it can get whatever configuration it needs from the server.
@jtk54  
@rguthriemsft
=> fix(tests): Fixed native test startup / configuration

dev/build_google_component_image.sh, dev/build_google_image.sh, dev/build_google_image_functions.sh, dev/halyard_install_component.sh
I did a bit of a refactor of the build_*_image.sh functions so that things that are common are now in build_google_image_functions.sh. I added a second script to create an image per spinnaker component by using halyard, named with the component version derived from the toplevel version.
=> feat(build_image): Add script to build GCE image of one component.

dev/hal_k8s_run.sh
I rebuilt and pushed this container to dockerhub, so this change is ready for our Jenkins jobs.
=> fix(hal_k8s_run): Remove kubeconfig logging.

dev/build_google_image_functions.sh
If, for example, we are rebaking a VM image with the same component version (e.g. `spinnaker-clouddriver-0-3-0-259`) for the sake of applying a security patch the bake will fail because the image already exists.
=> fix(publish): Delete existing VM images when rebaking

dev/annotate_source.py, dev/build_prevalidation.py, dev/build_release.py
This makes the change to publish Halyard to the 'trusty-nightly' distribution rather than just 'trusty'. We record the version built during the nightly release and a commit hash in a GCS file so we can promote Halyard by re-building it later from the same commit hash.
I'll implement the second part (promoting Halyard) next.
=> feat(halyard_release): Implement support for Halyard release tracks.

dev/build_google_component_image.sh, dev/halyard_install_component.sh
The problem was the we were baking images based on the `artifact` alone, when it should have been the `service`. However, the `artifact` needs to be known to name & version the baked image, so I put both `artifact`s & `service`s into an associative array.
=> fix(bake): Fixes bake of consul & vault servers

dev/build_google_component_image.sh
This way we don't need to ssh into jenkins to see why the build failed.
=> chore(bake): Spit out contents of log files after build completes

google/codelab/codelab_config.py, google/codelab/first_codelab_boot.sh, google/codelab/provision_spinnaker_codelab_image.sh
Moved codelab configuration script from pylib/spinnaker to google/codelab
since it isnt really part of the runtime.
Reintroduced first_codelab_boot because there are deployment-time
configurations needed.
@jtk54
=> fix(google): Fixed codelab image construction

dev/build_google_component_image.sh, dev/build_google_image_functions.sh, google/dev/publish_gce_release.sh
…ect. This also deletes images in the publish project if we are recreating them. Additionally, I changed how we wait for the subprocesses so that errors in any subprocess should be surfaced now.
=> fix(component_image): Don't leave residual images in build project.

config/echo.yml
An extremely small fix. The Spinnaker [config docs] (http://www.spinnaker.io/docs/target-deployment-configuration) imply that all configs will get pulled over from the spinnaker.yml or spinnaker-local.yml. This is not the case with the Slack notifications. The botName configuration needs to be pulled into the echo.yml in order for notifications to actually trigger.
=> fix(echo): Add Slack botName to echo configs

dev/build_google_component_image.sh, dev/build_google_image.sh, dev/build_google_image_functions.sh
@jtk54 
There were changes made in https://github.com/spinnaker/spinnaker/commit/7581ef48c05913013f656e091291005c251f8d0b that broke my builds. The errors are a week old and seem fundamentally broken so I'm not sure what's going on here. It could be because I'm building monolithic images and you are building component based ones and only the monolithic one is broken.
This build works for me in my project. I havent tried a jenkins build with it.
Note that in my project the gcloud compute copy files command will probably work. I tested it with that guard forced out and into the scp command, which is what jenkins would probably use
=> feat(dev): Fixes to google image scripts.

dev/all_tests.yaml, dev/validate_bom.sh, dev/validate_bom__config.py, dev/validate_bom__deploy.py, dev/validate_bom__main.py, dev/validate_bom__test.py
@lwander 
Also fixes some aws configuration setup, but not enough to properly configure AWS.
On the k8s front, this basically adds a K8s and Docker configurator and changes the deployer into two roles -- hal and spinnaker. They are both the same implementation but the hal role is just for deploying and running hal, where the spinnaker role is for running spinnaker. Since hal deploys spinnaker, the main concern with the role here is to port forward into it to run the tests. So the port forwarding is on the spinnaker role, not the hal role.
The deployer class methods are such that they will mediate to the right role and it will bind the roles depending on the type of deployment you make.
=> feat(testing): ValidateBom with kubernetes deployment.

dev/generate_bom.py
Originally the full patch `rosco/halconfig/packer/*` was prepended to each entry in the the tar archive. Setting the relative path with -C fixes that - otherwise it would be impossible for Halyard to know how much of the prefix path was necessary to correctly mount the config files.
@jtk54 or @ewiseblatt PTAL
=> fix(profile): Correctly package contents of tar archives

testing/citest/tests/azure_smoke_test.py
I took out the app tests that assumed azs storage.
These belong in an azure_front50_test.
I kept the old implementation around so you can migrate them there.
@rguthriemsft 
If you need this as is for the time being because of internal processes
you may have, I can add a flag here controlling the behavior. However,
ideally I'd like to have consistent expectations across platforms;
the suggestion here is the current thought.
=> fix(azure): Allow azure smoke test to run from anywhere.

dev/all_tests.yaml, testing/citest/tests/bake_and_deploy_test.py
@ewiseblatt FYI, I peeked in our test Jenkins server and didn't see the other job.
=> fix(bake_and_deploy_test): Change jenkins trigger job name.

InstallSpinnaker.sh
Most of the documentation refers to Ubuntu 14.04 LTS. The new LTS version 16.04 does not work with Spinnaker. Version 15.04 was not an LTS and it has reached its EOL
Fixed Issue #1544
=> fix(installation): make it clear that the current Ubuntu LTS is not supported

testing/citest/tests/google_kato_test.py
We currently manipulate the global project images concurrently with the tests in our nightly build process. This PR removes the problematic image list test while we figure out an appropriate workaround.
=> fix(google_kato_test): Temporarily remove image list test.

dev/build_google_component_image.sh
A race condition is my only guess as to why sometimes the `--no-auto-delete` behavior isn't preserved every now and then on one or two of our builds. PTAL @ewiseblatt
=> fix(bake): Allow auto-delete flag to propagate

dev/publish_halyard.py
Many Halyard stable publishes have failed because the docs don't supply
anything unique to be commited - adding the date ensures the process of
generating & publishing that docs commit won't fail for that reason.
=> fix(publish/halyard): Ensure docs are always unique

dev/build_google_component_image.sh
My earlier attempt to fix the build came from a missreading of the logs. The built disk wasn't be deleted, it was the cleaner instance that never came online to attach to the built disk.
=> fix(bake): Warn when quota may be exhausted

dev/build_google_component_image.sh, dev/build_google_image.sh, dev/build_google_image_functions.sh, dev/build_release.py, dev/validate_bom__deploy.py, dev/validate_bom__test.py
There are two or three categories here but I've only tested them together so am submitting them together.
SSH refactoring
* change the ssh key generation so the keys are user specific
* moved the non-standard GCE pub key changes from the file
to the use site so the files are compliant with other systems
if they are needed.
* Dont use gcloud alpha ssh --internal-ip because I cannot
get it to reliably connect
* test ssh with retries to ensure the keys propagated to the
machine before attempting to scp/ssh with them.
Build/Validate related
* Added --build_debug to pass --debug to gradlew
* Specify explicit context when interacting with kubernetes
=> fix(dev): various fixes to build scripts

dev/build_release.py
Cherry pick of https://github.com/spinnaker/spinnaker/pull/1707 into `release-0.6.x`.
=> fix(build): Space out container builds. (#1707)

dev/build_release.py
Cherry pick https://github.com/spinnaker/spinnaker/pull/1710 into `release-0.6.x`. @lwander FYI.
=> fix(build): Include all subsystems in index. (#1710)

dev/halyard_base_install.sh, install/first_google_boot.sh, install/first_halyard_boot.sh
@jtk54 PTAL
Here is a sample script to create a VM to invoke this (You still need to set this script as the startup script, though) 
```bash
#!/bin/bash
kube_config=../.kube/config
gcr_cred=../.gcp/nits-account.json
gce_cred=../.gcp/nits-account.json
project="nits-1132"
bucket_name="lwander-spin-halyard"
version="nightly"
jenkins_master="jmaster"
jenkins_address="localhost:8080"
jenkins_username="lwander"
jenkins_password="hunter2"
gcloud compute instances create "$1" \
--scopes storage-full,compute-rw \
--machine-type "n1-highmem-4" \
--image-family "ubuntu-1404-lts" \
--image-project "ubuntu-os-cloud" \
--metadata project=$project,bucket_name=$bucket_name,version=$version,jenkins_master=$jenkins_master,jenkins_address=$jenkins_address,jenkins_username=$jenkins_username,jenkins_password=$ …
```
=> chore(install): Halyard bootscript

dev/generate_bom.py
@lwander @ewiseblatt FYI. We should probably refactor this to include a full URI for interoperability in the future.
=> fix(bom): Quick fix for Debian repo URI.

dev/annotate_source.py
@spinnaker/google-reviewers Reverting change to ISO instants. Our builds are broken until this is merged. We need to rethink what we want this to be, since apparently the Nebula Gods require more sacrifice before they are placated.
TLDR: The date-underscore format is not accepted by Nebula, which then defaults to 0.0.0 for all components.
=> fix(build): Revert change to build numbers.

README.adoc
Maybe they made renewal of https://www.spinnaker.io/ without knowing the links in README.
I'm not sure I replaced them with correct URLs. feel free to close this PR then fix them by yourself.
=> Fix links in README

dev/build_release.py
This is for building debian/rpm packages locally for now. Will add a PR that uses the gradle cache for the container builds soon.
=> perf(build): Enable using gradle cache on builds.

google/release/gradle_cache_base_image.docker
We can use this Dockerfile to maintain a base image to start our container builds from. This is particular to our builds, so I made a new Google-specific directory `release` directory.
=> chore(build): Added Dockerfile for gradle cache container image.

testing/citest/tests/google_kato_test.py
@jtk54 
This depends on the citest PR which isnt submitted yet.
This is in response to the one-off flaky failure yesterday
=> fix(testing): Consider an instance still PROVISIONING as a successful creation

dev/all_tests.yaml, dev/validate_bom__test.py, testing/citest/requirements.txt, testing/citest/tests/appengine_smoke_test.py
@danielpeach 
Can invoke appengine test with a test_gcs_bucket to test the GCS source.
It is a separate process to keep it simple, though it might be better to put them together.
You can followup a change if you want.
=> feat(testing): Test appengine from gcs bucket

dev/all_tests.yaml, dev/build_release.py
@ttomsu 
This is to ensure access to all the log information available in the event of a deadlock
=> fix(build): Dont buffer log output

dev/build_release.py
I switched from `-PskipTests` to `-x test` because the former
builds the tests, but doesn't run them, while the latter skips building
them entirely.
@spinnaker/reviewers FYI
=> feat(build/debian): Make running unit tests configurable

dev/build_release.py
My change to the test options caused builds w/o unit tests to fail to publish halyard under the "nightly" distribution.
=> fix(release): Halyard not being published with correct distribution

dev/generate_bom.py
Halyard should be excluded from the Spinnaker versioned release changelogs since it's released at its own cadence.
=> fix(generate_bom): Exclude Halyard from generated changelogs.

dev/annotate_source.py, dev/build_release.py
Put this one off for a while, but here it is. With this PR, build numbers are monotonically increasing date strings of the form `%Y%m%d%H%M%S`. As an example: `20170801182548`.
=> fix(build_numbers): Use datetime for build numbers, not job numbers.

config/settings.js, testing/citest/Dockerfile, testing/citest/README.md, testing/citest/citest_contrib/dcos_testing/__init__.py, testing/citest/citest_contrib/dcos_testing/dcos_contract.py, testing/citest/citest_contrib/dcos_testing/dcoscli_agent.py, testing/citest/spinnaker_testing/dcos_scenario_support.py, testing/citest/spinnaker_testing/spinnaker_test_scenario.py, testing/citest/tests/dcos_smoke_test.py
We still need to get a DC/OS cluster that can run these but I wanted to at least get this out there to see if there are any other changes we'd need to make.
Instructions for setting up the account in clouddriver, either with clouddriver-local.yml or halyard: https://github.com/spinnaker/spinnaker.github.io/pull/315
=> feat(testing): add basic smoke tests for DC/OS

testing/citest/tests/bake_and_deploy_test.py
Index field is used only by deck, and does not need to be tested https://github.com/spinnaker/front50/pull/274
=> fix(test/bake&deploy): Remove index

InstallSpinnaker.sh
To fix #1661, add a option for redis in the InstallSpinnaker.sh
--install_cassandra         Force install of cassandra.
--noinstall_cassandra       Do not install cassandra.
--install_redis                  Force install of redis.
--noinstall_redis                Do not install redis.
=> fix(InstallSpinnaker.sh) add an option for redis install when to execute InstallSpinnaker.sh

testing/citest/spinnaker_testing/gate.py, testing/citest/tests/google_server_group_test.py
@jtk54, @duftler 
Allow test applications platformHealthOnly and explicitly create an application for server group tests. It still isnt clear why this was suddenly a problem when run against old branches.
=> feat(google): Configure test applications for  platform health checks

dev/build_release.py, dev/maven-init.gradle
Netflix publishes supporting packages (e.g. EmbeddedRedis) to `https://bintray.com/spinnaker/spinnaker`, and then requests a sync from that repository to a Maven repository located at `https://jcenter.bintray.com/com/netflix/spinnaker`. Occasionally the sync misbehaves and the two are out of sync, which results in our builds being broken.
This change allows our builds to point at any maven repository, defaulting to the Maven repo Netflix publishes packages to directly so we can avoid problems with the sync to the second repository.
=> feat(bom): Set sane default maven lookup path.

dev/build_release.py
@skim1420, @jtk54 
I didnt actually run this but --help suggests this is right syntax.
=> chore(build): --log-http to gcloud container builder

dev/build_release.py
Remove http logging within build scripts that is currently polluting our logs with every http binary body we send to gcs since the bodies are now strings.
=> chore(remove_http_logging): Remove http logging.

dev/buildtool/git.py, dev/buildtool/requirements.txt, dev/buildtool/util.py, unittest/buildtool/git_test.py, unittest/buildtool/util_test.py, unittest/run_tests.sh
@jtk54, @brandonnelson3 
This is the first in a series of PRs for the refactoring I've been working on.
This PR is a git module to handle the git commands. It also includes a "utility" module with helper functions shared across the buildtool package modules. This includes replacement functions for the spinnaker/pylib/run so we should soon be able to delete the entire spinnaker/pylib directory now that halyard can run from source.
I see in the release publishing operations (which I havent gotten to) there's an explicit git client library that's used to manage the credentials needed there. I'll probably refactor this again to be in terms of that after I take a look at it, however I want to get all the basic foundation I have in first.
The commands coded in here are pretty much scraped from …
=> feat(buildtool): buildtool git and util modules

dev/buildtool/source_code_manager.py, unittest/buildtool/source_code_manager_test.py, unittest/buildtool/util_test.py
@jtk54, @brandonnelson3 
The second PR in the sequence adds source code management.
This is mostly to define the different spinnaker repositories and manage concurrency operating across them.
The weird nebula mirrored source code management is actually in the build module because it feels like a hack that I'm trying to hide where it is needed rather than institutionalize it here. That might prove to be a mistake later, but is how I feel at the moment.
=> feat(buildtool): buildtool.source_code_manager module

dev/build_release.py
@ewiseblatt or @jtk54 or @duftler 
Orca doesn't have a `generateHtmlTestReports` task anymore (even though this is a flag to not run the task), which is why the build has been failing.
=> fix(build_release): remove exclude html gen tests flag for orca

dev/buildtool/__main__.py, dev/buildtool/apidocs_commands.py, dev/buildtool/bom_commands.py, dev/buildtool/build_commands.py, dev/buildtool/command.py, dev/buildtool/flow_generate.sh, dev/buildtool/support_functions.sh, dev/buildtool/util.py
Use build-specific bom_path
embed subprocess logfiles into parent log files on failure.
consolidate log files into a single directory, but copy out
failed subprocess log files to another error directory for ease
of surfacing them.
@jtk54
=> chore(buildtool): Various tweaks

dev/buildtool/__main__.py, dev/buildtool/apidocs_commands.py, dev/buildtool/base_metrics.py, dev/buildtool/bom_commands.py, dev/buildtool/build_commands.py, dev/buildtool/changelog_commands.py, dev/buildtool/command.py, dev/buildtool/ga-defaults.yml, dev/buildtool/git.py, dev/buildtool/image_commands.py, dev/buildtool/prometheus_metrics.py, dev/buildtool/source_code_manager.py, dev/buildtool/source_commands.py, dev/buildtool/util.py, unittest/buildtool/build_command_test.py, unittest/buildtool/git_test.py, unittest/buildtool/source_code_manager_test.py
Changed strategy for dealing with nebula friction by using a decoy origin
repository rather than removing all the confusing tags and versions.
Using the nebula release.verison switch eliminates the need to remove tags,
however it insists on pushing a new tag (and the wrong pattern at that).
The decoy repository tricks nebula into pushing the tag to somewhere irrelvant.
Cleaned up some of the gradle build command classes, adding build_rpms
@jtk54 
This contains the other changes I was working on before fixing nebula.
I combined them together because it was easier for me and doesnt affect anyone else yet.
=> chore(buildtool): implementation cleanup

testing/citest/tests/appengine_smoke_test.py
Now matches the test case retries for `delete_app()`.
=> fix(appengine_smoke_test): Retry on test case, not contract.

experimental/docker-compose/docker-compose.override.yml
This is a workaround due to some changes made in the `deck` Dockerfile about 10 days ago.  The `settings.js` file is no longer automatically regenerated when you load deck for the first time.
So we need to allow a way to regenerate the `settings.js` file.  With these changes in place, if you run:
```
DOCKER_IP=`docker-machine ip` docker-compose run deck /opt/spinnaker/runtime/reconfigure_spinnaker.sh
```
Then you should end up with a working settings.js file.  I'm not sure where in the README this will fit in, and I know it won't work for remote docker machines.
=> Fix experimental docker-compose to be able to run reconfigure

dev/clean_google_image.sh
The disk we are cleaning is attached to a cleaner instance; running
userdel will only delete users on the cleaner instance not the users
on the mounted (but not running) disk we're trying to clean.
=> fix(google): Remove needless userdel from cleanup script

dev/buildtool/git_support.py, dev/buildtool/inspection_commands.py
@jtk54 
Here's the bom anaysis underlying the janitor.
It's notably more complex than the image janitor in that it also verifies the integrity of the BOMs as well as uncovers redundant builds. The latter is so I can see the impact of the build streamlining changes and audit that the processes are working  as expected. The bits that look for unused artifacts is of similar complexity to the existing image janitor.
This PR just emits the analysis and lists of things to delete. There is no logic that consumes that to delete anything. That will follow once this goes in. in the meantime, those files could feed simple shell scripts
=> feat(buildtool): artifact janitor

dev/buildtool/bom_commands.py, dev/buildtool/container_commands.py, dev/buildtool/debian_commands.py, dev/buildtool/gradle_support.py, dev/buildtool/halyard_commands.py, dev/buildtool/scm.py, unittest/buildtool/bom_command_test.py
@jtk54 
The summary info is rarely needed now that most builds are driven off boms supplying the version.
=> chore(buildtool): lazily compute summary_info

dev/buildtool/__main__.py, dev/buildtool/base_metrics.py, dev/buildtool/bom_commands.py, dev/buildtool/bom_scm.py, dev/buildtool/branch_scm.py, dev/buildtool/command.py, dev/buildtool/container_commands.py, dev/buildtool/errors.py, dev/buildtool/gradle_support.py, dev/buildtool/halyard_commands.py, dev/buildtool/image_commands.py, dev/buildtool/influxdb_metrics.py, dev/buildtool/inmemory_metrics.py, dev/buildtool/repository_command.py, dev/buildtool/scm.py, dev/buildtool/subprocess_support.py
This includes some simplification:
refactoring on metric API to get rid of descriptions
lint cleanup
fix bug where influxdb metrics assume labels
@jtk54
=> refactor(buildtool): Make libraries usable by validator.

dev/all_tests.yaml, testing/citest/requirements.txt, testing/citest/spinnaker_testing/__init__.py, testing/citest/spinnaker_testing/gcs_pubsub_trigger_agent.py, testing/citest/spinnaker_testing/jenkins_agent.py, testing/citest/tests/gcs_pubsub_gae_test.py
Adds the citest and an agent for interacting with GCS with
pub/sub notifications configured, and observing triggered
pipelines that execute from the GCS events.
This assumes quite a lot of external bucket, topic, and Echo config
that isn't in place yet. The test parameters are all there to work
when supplied, however, and I have tested this quite a lot given
my GCS -> pub/sub configuration.
The point of this WIP is to see where I went off the reservation 
and bent the normal citest workflows for my use cases, and
how we can improve either citest or this implementation to
achieve the same goal.
=> feat(citest/pubsub): Adds GCS -> pubsub -> GAE citest.

dev/all_tests.yaml, dev/validate_bom__config.py, testing/citest/requirements.txt
@jtk54 
There are also a bunch of formating changes here to bring it mostly to 80 columns and use 4 space indents for continuing lines (which is the style used throughout).
The main gist here is to not require pubsub be configured and gate the pubsub test on pubsub being configured as is the pattern for all the other configurators.
=> fix(validate): only configure/run pub sub tests when pubsub is enabled

dev/buildtool/base_metrics.py, dev/buildtool/bom_commands.py, dev/buildtool/bom_scm.py, dev/buildtool/changelog_commands.py, dev/buildtool/config-template.yml, dev/buildtool/flow_build.sh, dev/buildtool/spinnaker_commands.py
This also changes publishing spinnaker to use changelog gists.
There is a process change here where the publish directly writes
the changelog entry to spinnaker.github.io, but takes the existing
gist URI as a parameter as discussed offline. This gist is assumed
to already be curated so no need for additional review step.
The push_changelog_to_gist introduced here is a new process step
where the changelog is uploaded to a separated volatile gist
(control outside this script) which is used offline while curating
the official changelog gist.
@jtk54 
@lwander
=> feat(buildtool): Write changelog gists

dev/buildtool/git_support.py, dev/buildtool/spinnaker_commands.py, unittest/buildtool/git_support_test.py
@lwander 
cherry-picked from master, this will tolerate exiting tags provided they are at the desired commit.
The assumption is that the repo was unchanged from before, though this will also handle the case of a failure in the middle of pushing release tags.
=> fix(buildtool): Dont tag unchaged repos

packer/init.aws.region
fix(aws/init): Adding missing '/' in meta-data AZ url
Availability zone meta-data endpoint will always return an empty response if the trailing / is missing.
=> fix(aws/init): Adding missing '/' in meta-data AZ url

testing/citest/tests/kube_v2_artifact_test.py, testing/citest/tests/kube_v2_smoke_test.py
This is for test writers to have an easier job of cleaning up orphaned test resources
=> test(provider/kubernetes): add owner label for cleanup

testing/citest/spinnaker_testing/kubernetes_manifests.py, testing/citest/tests/kube_v2_artifact_test.py
Since the cache may not have updated yet (OK) we just check that the
configmap was mounted and the pod is healthy.
=> fix(provider/kubernetes): fix versioned configmap name check

dev/validate_bom__config.py
A number of the intermittent failures observed in running our CI tests are due to Gate returing a 500 on /tasks/task_id because Hystrix did not have an available thread to use to query Orca.  As this is primarily a problem with requests being bursty rather than an overall throughput problem, adding a modest queue to the Hystrix config so that Gate can handle and recover from short bursts of queries.
=> fix(citest): Add queueing to gate Hystrix config

testing/citest/tests/kube_smoke_test.py
Removing extraneous reassignment of `builder`, which is making it a no-op.
=> fix(citest): Fix save daemonset pipeline test

codelabs/gke-source-to-prod/install/setup.sh
When running the codelab https://codelabs.developers.google.com/codelabs/cloud-spinnaker-kubernetes-cd/ I see this error: 
```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=master version "1.8.8-gke.0" is unsupported.
```
The codelab remains unusable after this, there's no recovery. 
This proposed fix takes the currently latest table gke version to fix that. 
After merging, the files on gs://gke-spinnaker-codelab/install.tgz would also need to get fixed.
=> BUGFIX: Update GKE version to 1.9.7-gke.3 for the codelab

dev/validate_bom__config.py
Some test failures, and the associated log timestamps, indicate that the machines running our tests may have a nontrivial time drift (on the order of hundreds of milliseconds).  To gather data on this, log the output of 'ntpq -p' before installing Spinnaker.
=> fix(validate): Log ntp time synchronization of instances

codelabs/cicd-k8s-best-practice/app/scripts/build-image.sh, codelabs/gke-source-to-prod/services/backend/build.sh, codelabs/gke-source-to-prod/services/frontend/build.sh, dev/buildtool/container_commands.py, spinbot/Makefile
The 'gcloud container builds' command group has been renamed to 'gcloud builds' as of Google Cloud SDK 210.0.0. The old commands are deprecated and will be removed in a future release; update
the calls in Spinnaker to account for this change.
=> chore(build): Update gcloud build commands

dev/validate_bom__config.py
A number of the intermittent failures observed in running our CI tests are due to Front50 hitting a Hystrix circuit breaker when trying to fetch newly-created applications from cloud storage. We fixed a similar
issue in gate by adding queueing to the Hystrix config; do the same for front50, and also increase the queue size to give us a bit more buffer (as we send ~20 requests to create an application at the start of the tests). As this is primarily an issue with burstiness and not throughput, leaving the thread pool size at the default for now.
=> fix(citest): Add queueing to front50 Hystrix config

testing/citest/tests/bake_and_deploy_test.py
In the bake and deploy test, we create a pipeline, wait for front50 to confirm it exists, then try to trigger the pipeline.  This sometimes fails, because it can take up to 10 seconds for Echo to cache the new pipeline, and trying to trigger it during this time will be a no-op.
=> fix(citest): Fix race condition in triggering pipeline

testing/citest/tests/google_server_group_test.py
When resizing a server group, Spinnaker reports success when the new instance is observed. Our test cases are actually testing that the instance group is reporting the new size, which can lag the instance actually appearing. Increase the amount of time we wait for the instance group to report its new size to reduce intermittent failures.
=> fix(citest): Increase timeout for resize server group

testing/citest/tests/kube_v2_artifact_test.py, testing/citest/tests/kube_v2_helm_test.py, testing/citest/tests/kube_v2_smoke_test.py
A few of the kube v2 tests use a status class of SynchronousHttpOperationStatus when sending a request to trigger a pipeline; this causes the test to return success immediately and move on to testing the contract condition. We should remove this and fall back on the default (GateTaskStatus) which will poll for completion of the pipeline before trying to verify the contract.
=> fix(citest): Fix operation polling in kube v2 tests

testing/citest/tests/google_server_group_test.py
Looks like the timeout added in PR #3171 was not enough; let's extend to 10 minutes to reduce test flakiness.
=> fix(citest): Further increase timeout for resize server group

dev/all_tests.yaml, dev/validate_bom__test.py
We currently use the same Jenkins job for all of our CI tests, which means that sometimes the GKE tests are triggering pipelines in the GCE tests (and vice versa).  Use a different Jenkins job for each platform to avoid these issues.
=> fix(citest): Use a different Jenkins job for each test

dev/buildtool/changelog_commands.py
#3099 removed an extraneous h1, and also changed the version displayed at the top of the [changelog page](https://www.spinnaker.io/community/releases/versions/1-8-5-changelog) so that it only shows major.minor, because the page actually contains all the point releases under that major minor.
A side effect was that the version listing under [Latest stable](https://www.spinnaker.io/community/releases/versions/#latest-stable) also now only showed major.minor, in contrast with earlier releases also shown on page. 
This should fix it.
=> chore(build): Restores fullly-qualified version to "Latest Stable" list

solutions/kayenta/README.md
The tutorial is currently providing two ways of creating
the "Automated Canary Deploy": with the GUI (the main way,
where the reader learns the most), and with the CLI (backup,
in the case the reader messes up their config).
The editors are asking to move the backup path outside of
the main tutorial document. So I'm putting it here, in the
README, with the commands needed to create the 2 other pipelines.
cc @lwander
=> docs(kayenta-tutorial): Add the commands needed to run the kayenta tutorial

dev/validate_bom__config.py
We use a lot of GCE operation quota when running multiple tests concurrently.  As our tests only deploy to US regions, limit the configured Google account to only poll US regions to reduce our quota usage.
=> fix(citest): Limit polling to US regions

dev/validate_bom__config.py
We use a lot of GCE operation quota when running multiple tests concurrently.  As our tests only deploy to US regions, limit the configured Google account to only poll US regions to reduce our quota usage.
=> fix(citest): Limit polling to US regions (#3233)

dev/buildtool/debian_commands.py, dev/buildtool/ga-defaults.yml, dev/buildtool/gradle_support.py
We get intermittent failures in our build scripts because we publish debians to Bintray asynchronously, but later build steps expect these debians to be present. Change the publish call to be synchronous.
=> fix(build): Publish debians to Bintray synchronously

testing/citest/tests/appengine_gcs_pubsub_test.py, testing/citest/tests/bake_and_deploy_test.py
Also initialize class variable for pub/sub test to avoid NPE.
=> fix(citest): Increase operation timeouts for bake and deploy.

dev/buildtool/changelog_commands.py
Example title: `Version 1.9.3` instead of `Version 1.9`
=> fix(changelog): Fix changelog title to the right version.

dev/validate_bom__config.py, testing/citest/spinnaker_testing/gcs_pubsub_trigger_agent.py
Needs a bit more time to wait for the GAE pub/sub deploy pipeline to complete, 1 minute is too short. Also adds debug logging for bucket cleanup in validation. @dibyom FYI.
=> Pipeline wait

approvers.md
Previously had approver access prior to governance; meets criteria.
=> chore(*) add @maggieneterval to list of approvers

dev/buildtool/debian_commands.py
Should fix our nightly build failing to find the `candidate` task
=> fix(builds): Adds composite build flag to buildtool to include nebula

sponnet/demo/demo.jsonnet, sponnet/pipeline.libsonnet
RE: #3456 
Add jenkins stage
Add artifact option for deploy manifest
Add notifications
Add stage timeout
Add moniker
Add expectedArtifacts
Add triggers (docker and git only) constraints TODO
Notes:
The `jsonnet fmt` function is responsible for a most of the changes to pre-existing lines.
Inheritance using a sleek per app `appname.jsonnet` is not catered to here and subject to outcomes from the design doc on MPT v2, future PR's, etc.
Questions:
1. camelCase for variables and functions is common in other projects like Prometheus, Databricks. I'm tempted to change `deploy_manifest` etc. Thoughts?
=> feat(sponnet): extend pipeline library

testing/citest/spinnaker_testing/gcs_pubsub_trigger_agent.py, testing/citest/spinnaker_testing/spinnaker.py, testing/citest/tests/appengine_gcs_pubsub_test.py
The appengine tests currently only request succeeded pipelines from Gate, so there is no information in the logs if the pipeline fails.
=> fix(citest): Log pipeline status in appengine tests

sponnet/demo/demo.jsonnet, sponnet/pipeline.libsonnet
- Style: camelCase stage types and demo.jsonnet variables.
- Add additional artifact types.
- Add Kubernetes FindArtifactsFromResource stage
- fix Kubernetes DeployManifest stage correctly sets source artifact or text
based on whether artifact supplied or not.
- Extend Jenkins stage - add properties file and configuration options
- Extend Wait stage - add custom skip message
- Add pipeline stage
- Add Wercker stage, untested as don't have access to a Wercker install.
Picked up some missing configuration options from initial stage add.
Moving on now to putting into use internally. Will come back to add more missing stages and options 
in a future PR later.
=> feat(sponnet): camelCase, additional artifacts and stages

sponnet/application.libsonnet, sponnet/demo/README.md, sponnet/demo/demo-app.jsonnet, sponnet/demo/demo-pipeline.jsonnet, sponnet/pipeline.libsonnet
Fixes:
Manual judgment stage fix to match Spinnaker locality naming or typo? (judgment not judgement) and add input value array.
Add Pipeline ID required for `spin` CLI to save pipeline. This has come up in slack channels.
```
$ jsonnet demo.jsonnet > demo.json && spin pipeline save --file demo.json
Required pipeline key 'id' missing...
```
Features:
Refactor notifications to support Manual Judgment stage notifications
Add Check Preconditions stage
Add additional stage execution options. Time Window is basic.
Add additional pipeline options
Add ability to create Applications
Update README.
Verified app and pipeline save with `spin` CLI per updated README.md instructions and both look ok in Deck.
Demo pipeline has become quite large and could be pared back a bit.
In practice one refactors …
=> feat(sponnet): Additional stages, execution options, application support, fixes

testing/citest/tests/bake_and_deploy_test.py
Turns out the 3rd argument is required.
=> fix(validation): Fix args list.

testing/citest/tests/bake_and_deploy_test.py
Inspired by [Matt's branch](https://github.com/duftler/spinnaker/commit/4fff510ac42251245161df757844e0ec3fb3fcc4).
=> fix(bake_and_deploy): Move image cleanup to disable/destroy.

spinbot/policy/stale_issue_policy.py
Allows spinbot to ignore stale/to-be-closed behavior on issues with this label.
=> feat(spinbot): no-lifecycle label support

spinbot/event/master_branch_pull_request_handler.py, spinbot/event/release_branch_pull_request_handler.py, spinbot/gh/__init__.py, spinbot/gh/conventions.py
Previously the commit messages included the commit bodies, mangling the
message written by spinnaker bot.
(hopefully this will be demonstrated here)
=> feat(spinbot): improve formatting of commit messages

solutions/bluegreen/README.md, solutions/bluegreen/app/Dockerfile, solutions/bluegreen/app/main.go, solutions/bluegreen/manifests/hellosvc.yaml, solutions/bluegreen/manifests/replicaset-v1.yaml, solutions/bluegreen/pipelines/pipeline.json
Added a blue-green deployment sample to the solutions/ directory. Supplements [the existing doc](https://www.spinnaker.io/guides/user/kubernetes-v2/traffic-management/#configure-the-disable-stage) for the Disable (Manifest) stage.  
**Sample includes**:
- `app/` - small Golang webserver, with a Dockerfile  
- `manifests/` - Kubernetes initial ReplicaSet  
- `pipeline/` - JSON, with 3 stages:
1. Deploy (Manifest) - deploy v2 ReplicaSet 
2. Disable (Manifest) - stop sending traffic to v1  
3. Scale (Maniefst) - scale v1 replicas from 3 down to 1
=> Adds blue-green deployment solution

sponnet/pipeline.libsonnet
Artifacts are not displayed properly on Deck because pipeline.libsonnet doesn't have 'kind' attribute in Artifact.
This PR adds 'kind' attribute to Artifact in pipeline.libsonnet.
close: #3740
=> fix(sponnet) Add kind attribute to Artifact

google/release/gradle_cache_base_image.docker
The 'java' docker repo has been deprecated and not maintained since the end of 2016 in favor of the 'openjdk' repo.
The old ones were using openjdk as well, so that's not a change, just the repo. This also makes the base debian image more modern (stretch instead of jesse).
=> chore(build): Bump gradle_cache base image

solutions/kayenta/README.md, solutions/kayenta/ci/scripts/first-deployment.sh, solutions/kayenta/ci/scripts/setup.sh
This is for an update of the [kayenta tutorial](https://cloud.google.com/solutions/automated-canary-analysis-kubernetes-engine-spinnaker) to use Spinnaker 1.12.
=> Update kayenta tutorial for Spinnaker 1.12

.github/ISSUE_TEMPLATE.md
Whenever somebody forgets to delete the issue template, this pings all the @ mentions.  Propose putting the mention in `backticks` to avoid the unintended ping.
=> chore(ISSUE_TEMPLATE): Put @ mentions in backticks

testing/citest/tests/appengine_smoke_test.py
This is to allow AppEngine smoke tests to pass even if no default version had been deployed prior to the test run.
=> fix(appengine): Deploy default app engine version if no version exists.

sponnet/demo/demo-pipeline.jsonnet, sponnet/pipeline.libsonnet
Per: https://github.com/spinnaker/orca/pull/2761
Notes:
1.  Haven't added `evaluateOverrideExpressions` option to Bake Manifest stage. See Helm PR here: https://github.com/spinnaker/spinnaker/pull/3811
2. Added `withSkipExpressionEvaluation()` to `deployManifest()` in a way that could be used for artifact or text manifests. 
I can move it to an flag in `withManifestArtifact(artifact):: self + { <here> }`  if text manifests are fundamentally different.
Not sure if it's a `no-op` for text manifests if set to `true`. 
@maggieneterval would you mind advising?
Tested via:
1. `spin` CLI submitting `demo-pipeline.jsonnet` to Spinnaker and verifying in Deck
2. Our internal sponnet pipelines now all default to true and have been run.
=> feat(sponnet): Add skip eval SPeL to Deploy Manifest

codelabs/gke-source-to-prod/install/setup.sh
It prints out a big warning about being deprecated when you do this.
https://cloud.google.com/container-registry/docs/support/deprecation-notices#gcloud-docker
=> fix(codelab): Don't use `gcloud docker` in the GKE codelab.

testing/citest/README.md
There were several places where links weren't showing up because the link's text
and its URL were on separate lines. I just ran the whole thing through the 
(internal) `mdformat` tool to fix that.
It also justified all the paragraphs to 80 characters. But I had to paste back 
in most of the tables because our internal markdown engine has more table 
features than Github.
=> docs(citest): reformat README.md

dev/validate_bom__config.py
Fixes #3349
Gcloud is not in the path by default for systemd services in ubuntu 18.04. In order to allow appengine to still work, pass in the path to gcloud to the appengine provider.
=> fix(appengine): Add gcloud path to appengine config for localdebian

sponnet/pipeline.libsonnet
Automated pipeline triggers can set permissions as below link,
however, pipeline.libsonnet can't set permissions.
This commit adds permissions settings to pipeline.libssonet.
Close: #4327
=> feat(sponnet): Add permissions to pipeline.libssonet

sponnet/pipeline.libsonnet
Since some functions had problems, undoRolloutManifest couldn't make a JSON.
This PR fixes those problems.
=> fix(sponnet): fix functions of undoRolloutManifest at pipeline.libsonnet

dev/buildtool/hal_support.py
We're accessing the response variable in the catch block, where it doesn't exist, which throws a python error instead of reporting the actual error that occurred.
=> fix(build): Fix error message on halyard error

sponnet/pipeline.libsonnet
Github trigger was missing the secret(for the web-hook) and expected artifact.
These parameters are required when following this documentation.
https://www.spinnaker.io/guides/user/pipeline/triggers/github/#configure-the-github-trigger
Bug: https://github.com/spinnaker/spinnaker/issues/4653
Signed-off-by: David O'Dell <dave@helix.re>
=> feat(sponnet) added secret and expected artifact to github trigger

.travis.yml
Travis builds are failing with the wrong distro, see this [PR](https://github.com/spinnaker/spinnaker/pull/4729) with a failed build.
=> fix(buildtool): Set trusty dist for travis

sponnet/application.libsonnet, sponnet/demo/demo-app-gce.jsonnet
Per https://github.com/spinnaker/orca/blob/master/orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/model/Application.groovy#L40, cloudProviders should be a string, not an array.
I'm getting this error when I try to save an application generated from sponnet:
```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.netflix.spinnaker.orca.front50.model.Application["cloudProviders"])
at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
at …
```
=> fix(sponnet): fix existing and add missing application attributes

dev/buildtool/cloudbuild.yml, dev/buildtool/config-template.yml, dev/buildtool/container_commands.py
* Now tagging the images with `version-variant` but left the existing `version` tag on the `slim` image to make it backward compatible with halyard. The slim image is the only one with 2 tags: `version` and `version-slim`.
* Moved any service-specific build logic to their Dockerfiles, leaving the `cloudbuild.yaml` file fully generic so it could be stored in this repo as a single template.
* Expecting every service to have `Dockerfile.compile`, `Dockerfile.slim` and `Dockerfile.ubuntu`
* Removed config parameters from `config-template.yml` for features that have been removed in a previous commit.
=> feat(buildtool): Ubuntu image variant support

dev/buildtool/subprocess_support.py, dev/validate_bom__deploy.py
By default, it was getting joined with stdout and then we tried to parse
it as JSON, which didn't work since it isn't, in fact, JSON.
My test run didn't actually have any of this stderr output, so I can't
say for certain that it actually works. But it doesn't make the
no-stderr case fail, so we're at least no worse off.
=> fix(buildtool): log stderr of `gcloud compute instances describe`

sponnet/pipeline.libsonnet
I wasn't sure whether to add it to the demo.
Example with GCP:
```
pipeline.triggers.pubsub("the-trigger", "google", "subscription")
.addAttributeConstraints("status", "SUCCESS")
.addPayloadConstraints("buildTriggerId", "default-github-checks")
.withExpectedArtifacts([my_expected_docker_image_artifact])
;
```
=> feat(sponnet): Added support for pubsub triggers

sponnet/pipeline.libsonnet
Note that this only adds support for `cloudbuild.yml` structures passed to a function. Not structures coming from an artifact.
=> feat(sponnet): Add support for Google Cloud Build stages

sponnet/pipeline.libsonnet
I'm porting the JSON I get Deck so I can replicate the JSON document with Sponnet, and I noticed that Deck isn't giving me a cluster in the moniker field, so I'm making it optional.
=> feat(sponnet): Make cluster optional in moniker

sponnet/pipeline.libsonnet
BREAKING CHANGE: `findArtifactFromExecution().withExecutionOptions()` used to work with an array of `executionOptions` but it now requires an object.
=> fix(sponnet): Output valid executionOptions for Find Artifact stage

testing/citest/tests/google_server_group_test.py
The Google zonal and regional server group tests have a step to clone an existing server group by sending a clone request to gate. This logic is wrapped in a retry loop to prevent flakiness (as added in a35fdacc3d77403916558d94e038fe036b6c7caf).
Given that cloning a server group is a non-idempotent mutating operation, we should not be retrying it if it fails, as this will leave the system in an unknown state. (In a recent run of the tests, we ended up cloning the server group twice, leading to downstream failures that were hard to trace back to this particular test.)
Remove the retry logic from this test; if this does cause flakiness, it will at least be easier to trace the test that is failing and we can then investigate how to fix the flakiness.
=> fix(citest): Don't retry server group cloning

.github/PULL_REQUEST_TEMPLATE.md
GitHub doesn't allow folks from outside the `spinnaker` org to add org-specific group mentions, so we're instructing people to do something they aren't allowed to do.
=> chore(github): Remove non-functional at-mention

.github/ISSUE_TEMPLATE.md
GitHub doesn't allow folks from outside the `spinnaker` org to add org-specific group mentions, so we're instructing people to do something they aren't allowed to do.
=> chore(ISSUE_TEMPLATE): Remove UX at mention

dev/buildtool/git_support.py, dev/buildtool/halyard_commands.py, dev/buildtool/scm.py
I noticed that `Push_RawChangelogGist` is re-cloning repos every time it runs (both the source repository repos and the gist which is technically also a repo).  There is logic to check if the repos have already been cloned and if so just fetch updates, but that logic is not running as we're deleting all these repos every time the script runs.  Removing the step to delete these (which is not a code change, but just a Jenkins config change) caused us to hit a bug where it doesn't realize that the repo on disk is the same repo it's considering cloning (as the one on disk has an ssh origin and the one it's considering cloning has an https origin).  This PR fixes said bug, allowing us to remove the step in the Jenkins job that deletes all these repos.
The hope is that by reducing the amount of …
=> fix(build): Fix repository comparison to handle ssh/https difference

dev/buildtool/bom_scm.py, dev/buildtool/branch_scm.py, dev/buildtool/git_support.py, dev/buildtool/scm.py
In a few places, we check if a directory containing a git repo already exists. If the directory does not exist, we clone the repo into the directory and check out the expected commit; if the directory does exist, we verify that it is at the expected commit.
This effectively makes it impossible to re-use directories, as there is no logic in the re-use path to fetch changes and check out the expected commit. Add this logic; now, if a the directory exists we'll attempt to fetch origin and check out the expected commit before moving on rather than expecting it to already be at the commit we want.
=> fix(build): Allow re-use of git directories

testing/citest/tests/bake_and_deploy_test.py
In a number of places in the tests, we create a new pipeline by sending a POST to gate, then immediately poll to check that the pipeline is there.  While in principle the immediate call should show the pipeline as existing (as there is logic in front50 to provide read-after-write consistency) there are a couple of edge cases.
Most of the places we try to read a new pipeline allow a few retries to give the pipeline to show up, but a few don't.  Add retries to the remaining places to reduce flakiness.
=> fix(citest): Add brief retry when validating a new pipeline

dev/validate_bom__test.py
We currently time out if a service takes more than 5 minutes to start. Some of the services currently take on the order of 5 minutes to start (at least in some of the citest environments), which is leading to flakiness.
Let's add a safety factor of 2, and give the services 10 minutes to start before we time out. (Ideally they would start faster, but let's at least not have flaky tests in the meantime.) This won't decrease the best-case time as the tests start when all the services are ready, even if it's shorter than the max time.
=> fix(citest): Allow longer service startup time

sponnet/pipeline.libsonnet
runJobManifest:
.withManifestArtifact(artifact) - reference manifestArtifactAccount from provided artefact
.withManifestText(text) - allow define manifest as text input
=> (fix) sponnet - runJobManifest stage

sponnet/demo/demo-pipeline.jsonnet
When attempting to run through the sponnet example you'll encounter this error recently introduced a recent fix and commit 62be7e5d874d903ef5152f7b0d6259ef33a47582. 
```
$ jsonnet demo-pipeline.jsonnet > demo-pipeline.json && spin pipeline save --file demo-pipeline.json
RUNTIME ERROR: function parameter name not bound in call.
demo-pipeline.jsonnet:(169:35)-(173:83)	thunk <findArtifactsFromResource>
demo-pipeline.jsonnet:211:169-194	thunk <array_element>
../pipeline.libsonnet:16:79-85	object <anonymous>
During manifestation
```
This PR fixes it.
```
$ jsonnet demo-pipeline.jsonnet > demo-pipeline.json && spin pipeline save --file demo-pipeline.json
Pipeline save succeeded
```
@Mahito  @louisjimenez
=> fix(jsonnet): Fix parameter for withManifestName fn

dev/validate_bom__config.py
@ttomsu @maggieneterval This temporarily disables the telemetry service for the build. Once it's determined why the service being unavailable causes echo to fail on the GKE provider, it can be turned back on.
=> turn off telemetry to test build

solutions/kayenta/pipelines/canary-deploy.json
This change adds mode: label to the canary-deploy.json pipeline.  Without the mode being specified, Spinnaker doesn't use the label selectors as desired in the delete manifest stages.
=> fix: adding in missing mode attribute on delete manifest stages

spinbot/policy/stale_issue_policy.py
After conferring with the Spinnaker SIG leads, we think it will help us curate a healthy backlog of beginner-friendly issues if they are never tagged as stale and auto-closed by Spinnakerbot.
=> feat(spinbot): do not mark beginner-friendly issues as stale

sponnet/pipeline.libsonnet
Adds fields for `namespaceOverride` to deployManifest at pipeline.libsonnet.
Ref. feat(provider/kubernetes): namespace deployManifest
https://github.com/spinnaker/deck/pull/7016
=> feat(sponnet): Add fields for namespaceOverride to deployManifest

sponnet/pipeline.libsonnet
"cloudProvider" parameter is required for using type ClusterSize in Check Preconditions stage with Kubernetes V2 provider.
```
...
{
"name": "Check Cluster Size",
"preconditions": [
{
"cloudProvider": "kubernetes",  # required
"context": {
"cluster": "replicaSet myapp",
"comparison": "==",
"credentials": "mycluster",
"expected": 0,
"moniker": {
"app": "myapp",
"cluster": "replicaSet myapp"
},
"regions": [
"mynamespace"
]
},
"failPipeline": false,
"type": "clusterSize"
}
],
"refId": "Check Cluster Size",
"requisiteStageRefIds": [ ],
"type": "checkPreconditions"
},
...
```
=> feat(sponnet): Support Kubernetes V2 provider in Check Preconditions stage

sponnet/demo/demo-v2-mpt.jsonnet
Fixes owner in mpt metadata and the following error when trying to run the demo:
```
$ jsonnet demo-v2-mpt.jsonnet 
RUNTIME ERROR: function parameter name not bound in call.
demo-v2-mpt.jsonnet:(146:35)-(150:83)	thunk <findArtifactsFromResource>
demo-v2-mpt.jsonnet:169:134-159	thunk <array_element>
../pipeline.libsonnet:16:79-85	object <anonymous>
../v2PipelineTemplate.libsonnet:10:49-57	object <anonymous>
During manifestation
```
@louisjimenez
=> fix(sponnet): fix issues in demo-v2-mpt.jsonnet

sponnet/pipeline.libsonnet
```jsonnet
local checkStage = sponnet.stages
.checkPreconditions("check")
.withStageStatus("foo", "SUCCEEDED", true)
.withStageStatus("bar", "FAILED", false);
```
generates 
```json
{
"checkStage": {
"name": "check",
"preconditions": [
{
"context": {
"stageName": "foo",
"stageStatus": "SUCCEEDED"
},
"failPipeline": true,
"type": "stageStatus"
},
{
"context": {
"stageName": "bar",
"stageStatus": "FAILED"
},
"failPipeline": false,
"type": "stageStatus"
}
],
"refId": "check",
"requisiteStageRefIds": [ ],
"type": "checkPreconditions"
}
}
```
=> feat(sponnet): add withStageStatus for checkPreconditions stage

sponnet/pipeline.libsonnet
Using the same pattern as the overrides in the bake stage with an additional `addPipelineParamter(key, value` function.
code 
```jsonnet
local pipelineStage = sponnet.stages
.pipeline("run-pipeline")
.withApplication("myApp")
.withPipeline("other-pipeline")
.withWaitForCompletion(true)
.withPipelineParameters({"foo": "bar"},)
.addPipelineParameter("baz", "stuff");
```
generates
```json
{
"pipelineStage": {
"application": "foo",
"failPipeline": true,
"name": "run-pipeline",
"pipeline": "foo-other-pipeline",
"pipelineParameters": {
"baz": "stuff",
"foo": "bar"
},
"refId": "run-pipeline",
"requisiteStageRefIds": [ ],
"type": "pipeline",
"waitForCompletion": true
}
}
```
=> feat(sponnet): add pipelineParameters for the pipeline stage

dev/validate_bom__config.py
Basically reverts https://github.com/spinnaker/spinnaker/pull/5023
Changes in Echo should make this safe to turn back on: https://github.com/spinnaker/echo/pull/706
Fixes https://github.com/spinnaker/spinnaker/issues/5144
=> feat(stats): Reenable stats in build process

testing/citest/tests/bake_and_deploy_test.py
Testing now, but pretty sure this caused a failure last night (which also got hung, but I think that's still a separate issue).
=> fix(tests): Turns out we do actually need 'cloudProviderType'

dev/buildtool/changelog_commands.py
Currently https://www.spinnaker.io/community/releases/versions/ displays the date with "+0000" (UTC) when in fact the time is in Eastern. This will make the frontmatter explicitly UTC.
=> fix(release): Explicitly use UTC time in release changelog

dev/build_google_image_functions.sh, dev/build_halyard_image.sh, dev/create_google_dev_vm.py, dev/validate-config-template.yml, dev/validate_bom__deploy.py, testing/citest/tests/bake_and_deploy_test.py
Not 100% sure this will fix the failing builds, but I think it's one of the reasons bake_and_deploy is failing
=> fix(bakery): Use xenial base image for GCE since trusty was deprecated

dev/buildtool/inspection_commands.py
Used in `Admin_AuditBoms` and transitively in `Admin_DeleteObsoleteArtifacts` Jenkins jobs, which I am going to run to reduce the data in the `halconfig` bucket
=> fix(boms): Do not including -validated BOMs in candidates to prune

dev/buildtool/cloudbuild-build-java8.yml, dev/buildtool/cloudbuild-tag-java8.yml, dev/buildtool/container_commands.py
If a `Dockerfile.java8` file exists, it (along with `Dockerfile.ubuntu-java8`) will be built, otherwise the standard `slim` and `ubuntu` containers will be tagged with `java8` suffixes.
This allows for a new `JAVA8` and `UBUNTU_JAVA8` `imageVariant` to be added to Halyard.
Once the builds are fully moved to Java 11, this PR can be reverted completely.
=> feat(build): Add support for java8 containers

dev/buildtool/cloudbuild-build-java8.yml, dev/buildtool/cloudbuild-tag-java8.yml
This removes the need for the `docker tag` build steps.
Had this lying around from an aborted attempt at something else, but it's worth checking in on its own...
=> refactor(release): apply multiple tags at build time

.github/workflows/stale-issues.yml
Setting DRY_RUN: true to see how it behaves. In theory, we may be able to turn down github.com/spinnaker/spinnakerbot after this.
tag: https://github.com/spinnaker/spinnaker/issues/5443
=> feat(spinbot): Replace the bulk of spinbot's issue labeling with a GHActions

.github/workflows/build-cop-rotation.yml
It appears assigning a team as a reviewer needs increased permissions, see https://github.com/peter-evans/create-pull-request/issues/155
Adding a bit more detail to the other fields.
=> fix(build-cop): Use PAT in order to assign a team reviewer

.github/workflows/build-cop-rotation.yml
v2 was failing because it uses deprecated actions. (It seems to still create the pull requests, but mails out errors.)
Doesn't look like we need to change anything for the v3 upgrade:
https://github.com/peter-evans/create-pull-request/blob/master/docs/updating.md#updating-from-v2-to-v3
=> Update to create-pull-request v3

README.adoc
This pull request updates the spinnaker new user experience by fixing the links within the project readme which render as 404 on the destination site. No new features have been added. This PR does not have an associated github issue.
=> docs(readme.md): updated 404s in readme links

.github/ISSUE_TEMPLATE.md
Remove the instruction to assign a label since that is not an option that contributors will have access to.
This PR is a response to #6155
=> fix: Update ISSUE_TEMPLATE.md to remove outdated instructions

.github/workflows/clean-untagged-images.yml
In order to keeps costs under control, want to delete untagged images older than 48 hours. 
More info on GCR Cleaner can be found here: [https://github.com/GoogleCloudPlatform/gcr-cleaner/](https://github.com/GoogleCloudPlatform/gcr-cleaner/)
I have not tested this out via a GHA, but have done some dry runs locally. I've added the dry-run flag so that we can test this out on GHA and evaluate the output, before removing the dry-run flag
=> feat(gha): gha to delete untagged images older than 48 hours

build.gradle, spinnaker-gradle-project/spinnaker-project-plugin/build.gradle, spinnaker-gradle-project/spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/nexus/NexusPublishPlugin.groovy
Plumbs the `publishToNexus` and related tasks up to the composite root.
=> fix(build): Fix Nexus library publishing

deck-kayenta/package.json, deck-kayenta/src/kayenta/metricStore/datadog/index.ts
Enable using query templates with Datadog metric store. Previously this option was available only for stackdriver and prometheus, so the user has to modify the JSON directly in order to use additional tags or metric equations with Datadog metric store.
=> feat(kayenta): enable using template for Datadog metric store

echo/echo-rest/src/test/java/com/netflix/spinnaker/echo/events/RestEventListenerTest.java
- Though the tests don't fail, error messages like the following are appearing during the build due to missing mock responses:
```
java.lang.NullPointerException: Cannot invoke "retrofit2.Call.execute()" because "call" is null
at com.netflix.spinnaker.kork.retrofit.Retrofit2SyncCall.executeCall(Retrofit2SyncCall.java:47) ~[kork-retrofit-7.254.0.jar:7.254.0]
at com.netflix.spinnaker.kork.retrofit.Retrofit2SyncCall.execute(Retrofit2SyncCall.java:34) ~[kork-retrofit-7.254.0.jar:7.254.0]
```
- This PR addresses the issue by providing necessary mocking when retrofit2 calls are made.
=> fix(rest): fix the retrofit2 error messages coming in the test logs of RestEventListenerTest

halyard/halyard-config/halyard-config.gradle, halyard/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidator.java, halyard/halyard-config/src/test/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidatorTest.java
- After upgrading clouddriver to retrofit2, clouddriver's DockerRegistryNamedAccountCredentials used in DockerRegistryAccountValidator needed to be updated without which the following error occurs when a docker registry account is added through hal command. 
```
Validation in default.provider.dockerRegistry.dockerhub:
! ERROR Unable to fetch tags from the docker repository:
library/alpine, Cannot invoke method getService() on null object
? Can the provided user access this repository?
! ERROR Unable to fetch tags from the docker repository:
xxxxx/yyyyyy, Cannot invoke method getService() on null object
? Can the provided user access this repository?
```
- This PR addresses the above  issue but since halyard is not upgraded to retrofit2 yet, the fix provided is a temporary one, …
=> fix(config): fix the issue of halyard failing to add docker registry account

igor-core/src/test/java/com/netflix/spinnaker/igor/history/EchoServiceTest.java, igor/igor-core/igor-core.gradle, igor/igor-core/src/main/java/com/netflix/spinnaker/igor/history/EchoConverterFactory.java, igor/igor-core/src/main/java/com/netflix/spinnaker/igor/history/EchoService.java, igor/igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/EchoConfig.groovy, igor/igor-web/src/test/java/com/netflix/spinnaker/igor/nexus/NexusEventPosterTest.java
- It was observed that the igor was throwing the following error related to retrofit2 serialization. This PR addresses the issue by replacing the @Body type from an abstract `Event` type to `Map<String, Object>` and make changes accordingly at all the required places.
- Added a test to demonstrate the issue. 
```
Caused by: java.lang.IllegalArgumentException: Unable to convert GenericBuildEvent(details={type=build, source=igor}, content=GenericBuildContent(project=GenericProject(name=spinnaker, lastBuild=GenericBuild(building=false, fullDisplayName=null, name=null, number=0, duration=null, timestamp=null, result=null, artifacts=null, testResults=null, url=null, id=null, genericGitRevisions=null, properties=null)), master=IgorHealthCheck, type=null)) to RequestBody (parameter #1)
for …
```
=> fix(retrofit2): fix the issue of retrofit2 being unable to convert the Event object to RequestBody.

clouddriver/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy, clouddriver/clouddriver-docker/src/test/java/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClientTest.java
- A docker registry when responding with next link to query for catalog repositories or tags, it is expected to send two query parameters : 1. `n` - number of items per page and 2. `last` - last item rendered in the current response. But Azure Container Registry was also sending one more query parameter (`orderby`) with no value which is causing the failure while parsing the `next` link.  https://github.com/spinnaker/spinnaker/issues/7065
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
...
at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$_parseForQueryParams_closure20.doCall(DockerRegistryClient.groovy:502) ~[clouddriver-docker-2025.0.0.jar:2025.0.0]
```
- This PR addresses the issue by accepting blank value for a …
=> fix(docker): fix the issue of fetching docker images

igor/igor-web/igor-web.gradle, igor/igor-web/src/main/java/com/netflix/spinnaker/igor/config/HelmConverterFactory.java, igor/igor-web/src/test/java/com/netflix/spinnaker/igor/helm/accounts/HelmAccountsServiceTest.java
- When Igor was trying to call Clouddriver to fetch helm accounts, presence of additional field(s) was causing SpinnakerConvertionException:
```
INFO 2025-05-15T23:30:38.603945402Z [resource.labels.containerName: igor] 2025-05-15 23:30:38.603 ERROR 1 --- [ scheduling-1] c.n.s.igor.helm.accounts.HelmAccounts : Failed to get list of Helm accounts
com.netflix.spinnaker.kork.retrofit.exceptions.SpinnakerConversionException: Failed to process response body: Unrecognized field "type" (class com.netflix.spinnaker.igor.helm.accounts.ArtifactAccount), not marked as ignorable (2 known properties: "types", "name"])
at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 38] (through reference chain: java.util.ArrayList[0]->com.netflix.spinnaker.igor.helm.accounts.ArtifactAccount["type"]) …
```
=> fix(web): fix HelmConverterFactory for deserialization error

deck-kayenta/package.json, deck-kayenta/src/kayenta/actions/creators.ts, deck-kayenta/src/kayenta/actions/index.ts, deck-kayenta/src/kayenta/canary.help.ts, deck-kayenta/src/kayenta/edit/editMetricModal.spec.tsx, deck-kayenta/src/kayenta/edit/editMetricModal.tsx, deck-kayenta/src/kayenta/reducers/selectedConfig.ts
Add outlier strategy field to the canary config modal, this config exists in Kayenta config schema [here](https://github.com/spinnaker/spinnaker/blob/93ea3ff5b9c804d727797e871101b679bd8b1595/kayenta/docs/canary-config.md#properties-7) but was not exposed in the modal when metric configuration is created/updated.
=> feat(kayenta): adding outlierStrategy field in metric config modal

.github/actions/spinnaker-release/dist/index.js, .github/actions/spinnaker-release/src/bom/bom.ts, .github/actions/spinnaker-release/src/bom/generate.ts, .github/actions/spinnaker-release/src/bom/service.ts, .github/actions/spinnaker-release/src/git/git.ts, .github/actions/spinnaker-release/src/versions.ts
The original implementation of BoM generation was designed around branch-build numbers (e.g. `clouddriver-2025.0-1`) - we were not rebuilding containers on release.  Later in the process, we elected to do that (e.g. `clouddriver-2025.0.1` - note the dot), and tag searching was then broken.  
The design was also meant to always take the latest version unless overridden, which has been improved to always use a release version as a reference point.  This makes it possible to regenerate an older BoM if needed.  This can be used to update the incorrect existing BoMs for `2025.0.1` and `2025.0.2`.
Example BoM produced by this change with input version `2025.0.2`:
```yaml
artifactSources:
debianRepository: https://us-apt.pkg.dev/projects/spinnaker-community
dockerRegistry: …
```
=> fix(build): Fix BoM generation against release tags

.github/actions/spinnaker-release/dist/index.js, .github/actions/spinnaker-release/package-lock.json, .github/actions/spinnaker-release/package.json, .github/actions/spinnaker-release/src/bom/generate.ts, .github/actions/spinnaker-release/src/bom/versionsDotYml.ts, .github/actions/update-monorepo/dist/index.js
This fixes a compatibility issue between monorepo tooling and buildtool.  Buildtool collapsed patch versions, but only tried to update the incoming version.  It also limited total releases to three, under the assumption that all releases were only represented by their latest patch in the version list.  
Monorepo tooling made an entry for every patch, which pushed all the older releases off the list when buildtool was consuming it.  This is now collapsed and sorted, and limited to three for compatibility.
This also adds in some hooks to update the top-level metadata whenever something is potentially mutated. 
Example versions.yml generated by this change:
```yaml
illegalVersions:
- reason: Broken apache config makes the UI unreachable
version: 1.2.0
- reason: UI does not load
version: …
```
=> fix(build): Limit versions.yml to three releases, and collapse patch versions

clouddriver/clouddriver-artifacts/src/integration/resources/clouddriver.yml, clouddriver/clouddriver-ecs/src/integration/resources/clouddriver.yml, clouddriver/clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/containers/KubernetesCluster.java, clouddriver/clouddriver-kubernetes/src/integration/resources/clouddriver.yml, front50/front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/SqlStorageServiceTests.kt, kork/kork-sql-test/src/main/java/com/netflix/spinnaker/kork/sql/test/SqlTestUtil.java, kork/kork-sql/src/test/java/com/netflix/spinnaker/kork/sql/config/TransactionIsolationMysqlTest.java
Before this, tests would fail because there's no arm docker image for mysql 5.7.22 nor 5.7.34 with errors like:
> Task :orca:orca-sql:test
```
MySqlPipelineExecutionRepositorySpec > initializationError FAILED
org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=mysql:5.7.34, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@41c1b23c)
at app//org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1364)
at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:359)
at app//org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
at …
```
=> chore(test): adjust test code to execute on arm

igor/igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/JenkinsClient.groovy, igor/igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.java, igor/igor-web/src/test/java/com/netflix/spinnaker/igor/jenkins/service/JenkinsServiceTest.java
- When a Jenkins job's build or buildWithParameters API is invoked, there won't be any response body(response code 201). But the Igor code responsible for handling the API response assumes a response body hence fails with the following error:
``` 
com.netflix.spinnaker.kork.retrofit.exceptions.SpinnakerConversionException: Failed to process response body: Unexpected EOF in prolog
at [row,col {unknown-source}]: [1,0]
at com.netflix.spinnaker.kork.retrofit.ErrorHandlingExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ErrorHandlingExecutorCallAdapterFactory.java:156) ~[kork-retrofit-2025.0.3.jar:2025.0.3]
at com.netflix.spinnaker.kork.retrofit.Retrofit2SyncCall.executeCall(Retrofit2SyncCall.java:47) ~[kork-retrofit-2025.0.3.jar:2025.0.3]
2
``` 
- This PR addresses the above issue by …
=> fix(igor-web): fix Jenkins job's build response handling issue

gate/gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy, gate/gate-web/src/main/java/com/netflix/spinnaker/gate/filters/ProvidedIdRequestFilter.java, gate/gate-web/src/main/java/com/netflix/spinnaker/gate/filters/ProvidedIdRequestFilterConfigurationProperties.java, gate/gate-web/src/test/java/com/netflix/spinnaker/gate/HeaderAuthTest.java, gate/gate-web/src/test/java/com/netflix/spinnaker/gate/HeaderAuthWiremockTest.java
enabled by setting provided-id-request-filter.enabled to true (default: false).
ProvidedIdRequestFilter is configured early enough in the filter chain so gate uses
X-SPINNAKER-REQUEST-ID and X-SPINNAKER-EXECUTION-ID headers from incoming http requests
when it makes downstream http requests (e.g. to fiat) during authentication.
=> fix(web): add ProvidedIdRequestFilter

front50/gradle.properties
Found duplicate entry for korkVersion in front50/gradle.properties. This PR fixes that.
=> fix(front50/korkversion): remove older duplicate entry of korkVersion

.github/workflows/spinnaker-gradle-project.yml, spinnaker-gradle-project/build.gradle, spinnaker-gradle-project/spinnaker-extensions/build.gradle.kts, spinnaker-gradle-project/spinnaker-project-plugin/build.gradle
- Publishing tasks are now exposed via the `spinnaker-gradle-project` composite, so they can be properly addressed from the root build
- Gradle plugins now have a required `description` field, so that is now set in the metadata
- Automatically publishes on `main` pushes to its subtree, which will produce a version like `main-1`
=> fix(build): Enable publishing for Gradle plugins

kork/kork-retrofit2/src/test/kotlin/com/netflix/spinnaker/kork/retrofit/Retrofit2ServiceProviderTest.kt
SpinnakerRetrofitInterceptor is for use with retrofit1.  It wasn't used in Retrofit2ServiceProviderTest.
=> refactor(retrofit2/test): remove unused code

kork/kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/RetrofitServiceFactory.java, kork/kork-retrofit/src/test/kotlin/com/netflix/spinnaker/kork/retrofit/RetrofitServiceProviderTest.kt, kork/kork-retrofit2/src/main/java/com/netflix/spinnaker/kork/retrofit/Retrofit2ServiceFactory.java, kork/kork-retrofit2/src/test/java/com/netflix/spinnaker/kork/retrofit/Retrofit2ServiceFactoryTest.java, kork/kork-web/src/main/java/com/netflix/spinnaker/config/DefaultServiceClientProvider.java, kork/kork-web/src/main/java/com/netflix/spinnaker/kork/client/ServiceClientFactory.java, kork/kork-web/src/main/java/com/netflix/spinnaker/kork/client/ServiceClientProvider.java, orca/orca-clouddriver/orca-clouddriver.gradle, orca/orca-retrofit/orca-retrofit.gradle
- With the introduction of `LegacySignatureCallAdapter` in https://github.com/spinnaker/spinnaker/pull/7088, the logic to verify whether the request is for retrofit2 client is no longer valid because the retrofit2 enabled API interface need not have method return types with Call wrapper.
- This PR addresses the issue by introducing the RetrofitVersion enum field in all the ServiceClientProvider.getService() calls. 
- Added a test to demonstrate the issue.
=> fix(retrofit2): fix a broken scenario related to LegacySignatureCallAdapter

kork/spinnaker-dependencies/spinnaker-dependencies.gradle
chore(dependency): bump tomcat from 9.0.83 to 9.0.107
Fixes tomcat CVEs. Most importantly CVE-2024-56337, CVE-2024-50379, CVE-2025-24813
=> chore(dependency): bump tomcat from 9.0.83 to 9.0.107

kork/kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/RetrofitServiceFactory.java, kork/kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/util/RetrofitUtils.java, orca/orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfiguration.java, orca/orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/config/EchoConfiguration.groovy, orca/orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/config/Front50Configuration.groovy, orca/orca-igor/orca-igor.gradle, orca/orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/config/IgorConfiguration.groovy, orca/orca-igor/src/test/java/com/netflix/spinnaker/orca/igor/BuildServiceTest.java, orca/orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/RetrofitConfiguration.groovy
- This PR addresses the issue - https://github.com/spinnaker/spinnaker/issues/7059#issuecomment-3003509067
- It is observed that the retrofit1 client is added with retrofit2 specific interceptors and this PR removes them.
- [RawOkHttpClientConfiguration.java](https://github.com/spinnaker/spinnaker/blob/release-2025.0.x/kork/kork-web/src/main/java/com/netflix/spinnaker/config/okhttp3/RawOkHttpClientConfiguration.java) is adding interceptors to a OkHttpClient which is then autowired in [DefaultOkHttpClientBuilderProvider.java](https://github.com/spinnaker/spinnaker/blob/release-2025.0.x/kork/kork-web/src/main/java/com/netflix/spinnaker/config/okhttp3/DefaultOkHttpClientBuilderProvider.java#L59) and getting to retrofit1 through [OkHttpClientProvider](https://github.com/spinnaker/spinnaker/blo …
=> fix(retrofit): fix retrofit1 client definition in kork

echo/echo-notifications/src/main/java/com/netflix/spinnaker/echo/googlechat/GoogleChatClient.java, echo/echo-notifications/src/main/java/com/netflix/spinnaker/echo/googlechat/GoogleChatNotificationService.java, echo/echo-notifications/src/main/java/com/netflix/spinnaker/echo/googlechat/GoogleChatService.java, echo/echo-notifications/src/test/java/com/netflix/spinnaker/echo/googlechat/GoogleChatClientTest.java
- This PR addressed the issue https://github.com/spinnaker/spinnaker/issues/7022
- The issue occurred because the partial webhook url which contains query parameters(after two terms separated by slashes) was being sent as path variable due to which incorrect encoding was happening. This used to work with retrofit1 but retrofit2 is strict in this regard.
- From the [google chat official documentation](https://developers.google.com/workspace/chat/quickstart/webhooks?utm_source=chatgpt.com#python_1), found the webhook url is of the form - https://chat.googleapis.com/v1/spaces/SPACE_ID/messages?key=KEY&token=TOKEN so based on this, fix is provided by separated the path and query parameters.
- Added a test to demonstrate the issue.
=> fix(googlechat): fix googlechat encoding issue

kork/spinnaker-dependencies/spinnaker-dependencies.gradle, orca/gradle/groovy.gradle, orca/gradle/spek.gradle, orca/gradle/spock.gradle
https://github.com/spinnaker/orca/pull/4566 that were apparently lost in the monorepo migration.
Without the junit-jupiter-engine dependency in orca/gradle/groovy.gradle, WebhookServiceTest doesn't run as part of
```
$ ./gradlew orca:orca-webhook:test
```
The addition of junit-bom to spinnaker-dependencies isn't a functional change.  spock-core brings it in even before this change, but now it's explicit, and matches what's in the [individual kork repo](https://github.com/spinnaker/kork/blob/a7b6fdea15ec2e98c80093947f194afb0ee552f3/spinnaker-dependencies/spinnaker-dependencies.gradle#L57).
=> chore(orca): restore changes from https://github.com/spinnaker/orca/pull/4566

clouddriver/clouddriver-web/clouddriver-web.gradle, clouddriver/clouddriver-web/src/main/java/com/netflix/spinnaker/clouddriver/controllers/CredentialsController.java, clouddriver/clouddriver-web/src/test/java/com/netflix/spinnaker/clouddriver/controllers/CredentialsControllerTest.java, orca/orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/DelegatingOortService.java, orca/orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/OortService.java, orca/orca-webhook/orca-webhook.gradle, orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookProperties.java, orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/pipeline/PreconfiguredWebhookStage.java, orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/pipeline/WebhookStage.java, orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/service/WebhookAccountProcessor.java, orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/service/WebhookService.java, orca/orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/pipeline/PreconfiguredWebhookStageSpec.groovy, orca/orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/pipeline/WebhookStageSpec.groovy, orca/orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/service/WebhookServiceSpec.groovy, orca/orca-webhook/src/test/java/com/netflix/spinnaker/orca/webhook/config/MtlsConfigurationTestBase.java, orca/orca-webhook/src/test/java/com/netflix/spinnaker/orca/webhook/config/WebhookConfigurationTest.java, orca/orca-webhook/src/test/java/com/netflix/spinnaker/orca/webhook/service/WebhookServiceTest.java
There are a series of changes here:
* feat(clouddriver/web): add an endpoint to fetch account details
* feat(orca/webhook): add new account property to webhook stages
* feat(orca/webhook): add webhook.validateAccount
* feat(orca/webhook): add WebhookAccountProcessor interface
with these orca config flags to control behavior:
* `webhook.requireAccount` (default: false). If true and the account property is not present (i.e. a non-empty string),
the stage fails.
* `webhook.validateAcount` (default: false). If true, and an account property is present, call clouddriver's GET /credentials/{account}/authorized endpoint to validate that the current user has permission to use the account.
The bigger picture here is that this is a new mechanism to help lock down webhook stages.  The addition of the …
=> feat(orca/webhook): add account property to webhook stages and introduce WebhookAccountProcessor interface

orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookConfiguration.java, orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookProperties.java, orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/util/WebhookLoggingEventListener.java, orca/orca-webhook/src/test/java/com/netflix/spinnaker/orca/webhook/config/WebhookConfigurationTest.java, orca/orca-webhook/src/test/resources/logback-test.xml
to get (potentially very verbose) information about every okhttp interaction related to webhooks.
Both default to false. Log messages provided by WebhookLoggingEventListener when enabled.
The goal is to make it easier to troubleshoot when webhook stages are failing.
=> feat(webhook): add webhook.eventLoggingEnabled and webhook.eventLoggingVerbose properties

orca/orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForCapacityMatchTask.java
Most likely a groovy/java change in past - java file string formatting doesn't work this way.
=> fix(logs): Fix log message formatting 

orca/orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/DelegatingKatoRestService.java, orca/orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/KatoRestServiceSpec.groovy, orca/orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/DelegatingKatoRestServiceTest.java
- Fixed requestOperations method signature in DelegatingKatoRestService to ensure `cloudProvider` comes before `clientRequestId`.
- Updated test KatoRestServiceSpec accordingly.
- Prevents 400 errors where UUID was misinterpreted as cloudProvider.
Error:
```
ERROR 1 --- [     handlers-7] c.n.s.orca.q.handler.RunTaskHandler      : [rahulgandhi.chekuri@opsmx.io] Error running DeployManifestTask for pipeline[01K1J9JBP1BDNAHX38R2JYRED1]
com.netflix.spinnaker.kork.retrofit.exceptions.SpinnakerHttpException: Status: 400, Method: POST, URL: http://spin-clouddriver.onlyspinnaker:7002/021b86e19da715828bcc1d917db06cbb25aa7096ad5b11b263d86f866161eedd/ops?clientRequestId=kubernetes, Message: No cloud provider named '021b86e19da715828bcc1d917db06cbb25aa7096ad5b11b263d86f866161eedd' found
at …
```
=> fix(orca/clouddriver): correct parameter order for requestOperations to avoid invalid cloudProvider errors

halyard/halyard-cli/halyard-cli.gradle, halyard/halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java, halyard/halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java, halyard/halyard-cli/src/test/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonServiceTest.java
- Retrofit2 does not support type variables in method return type. So `DaemonService.getTask()` is failing with the following error:
```
Method return type must not include a type variable or
wildcard: com.netflix.spinnaker.halyard.core.tasks.v1.DaemonTask<C, T>
for method DaemonService.getTask 
```
- This PR fixes the issue by manually deserializing the ResponseBody so that retrofit2 doesn't need to know the actual generic types at compile time. 
- Added a test to demonstrate the issue.
=> fix(halyard/retrofit2): fix daemon service getTask API definition

kork/kork-retrofit2/src/main/java/com/netflix/spinnaker/kork/retrofit/Retrofit2ServiceFactory.java, kork/kork-web/kork-web.gradle, kork/kork-web/src/main/java/com/netflix/spinnaker/config/DefaultServiceClientProvider.java, kork/kork-web/src/main/java/com/netflix/spinnaker/kork/client/ServiceClientFactory.java, kork/kork-web/src/main/java/com/netflix/spinnaker/kork/client/ServiceClientProvider.java, orca/orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/config/BakeryConfiguration.groovy, orca/orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/api/BakeryServiceSpec.groovy
- This PR addressed the issue reported in Spinnaker slack channel - https://spinnakerteam.slack.com/archives/C0DPVDMQE/p1755855361456079
- Due to @ Body param being a base class, when passing a subclass, retrofit2 doesn't serealize to subclass with the default Jackson Converter.Factory. So updated Retrofit2ServiceFactory to accept a custom Convertor.Factory.
- Added a test to demonstrate the issue.
=> fix(orca/retrofit2): fix orca bakeservice api

clouddriver/clouddriver-google/src/main/java/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.java, clouddriver/clouddriver-google/src/test/java/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandlerTest.java
From slack:
```
2025-09-03 14:15:56.226 ERROR 45387 --- [tionProcessor-0] c.n.s.c.o.DefaultOrchestrationProcessor  : java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "com.netflix.spinnaker.clouddriver.google.deploy.description.BasicGoogleDeployDescription.getSelectZones()" is null
at com.netflix.spinnaker.clouddriver.google.deploy.handlers.BasicGoogleDeployHandler.setDistributionPolicyToInstanceGroup(BasicGoogleDeployHandler.java:1081)
at com.netflix.spinnaker.clouddriver.google.deploy.handlers.BasicGoogleDeployHandler.createInstanceGroupManagerFromInput(BasicGoogleDeployHandler.java:1063)
at com.netflix.spinnaker.clouddriver.google.deploy.handlers.BasicGoogleDeployHandler.handle(BasicGoogleDeployHandler.java:251)
```
* Primary …
=> fix(gcp): More NPE handling on some input

clouddriver/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/AccountsConfiguration.java, clouddriver/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/AmazonAccountDefinitionSourceConfiguration.java, clouddriver/clouddriver-aws/src/test/java/com/netflix/spinnaker/testconfig/AmazonCredentialsInitializerTest.java
This change allows clouddriver AWS accounts to use the account management API. Specifically, it allows clouddriver to load AWS accounts from the AccountDefinitionRepository used by the account API.
The new config flag `account.storage.aws.enabled`, in addition to the existing config flag `account.storage.enabled`, control when this feature is enabled.  Both are false by default.
=> feat(clouddriver/aws): Implement the account API for aws accounts

clouddriver/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentials.java, clouddriver/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsInitializer.java, clouddriver/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/AssumeRoleAmazonCredentials.java, clouddriver/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/NetflixAmazonCredentials.java, clouddriver/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/NetflixAssumeRoleAmazonCredentials.java, clouddriver/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/NetflixSTSAssumeRoleSessionCredentialsProvider.java, clouddriver/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/AmazonCredentialsParser.java, clouddriver/clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonBasicCredentialsLoaderSpec.groovy, clouddriver/clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonClientProviderSpec.groovy, clouddriver/clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsLoaderSpec.groovy, clouddriver/clouddriver-aws/src/test/java/com/netflix/spinnaker/clouddriver/aws/security/config/AmazonCredentialsParserTest.java, clouddriver/clouddriver-aws/src/test/java/com/netflix/spinnaker/testconfig/AmazonCredentialsInitializerTest.java, clouddriver/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/security/NetflixECSCredentials.java
when the existing config flag `aws.client.logEndpoints` is true.  It defaults to false.  https://github.com/spinnaker/spinnaker/pull/7239 added that config flag.
=> feat(clouddriver/aws): log the endpoint that aws sdk sts clients use

clouddriver/clouddriver-sql/clouddriver-sql.gradle, clouddriver/clouddriver-sql/src/main/kotlin/com/netflix/spinnaker/clouddriver/sql/security/SqlAccountDefinitionRepository.kt, clouddriver/clouddriver-sql/src/test/kotlin/com/netflix/spinnaker/clouddriver/sql/security/SqlAccountDefinitionRepositoryTest.kt
If a user creates an account with an initial type, say "aws", and then creates another account with the same name but a different type, say "kubernetes", the operation will succeed but the type given by the "type" column will not match the actual type of the account. This causes clouddriver to fail to start as it cannot marshal the account definition jsons into the correct Java objects. Fix this by also updating the "type" column during an update operation.
=> fix(sql): Update account type column during upserts

front50/front50-s3/front50-s3.gradle, front50/front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3BucketProperties.java, front50/front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3ClientFactory.java, front50/front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Properties.java, front50/front50-s3/src/test/java/com/netflix/spinnaker/front50/config/S3ClientFactoryTest.java
- While upgrading front50 to aws sdk v2 in https://github.com/spinnaker/spinnaker/pull/7250, it was mistakenly assumed that the regionOverride was meant for the s3 compatible storage but in reality it was meant only for signerOverride in sdk v1. So with the existing code, for s3 compatible storages, region won't be set and will cause the following error:
```
software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@629bee3b: 
Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region)
```
- This PR fixes the issue by assigning region to S3Builder even for S3 compatible storages.
- A test is added to demonstrate the issue.
=> fix(front50/s3): always configure region in s3 client, when specified
